.circleci/config.yml
appcues/build.gradle
appcues/codecov.gradle
build.gradle
fastlane/Fastfile

Attempt here is to run the debugUnitTest task then the code coverage task, generate xml report with jacoco, then upload that to codecov.io via CircleCI - on merges to main.
codecov is free to open source projects, and once we are happy with it, we could also include a badge and link in our readme.
reporting and history will eventually show up here https://app.codecov.io/gh/appcues/appcues-android-sdk

Add jacoco coverage report generation and CI integration with codecov

---

appcues/src/main/java/com/appcues/ui/extensions/ModifierExt.kt
appcues/src/main/java/com/appcues/ui/modal/BottomSheetModal.kt
appcues/src/main/java/com/appcues/ui/modal/ExpandedBottomSheetModal.kt
appcues/src/main/java/com/appcues/ui/modal/FullScreenModal.kt
appcues/src/main/java/com/appcues/ui/modal/SharedModal.kt

My bad for not explaining it better in the PR.
https://appcues.slack.com/archives/C02EX9N4067/p1653506537818429
per slack conversation there are some properties that can be sent to us but should be ignored. the reason being that builder is saving properties on the fly, and if you change from one type to another they want to keep properties set so it has a better experience on builderside if user decides to go back to that previous block type.

♻️  Ignoring possible phantom properties from the json response

---

appcues/src/main/java/com/appcues/DeeplinkHandler.kt

in addition to the `appcues-{application_id}` scheme, which matches the current app ID - we'll also support a special case of `appcues-democues` for deeplinks that are agnostic of app ID in the Democues usage where you can change the account/app at runtime.

Add support for Democues special case deeplinking logic

---

appcues/src/main/AndroidManifest.xml
appcues/src/main/java/com/appcues/analytics/ExperienceLifecycleTracker.kt
appcues/src/main/java/com/appcues/statemachine/Action.kt
appcues/src/main/java/com/appcues/statemachine/State.kt
appcues/src/main/java/com/appcues/statemachine/StateMachine.kt
appcues/src/main/java/com/appcues/ui/AppcuesActivity.kt
appcues/src/main/java/com/appcues/ui/AppcuesViewModel.kt
appcues/src/main/java/com/appcues/ui/ExperienceRenderer.kt
appcues/src/test/java/com/appcues/statemachine/StateMachineTest.kt

This is a Draft PR to discuss a proposed idea for an issue recently uncovered.
**Issue**: since our AppcuesActivity was set to use `noHistory=true` in commit https://github.com/appcues/appcues-android-sdk/commit/5bedc0096b4779589150b3f1584f23eec4f11c5c (PR #141) - any ExperienceAction that might open up a new Activity would inadvertently kill off a running Experience when launched, even if there was no close action and the expectation was that you could return back to the running Experience.  Example: link to URL - which opens the Chrome Tabs Activity - not good.
**Idea**: revert the `noHistory=true` change and support more robust handling of pause/resume in AppcuesActivity.  The StateMachine can be told to go into a Paused state, remembering the actual state it was in before paused. …

Support Paused state in the StateMachine and logic to render a new Experience if needed

---

appcues/build.gradle
appcues/src/main/AndroidManifest.xml
appcues/src/main/java/com/appcues/action/ActionKoin.kt
appcues/src/main/java/com/appcues/action/ActionRegistry.kt
appcues/src/main/java/com/appcues/action/appcues/RequestReviewAction.kt
appcues/src/main/java/com/appcues/ui/InAppReviewActivity.kt
gradle/tools/detekt/detekt-config.yml

This stacks on top of #160 , since it requires the capability to launch an Activity on top of a running experience.
Using the [Google Play in-app review lib](https://developer.android.com/guide/playcore/in-app-review/kotlin-java) to allow an experience action that can request a review.  Similar to iOS, it's not really guaranteed to show the review, that is up to the internal Play implementation - but we can request.
A new Activity, the InAppReviewActivity is used to launch this review on top of the current experience, with a callback to return when done and allow the Experience action sequence to continue in natural order.
There is a 3 sec timeout in place to return from the review Activity if the Play library never returns a result when asked for the review task.  The Play library only …

Add action for requesting review

---

appcues/src/main/java/com/appcues/debugger/AppcuesDebuggerManager.kt
appcues/src/main/java/com/appcues/debugger/ui/DebuggerFloatingActionButton.kt
appcues/src/main/java/com/appcues/debugger/ui/DebuggerFloatingActionEvents.kt
appcues/src/main/java/com/appcues/debugger/ui/MutableDebuggerState.kt
appcues/src/main/java/com/appcues/util/ContextExt.kt

Initially I tried to research a way to check if the activity was fitting system window or not, but it seems like a impossible task so I moved away from it and went on a different approach.
Now we are drawing on the decorView.root which has similar effect as we had before but in addition to this I had to manually add top/bottom margins to the ComposeView used by the debugger or else the debugger could go under status/navigation bar icons.

🐛 Fix bug to properly display the debugger even when activity is fitsystemwindow false

---

appcues/src/main/java/com/appcues/debugger/AppcuesDebuggerManager.kt

mistake com my part I forgot to include this in last the last PR, very important detail because when debugger manager has not started the debugger yet it will crash saying that currentActivity has not being initialized.

🐛 DebuggerManager stop does nothing in case activity reference is not initialized

---

appcues/src/main/java/com/appcues/Appcues.kt
appcues/src/test/java/com/appcues/AppcuesTest.kt
appcues/src/test/java/com/appcues/analytics/AnalyticsTrackerTest.kt

A few test updates to (A) ensure AnalyticsTracker is publishing the expected tracking data to the analyticsFlow SharedFlow and (B) ensure that Appcues is properly broadcasting that tracking data to any attached AnalyticsListener

Add tests for new AnalyticsListener functionality

---

appcues/codecov.gradle
appcues/src/main/java/com/appcues/AppcuesConfig.kt
appcues/src/test/java/com/appcues/data/AppcuesRepositoryTest.kt

Adding tests for the cache/retry behaviors in the AppcuesRepository, and a few other functions.
Also updated JaCoCo settings to exclude some UI code and some Moshi generated JSON Adapters, Room generated code from the coverage report.

Tests for AppcuesRepository

---

appcues/build.gradle
build.gradle

Update:  the workaround in comment 11 here https://issuetracker.google.com/issues/236612358#comment seems to work for us - so I think we can move forward with this until Room 2.4.3 is released for standard Kotlin 1.7.0 compat.
--------------
Marking this one as a draft, as it unfortunately hits a snag.  I was trying to stay current on Compose updates moving toward stable.
Compose 1.2.0-rc03 appears to require the, now stable, compose compiler 1.2.0.  Related - [Compose is now versioning libraries independently](https://android-developers.googleblog.com/2022/06/independent-versioning-of-Jetpack-Compose-libraries.html)
The 1.2.0 compiler requires Kotlin 1.7.0
Updating to Kotlin 1.7.0 breaks the Room code generation though, unfortunately.  Room 2.5.0-alpha02 appears to resolve the issue, but …

Update to Compose 1.2.0-rc03

---

fastlane/semver.sh
release.sh

stacks on #175 since it includes usages of the docs script
this is modeled after the ios script, which is modeled after Segment - it provides a single command to package up each of our releases
* validate new version is increasing per semver
* update version number in appcues.properties
* generate changelog from git history
* commit and push version change
* make the github release
* publish to maven central (still requires manually releasing the package on sonatype side)
* update docs on github pages for the release
it requires the signing creds (4 variables) be set in the environment as well for the maven part

Add release script for versioning and maven central publish

---

.circleci/config.yml
appcues/publish-maven.gradle
fastlane/Fastfile
fastlane/README.md

I don't think we need these gpr packages created on every merge to main anymore, now that we are publishing as needed on Maven Central.  This was really just a temporary workaround before we made those public.  A merge to main now will just run the code coverage report and upload to codecov.io

Remove the deploy to GitHub package registry

---

appcues/src/main/java/com/appcues/debugger/DebuggerRecentEventsManager.kt

this is a followup on https://app.shortcut.com/appcues/story/35831/show-user-as-unidentified-in-android-debugger-and-clear-events-on-session-reset
to mirror IOS behavior we will clear the recent event list whenever we get a session reset event coming in.

🐛 Clear events from list when SessionReset is sent

---

appcues/src/main/java/com/appcues/ui/extensions/ModifierExt.kt

we werent using properly the radius property for shadow, no I added to the shadow method an extra parameter that takes in consideration the cornerRadius so that we can properly set shadow behind the content its clipped on.

🐛 Properly set shadow using cornerRadius for shape and radius for shadow layer

---

appcues/build.gradle

I noticed that when I updated to Compose 1.2.0-rc03 I had not updated the Accompanist versions to match - fixed here.

Update Accompanist versions to match Compose version

---

appcues/src/main/java/com/appcues/ui/AppcuesViewModel.kt

This is a bit of a subtle one, but I think it is the proper fix for what I'm observing in the bug in this ticket.
Previously, when an Experience was being dismissed - killing it off - it would send a `Pause` action to the state machine, since it was in the `appcuesViewModelScope` and the `AppcuesViewModel.onPause()` was being triggered.  But the VM was actually detached by this point, as it was being closed, and we should not be sending a `Pause` action in this case - which is more appropriately handled now by using the `viewModelScope` for this StateMachine call - which will go out of scope when the VM is dying off.
The issue this caused was that the StateMachine would get into a `Paused` state, erroneously, as the first Experience was closed out.  This Experience would never `Resume` …

Only trigger pause and resume in the state machine with the AppcuesViewModel is active

---

appcues/src/main/java/com/appcues/statemachine/StepReference.kt
appcues/src/main/java/com/appcues/ui/AppcuesViewModel.kt

crazy bug to find at this point in the project.
StepIndex worked for simple flows, but we needed a way to find the correct step index based on the index value from within a step group.

🐛 Adding StepGroupPageIndex as step reference for swipe trait

---

appcues/src/debug/java/com/appcues/CompositionTestHelper.kt
appcues/src/main/java/com/appcues/ui/AppcuesCompositions.kt
appcues/src/main/java/com/appcues/ui/primitive/ExperiencePrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/ImagePrimitive.kt

This is a new approach that I've found workable for loading images from our snapshot testing library - allow an optional override of the Coil `ImageLoader` that gets send down into the composition using a `CompsitionLocalProvider`.  By default, it's null, and the normal logic stays the same.  In tests, we can pass in our own ImageLoader that loads static resources synchronously.  Will post the updates to the test code in the spec repo.

Add support for mocking Coil ImageLoader for testing

---

appcues/build.gradle
appcues/dokka.gradle

This fix will correct an issue that allowed our debug source public interface for snapshot testing to show up in the published docs from Dokka. I have already pushed the fix to the public docs.

Configure dokka to ignore debug source set files

---

appcues/build.gradle

https://android-developers.googleblog.com/2022/07/jetpack-compose-1-2-is-now-stable.html
We're now able to use stable 1.2.0 Compose, and the accompanying stable 0.25.0 of the Accompanist libs 🎉
Also, Room 2.4.3 has the fix for [this bug](https://issuetracker.google.com/issues/236612358) that we had to work around with Kotlin 1.7.0, so patched that up.

Update dependencies for Compose, Accompanist, and Room

---

appcues/src/main/java/com/appcues/debugger/AppcuesDebuggerManager.kt

Discovered during some UI testing that we had this cast to `FragmentActivity` in the `AppcuesDebuggerManager` that may not always be valid - updating this to use `as?` to be safe.

Update to use safe cast in Debugger

---

appcues/src/main/java/com/appcues/logging/Logcues.kt

Propose taking this item out at this point for the sake of higher customer confidence in the product.  It was used earlier on to allow for finding/fixing crashes early.

Remove code allowing crashes in Debug log mode

---

appcues/src/main/java/com/appcues/statemachine/StateMachine.kt
appcues/src/main/java/com/appcues/statemachine/Transition.kt
appcues/src/main/java/com/appcues/ui/AppcuesActivity.kt
appcues/src/main/java/com/appcues/ui/AppcuesViewModel.kt

Issue found in UI testing
If the `AppcuesActivity` goes through pause/resume, it can trigger extraneous `step_seen` analytic events, since the Resume will reset the state machine back to `RenderingStep` and trigger the listener again.

Fix analytics reporting during activity pause/resume

---

appcues/src/main/java/com/appcues/analytics/AutoPropertyDecorator.kt
appcues/src/main/java/com/appcues/util/ContextResources.kt

_userAgent was being put into the hashMap async which could lead to unwanted ConcurrentModificationException.

🐛 Fix to ConcurrencyModificationException on AutoPropertiesDecorator

---

appcues/src/main/java/com/appcues/ui/extensions/ModifierExt.kt
appcues/src/main/java/com/appcues/ui/primitive/ImagePrimitive.kt
appcues/src/main/java/com/appcues/ui/utils/AppcuesAspectRatioModifier.kt

This should resolve the remaining discrepancies found in UI test cases for various image fit/fill/sizing options.
The core of the issue appears to be the handling of the [Compose `.aspectRatio` Modifier](https://developer.android.com/reference/kotlin/androidx/compose/foundation/layout/package-summary#(androidx.compose.ui.Modifier).aspectRatio(kotlin.Float,kotlin.Boolean)).  This modifier takes a param for `matchHeightConstraintsFirst` that is fundamentally inflexible compared to how [SwiftUI](https://developer.apple.com/documentation/swiftui/view/aspectratio(_:contentmode:)-771ow) adapts the aspect ratio to do different things based on the content model (FIT vs FILL) - when finding which constraint it will allow to stretch.
After a lot of experimentation, I ended up making my own Modifier …

Fix image layout handling

---

appcues/build.gradle

Update from 3.1.4 to 3.1.6 brings a few internal fixes https://github.com/InsertKoinIO/koin/blob/main/CHANGELOG.md.  This version was created back on April 18, 2022.

Update Koin to version 3.1.6

---

appcues/src/main/java/com/appcues/ui/extensions/StyleComponentExt.kt
appcues/src/main/java/com/appcues/ui/primitive/HorizontalStackPrimitive.kt

Fairly simple proposed fix for the issue noted here https://app.shortcut.com/appcues/story/39841/image-sizing-issues-from-ui-tests about hstack alignment discrepancies between ios/android
allow the row level vertical alignment to apply to the items within, rather than setting them to CenterVertically by default - that is still the fallback default if nothing else set.

Support row level vertical alignment specification

---

appcues/src/main/java/com/appcues/Appcues.kt

makes this available on the companion for access from `Appcues.version` directly - don't need an instance. Matches iOS and simplifies things like using in Democues where the instance is not created initially until the account/app input is set.
and remove the build type

Simplify access to SDK version

---

appcues/src/main/java/com/appcues/logging/Logcues.kt
appcues/src/main/java/com/appcues/ui/AppcuesActivity.kt
appcues/src/main/java/com/appcues/ui/AppcuesCompositions.kt
appcues/src/main/java/com/appcues/ui/primitive/ExperiencePrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/ImagePrimitive.kt
appcues/src/test/java/com/appcues/action/ActionRegistryTest.kt

Minor improvement in logging - noticed while working on dependencies in Xamarin binding that Coil can silently fail for various reasons and our logging did not give any indication as to why.

Add error logging when Coil fails to load images

---

appcues/src/debug/java/com/appcues/CompositionTestHelper.kt

This is just a detail missed yesterday in #219 - we have this helper function that snapshot tests use to test primitive rendering, and it needs the same LocalLogcues option provided, otherwise tests can throw exceptions.

Add new LocalLogcues provider to the function used in snapshot testing for primitives

---

appcues/src/main/java/com/appcues/ui/AppcuesActivity.kt
appcues/src/main/res/values/themes.xml

While preparing Ionic samples I noticed that the debugger was not properly being displayed on top of experiences. this is because of a change for a previous bug we worked on, so instead of using fitSystemWindow=true that forces the activity content (decorView) to apply padding we are applying the padding ourselves in root composition, this way we dont mess up with debugger standard behavior to apply padding.
PS: accidentally pushed UI tests updates to main, but here is the commit: https://github.com/appcues/appcues-mobile-experience-spec/commit/c292d23588bbea15fab925102b7b68d5ea98756a

🐛 Fix debugger position overlayed on Experiences

---

appcues/src/main/java/com/appcues/data/model/ExperiencePrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/ExperiencePrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/OptionSelectPrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/TextInputPrimitive.kt
appcues/src/main/res/drawable/appcues_ic_check_box_selected.xml
appcues/src/main/res/drawable/appcues_ic_check_box_unselected.xml
appcues/src/main/res/drawable/appcues_ic_radio_button_selected.xml
appcues/src/main/res/drawable/appcues_ic_radio_button_unselected.xml

Spent some time looking at UI options and implemented a basic first version that just uses standard controls for now.  We don't have final requirements for how this is actually supposed to look and the related stying options, so I'm just going to checkpoint this work here for now and go look at the actual persisting/reporting of user input state portion.  We can come back to UI styling when the requirements are known.
| checkbox - vertical | checkbox - horizontal | radio | picker |
| ---- | ----- | ----- | ----|
| ![checkbox_vert](https://user-images.githubusercontent.com/19266448/187491157-fd704ef6-0ba4-4f4c-8d62-731b7e87c883.gif) | ![checkbox_horiz](https://user-images.githubusercontent.com/19266448/187491314-ea5acdaf-ac3d-4fdf-8604-b02de6b9dbb0.gif) | …

Implement initial UI controls for textInput and optionSelect primitives

---

appcues/src/main/java/com/appcues/ui/primitive/OptionSelectPrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/TextInputPrimitive.kt

* optionSelect - ensure `verticalList` form is used as fallback for any invalid settings
* textField - revisions to provide a more basic / standardized look and feel - using OutlinedTextField but with no label animation or highlight colors, a border defined by `textFieldStyle.borderColor`; special case control that defaults to fill available width (`fillMaxWidth()` usage here)

Revise the UI for form input controls from review/feedback

---

appcues/src/main/java/com/appcues/data/mapper/step/primitives/OptionSelectPrimitiveMapper.kt
appcues/src/main/java/com/appcues/data/mapper/step/primitives/TextInputPrimitiveMapper.kt
appcues/src/main/java/com/appcues/data/model/ExperiencePrimitive.kt
appcues/src/main/java/com/appcues/data/remote/response/step/primitive/PrimitiveResponse.kt
appcues/src/main/java/com/appcues/ui/primitive/OptionSelectPrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/TextInputPrimitive.kt
appcues/src/main/res/drawable/appcues_ic_drop_down.xml

This gets things up to speed with the model changes in https://github.com/appcues/appcues-mobile-experience-spec/pull/74
Also, adds the `picker` styling to match general speculation about what it should look like from recent convos

Update form controls for latest model spec changes

---

appcues/src/main/java/com/appcues/ui/primitive/TextInputPrimitive.kt

Minor update, but no reason we would need `OutlinedTextField` really, since we draw our own border around the input based on the component JSON definition.
Side note, came up in discussion that the Compose TextField bakes in 16dp padding around the input, which cannot easily be adjusted or edited based on `textFieldStyle` in the JSON.  It looks like to do so, we'd need to do something like this https://stackoverflow.com/a/68601606 and copy the TextField source and modify it - hoping to avoid that.  Maybe 16dp default padding is ok here, similar to radio and checkbox padding, to give standard Android touch target behaviors.

Simplify to use TextField instead of OutlinedTextField

---

appcues/src/main/java/com/appcues/ui/primitive/ButtonPrimitive.kt

This change allows button content to be horizontally aligned leading/trailing, if inside of a button that is not autosized - a fixed or full width button.

Fix horizontal alignment of content within Button of larger width

---

appcues/src/main/java/com/appcues/ui/primitive/OptionSelectPrimitive.kt

Bug found in testing recent work - this is so the custom selection mode (not a typical radio/checkbox) like the `8` option shown here will use the defined selected style.
More generally, the data model allows optional custom selected style in any context, which should now be respected.

Ensure selectedContent is used, if available, for selected item(s) in optionSelect

---

appcues/src/main/java/com/appcues/analytics/ExperienceLifecycleEvent.kt
appcues/src/main/java/com/appcues/analytics/ExperienceLifecycleTracker.kt
appcues/src/main/java/com/appcues/data/model/Step.kt
appcues/src/main/java/com/appcues/ui/AppcuesActivity.kt
appcues/src/main/java/com/appcues/ui/ExperienceStepFormState.kt
appcues/src/main/java/com/appcues/ui/primitive/OptionSelectPrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/TextInputPrimitive.kt

Adds our form state object `ExperienceStepFormState` to the domain model for `Step`, and then use this value in the CompositionLocal that gets sent into the compose primitives.  This way, we can retain the form state in the domain model as the user moves through steps, and restore previous values if they return to a step.  It also has the data prepared in a way that makes it easy to submit analytics from the Experience and Step model later on.
This change also takes a first pass at formatting the `appcues:v2:step_interaction` event with the `interactionType` and `interactionData` from the initial proposal. This form is still TBD, but this gets some initial structure in place that we can fine tune formatting on as needed later.
There are still some details to polish up, and I'll note …

Add support for maintaining form state at Step level, initial analytics tracking

---

appcues/src/debug/java/com/appcues/CompositionTestHelper.kt
appcues/src/main/java/com/appcues/ui/extensions/ModifierExt.kt
appcues/src/main/java/com/appcues/ui/primitive/OptionSelectPrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/TextInputPrimitive.kt

Some touch up work on the optionSelect and textInput components from recent snapshot test review and related iOS work.
* The optionSelect primitive now uses the `controlPosition` alignment value to derive the alignment of the parent vertical or horizontal stack.  ex: a verticalList layout with controlPosition of trailing will align the rows within the column to trailing edge - allowing the checkboxes or radio buttons to line up consistently.
* The ComposeContent helper is updated to wrap the composition in the AppcuesTheme, as it was discovered that the lack of this could lead to some discrepancy in the snapshot test results versus actual rendered content - this should make the tests more realistic
* The textInput primitive will now respect additional styling settings that were missed …

Additional clean up on form controls from test review

---

appcues/src/main/java/com/appcues/analytics/AnalyticsTracker.kt
appcues/src/main/java/com/appcues/analytics/ExperienceLifecycleEvent.kt
appcues/src/main/java/com/appcues/analytics/ExperienceLifecycleTracker.kt
appcues/src/main/java/com/appcues/data/MoshiConfiguration.kt
appcues/src/main/java/com/appcues/data/remote/adapters/ExperienceStepFormStateAdapter.kt
appcues/src/main/java/com/appcues/debugger/DebuggerRecentEventsManager.kt
appcues/src/main/java/com/appcues/debugger/model/DebuggerEventItem.kt
appcues/src/main/java/com/appcues/debugger/ui/details/DebuggerEventDetails.kt
appcues/src/main/java/com/appcues/ui/ExperienceStepFormState.kt
appcues/src/main/java/com/appcues/ui/primitive/OptionSelectPrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/TextInputPrimitive.kt
appcues/src/main/java/com/appcues/util/StringExt.kt
appcues/src/main/res/values/strings.xml

This is the next pass at our survey control analytics, cleaning up a few things along the way.
* support adding the question/answer pairs as profile attributes with `_appcuesForm_` prefix, matching web behavior. This occurs in `ExperienceLifecycleTracker.trackFormSubmission`
* support showing the form results interaction data nicely in the debugger, matching iOS.  This led to some more cleanup where I allowed storing the `ExperienceStepFormState` in the custom attributes of the event directly, then use a Moshi adapter to control how the resulting "formResult" JSON mapping occurs on the network request.  Having the full object model in the in-memory attributes makes it simpler to reference this data in the debugger, not having to dig into nested maps - and is very much like the approach …

Survey control updates and analytics

---

appcues/src/main/java/com/appcues/analytics/ExperienceLifecycleTracker.kt
appcues/src/main/java/com/appcues/statemachine/State.kt
appcues/src/main/java/com/appcues/statemachine/Transitions.kt
appcues/src/test/java/com/appcues/analytics/AnalyticsTrackerTest.kt
appcues/src/test/java/com/appcues/analytics/ExperienceLifecycleTrackerTest.kt
appcues/src/test/java/com/appcues/statemachine/StateMachineTest.kt

This ended up being an easy fix, so knocking out.  We already knew in the EndExperience action whether we should mark a flow complete or use the default behavior (if on last step, its complete).  This just updates the EndingStep state to also be aware of this flag, and then add similar logic around whether or not to record step_completion analytic.
For now, form submission (step_interaction) is also tied to this same logic, but this will change in the near future as we build the new survey submission action support.

Do not trigger step_completed when dismissing experience early

---

appcues/src/main/java/com/appcues/data/MoshiConfiguration.kt
appcues/src/main/java/com/appcues/data/remote/request/ActivityRequest.kt

This adds a new annotation `@SeralizeNull`, that can be used on our Moshi JSON models to indicate a field should serialize the null value, rather than being omitted in the output (default behavior).  Idea is inspired by https://stackoverflow.com/a/52265735 .
The reason this came up - when you unset the `groupId` on a group call, passing null, this is meant to remove the associated group for the current user.  Right now, it will just post a payload to the API that removes the `group_id` property entirely, on android:
```js
{
"request_id": "1c3bcc00-bd7d-426f-9df7-660b9f458442",
"user_id": "default-00000",
"account_id": "123"
}
```
This will make it match iOS instead, like
```js
{
"request_id": "1c3bcc00-bd7d-426f-9df7-660b9f458442",
"user_id": "default-00000",
"account_id": "123", …
```

Fix group_id null value not being sent when cleared

---

fastlane/Fastfile

Will need to propagate to all the other Android deploy scripts in other repos.

Truncate changelog to 500 chars for Google Play API limit

---

appcues/src/main/java/com/appcues/action/ActionKoin.kt
appcues/src/main/java/com/appcues/action/appcues/CloseAction.kt
appcues/src/main/java/com/appcues/analytics/ExperienceLifecycleTracker.kt
appcues/src/main/java/com/appcues/statemachine/Action.kt
appcues/src/main/java/com/appcues/statemachine/State.kt
appcues/src/main/java/com/appcues/statemachine/StateMachine.kt
appcues/src/main/java/com/appcues/statemachine/Transitions.kt
appcues/src/main/java/com/appcues/trait/TraitKoin.kt
appcues/src/main/java/com/appcues/trait/appcues/SkippableTrait.kt
appcues/src/main/java/com/appcues/ui/AppcuesViewModel.kt
appcues/src/main/java/com/appcues/ui/ExperienceRenderer.kt
appcues/src/test/java/com/appcues/action/appcues/CloseActionTest.kt
appcues/src/test/java/com/appcues/analytics/ExperienceLifecycleTrackerTest.kt
appcues/src/test/java/com/appcues/statemachine/StateMachineTest.kt
appcues/src/test/java/com/appcues/ui/ExperienceRendererTest.kt

these are the same logical changes as were applied on iOS in https://github.com/appcues/appcues-ios-sdk/pull/249, plus the logic adjustment in https://github.com/appcues/appcues-ios-sdk/pull/250
* when processing the transition from rendering step to ending step, only mark the step complete if we are moving forward in the experience.  moving backward (i.e. previous button) will not trigger step_completed analytics
* remove other logic that was being layered on top of the `markComplete` flag in the state (the `isStepCompleted` and `isExperienceCompleted`, as the state is now the true source of whether it should be marked complete
* refactor to process all `EndExperience` actions through a single funnel in the `ExperienceRenderer.dismissCurrentExperience` function - this allows us to …

Fix step_completed event being improperly triggered on backwards navigation

---

appcues/src/main/java/com/appcues/AnalyticsPublisher.kt
appcues/src/main/java/com/appcues/Appcues.kt
appcues/src/main/java/com/appcues/AppcuesKoin.kt
appcues/src/main/java/com/appcues/data/model/ExperienceStepFormState.kt
appcues/src/main/java/com/appcues/data/remote/adapters/ExperienceStepFormStateAdapter.kt
appcues/src/test/java/com/appcues/AnalyticsPublisherTest.kt
appcues/src/test/java/com/appcues/AppcuesTest.kt

with this change not only we send the form state over to platform but we can also listen for this event using the SDK listener to grab the entire map of properties

♻️  Sanitizing Date values to Double when publishing analytics

---

appcues/src/main/java/com/appcues/AppcuesKoin.kt
appcues/src/main/java/com/appcues/analytics/AnalyticsEvent.kt
appcues/src/main/java/com/appcues/data/AppcuesRepository.kt
appcues/src/main/java/com/appcues/data/mapper/experience/ExperienceMapper.kt
appcues/src/main/java/com/appcues/data/model/Experience.kt
appcues/src/main/java/com/appcues/data/model/Experiment.kt
appcues/src/main/java/com/appcues/data/remote/response/ExperimentResponse.kt
appcues/src/main/java/com/appcues/data/remote/response/QualifyResponse.kt
appcues/src/main/java/com/appcues/data/remote/response/experience/ExperienceResponse.kt
appcues/src/main/java/com/appcues/ui/ExperienceRenderer.kt
appcues/src/test/java/com/appcues/action/appcues/SubmitFormActionTest.kt
appcues/src/test/java/com/appcues/data/AppcuesRepositoryTest.kt
appcues/src/test/java/com/appcues/data/remote/retrofit/stubs/ContentModalOneStubs.kt
appcues/src/test/java/com/appcues/mocks/ExperienceMocks.kt
appcues/src/test/java/com/appcues/statemachine/StateMachineTest.kt
appcues/src/test/java/com/appcues/ui/ExperienceRendererTest.kt

similar updates to the [iOS changes here](https://github.com/appcues/appcues-ios-sdk/pull/258)
* decode a top level `experiments` mapping on the `QualifyResponse`
* add support for an optional `experiment_id` on the `ExperienceResponse`
* add mapping for an optional `Experiment` object on the `Experience`, when a matching experiment is found for the `experiement_id`
* modify `ExperienceRenderer` to support experiment logic, if there is a matching experiment for an `Experience` being rendered:
* if group is `control` - block rendering the experience and move on to next priority, if any
* if not (group `exposed`) - continue rendering the experience as usual
* in both cases, trigger an `appcues:experiment_entered` analytic for the user, with the group and experiment ID
note: a bit of work …

Add support for experiments

---

appcues/src/main/java/com/appcues/data/AppcuesRepository.kt
appcues/src/main/java/com/appcues/data/mapper/experience/ExperienceMapper.kt
appcues/src/main/java/com/appcues/data/remote/response/ExperimentResponse.kt
appcues/src/main/java/com/appcues/data/remote/response/QualifyResponse.kt
appcues/src/test/java/com/appcues/data/AppcuesRepositoryTest.kt

Discovered the JSON representation is an array, not a dictionary as previously thought from the ticket - this fixes up.

Update experiments for array representation in JSON

---

appcues/src/main/java/com/appcues/SessionMonitor.kt
appcues/src/main/java/com/appcues/analytics/AnalyticsQueueProcessor.kt
appcues/src/main/java/com/appcues/analytics/AutoPropertyDecorator.kt
appcues/src/main/java/com/appcues/analytics/ExperienceLifecycleTracker.kt
appcues/src/main/java/com/appcues/analytics/SdkMetrics.kt
appcues/src/main/java/com/appcues/data/AppcuesRepository.kt
appcues/src/main/java/com/appcues/data/mapper/experience/ExperienceMapper.kt
appcues/src/main/java/com/appcues/data/model/Experience.kt
appcues/src/main/java/com/appcues/data/remote/AppcuesRemoteSource.kt
appcues/src/main/java/com/appcues/data/remote/request/ActivityRequest.kt
appcues/src/main/java/com/appcues/data/remote/retrofit/AppcuesService.kt
appcues/src/main/java/com/appcues/data/remote/retrofit/RetrofitAppcuesRemoteSource.kt
appcues/src/main/java/com/appcues/data/remote/retrofit/RetrofitWrapper.kt
appcues/src/main/java/com/appcues/debugger/DebuggerRecentEventsManager.kt
appcues/src/main/java/com/appcues/trait/AppcuesAnimatedTraitVisibility.kt
appcues/src/main/java/com/appcues/trait/appcues/BackdropTrait.kt
appcues/src/main/java/com/appcues/ui/AppcuesViewModel.kt
appcues/src/main/java/com/appcues/ui/composables/AppcuesComposition.kt
appcues/src/main/java/com/appcues/ui/composables/CompositionRemembers.kt
appcues/src/main/java/com/appcues/ui/modal/BottomSheetModal.kt
appcues/src/main/java/com/appcues/ui/modal/DialogModal.kt
appcues/src/main/java/com/appcues/ui/modal/ExpandedBottomSheetModal.kt
appcues/src/main/java/com/appcues/ui/modal/FullScreenModal.kt
appcues/src/main/res/values/strings.xml
appcues/src/test/java/com/appcues/data/AppcuesRepositoryTest.kt

The idea here is to use a static registry of metrics by request ID - in `SdkMetrics`.  This is where other spots can track key points in the qualification/rendering lifecycle
* the moment the analytic comes in to the sdk
* when it is sent out in the network request
* when it returns from the network
* when it starts presentation in the UI
Then, when the `experience_started` analytic is trigged on initial render, we can capture and send the new `_sdkMetrics` node in the attributes, for reporting usage.
A few approaches are used to keep this metrics collection from bloating in size at runtime
* only adds entries for things that might potentially trigger qualification - analytics sent in that are "interactive" / processed immediately (i.e. the customer app screens and events).  Does not …

Add SDK metrics to capture timings around experience rendering

---

appcues/src/main/java/com/appcues/analytics/ExperienceLifecycleEvent.kt
appcues/src/main/java/com/appcues/data/mapper/step/primitives/OptionSelectPrimitiveMapper.kt
appcues/src/main/java/com/appcues/data/mapper/step/primitives/TextInputPrimitiveMapper.kt
appcues/src/main/java/com/appcues/data/model/ExperiencePrimitive.kt
appcues/src/main/java/com/appcues/data/model/ExperienceStepFormState.kt
appcues/src/main/java/com/appcues/data/remote/response/step/primitive/PrimitiveResponse.kt
appcues/src/test/java/com/appcues/action/appcues/SubmitFormActionTest.kt
appcues/src/test/java/com/appcues/data/mapper/step/primitives/OptionSelectPrimitiveMapperTest.kt

Adds an optional additional profile attribute if the `attributeName` is specified in the primitive JSON props.

Add support for custom attribute name to store survey question results

---

release.sh

Mirroring the fix discovered on the iOS side here https://github.com/appcues/appcues-ios-sdk/pull/268

Update release script to be explicit about branch name

---

appcues/src/main/java/com/appcues/data/mapper/experience/ExperienceMapper.kt
appcues/src/main/java/com/appcues/data/model/Experiment.kt
appcues/src/main/java/com/appcues/data/remote/response/ExperimentResponse.kt
appcues/src/main/java/com/appcues/data/remote/response/experience/ExperienceResponse.kt
appcues/src/main/java/com/appcues/ui/ExperienceRenderer.kt
appcues/src/test/java/com/appcues/data/remote/retrofit/stubs/ContentModalOneStubs.kt
appcues/src/test/java/com/appcues/ui/ExperienceRendererTest.kt

Once we had a real test response to try out, discovered a misunderstanding in the requirements around how the response would look. We need to link the experiment and experience as shown here - matching on the experience ID inside of the experiments array. There is no experiment_id in the experience response object.

Fix logic that links experiments and experiences in response

---

appcues/src/debug/java/com/appcues/CompositionTestHelper.kt
appcues/src/main/java/com/appcues/ui/composables/AppcuesComposition.kt
appcues/src/main/java/com/appcues/ui/composables/CompositionLocals.kt
appcues/src/main/java/com/appcues/ui/extensions/ModifierExt.kt
appcues/src/main/java/com/appcues/ui/primitive/EmbedHtmlPrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/ExperiencePrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/HorizontalStackPrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/ImagePrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/SpacerPrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/VerticalStackPrimitive.kt
appcues/src/main/java/com/appcues/ui/utils/AppcuesAspectRatioModifier.kt
appcues/src/main/java/com/appcues/ui/utils/ComposeConstraintsExt.kt

Updating the AspecRatio reader logic to fit specs for Side-by-side content.
Before this change aspectRatio was calculated based only on the target primitive, now by knowning [stackScope](https://github.com/appcues/appcues-android-sdk/pull/258/files#diff-ba5fc2a50d116a563e61531b0fc5fb60f4d2538b904a422b789db5cf004a4d56R45) and by each primitive reporting its own size [here](https://github.com/appcues/appcues-android-sdk/pull/258/files#diff-cf90f453a88a858b5ab8c9546f22d74473fff88d732c9875114c33bf846569faR88) we can better define how Constraint.findSize()  works to mirror Web builder and IOS renderings.
updating tests with this change in [this PR](https://github.com/appcues/appcues-mobile-experience-spec/pull/106).

♻️ Updated Size finder logic to match specs

---

appcues/src/main/java/com/appcues/ui/extensions/ModifierExt.kt
appcues/src/main/java/com/appcues/ui/modal/BottomSheetModal.kt
appcues/src/main/java/com/appcues/ui/modal/DialogModal.kt
appcues/src/main/java/com/appcues/ui/modal/ExpandedBottomSheetModal.kt
appcues/src/main/java/com/appcues/ui/modal/FullScreenModal.kt
appcues/src/main/java/com/appcues/ui/modal/SharedModal.kt

Changing some of the UI behavior to consider and fit properly in order the cornerRadius + BorderWidth, taking into consideration possible background. reflected UI tests is [here](https://github.com/appcues/appcues-mobile-experience-spec/pull/109).
the only difference between builder and Android is the clipping of the primitive based on cornerRadius + padding, this is unusual behavior for Compose and will lead to unwanted clipping for things like negative margin and shadows

🐛 Fix bug where corner Radius and border width was not properly applied

---

appcues/build.gradle
appcues/src/main/AndroidManifest.xml
appcues/src/main/java/com/appcues/ui/AppcuesActivity.kt
appcues/src/main/java/com/appcues/ui/composables/AppcuesComposition.kt
appcues/src/main/java/com/appcues/ui/composables/CompositionRemembers.kt
appcues/src/main/res/layout/appcues_activity_layout.xml

working around a previous issue from delivery-hero (customer) we now have a appcues_activity_layout.xml containing the container for our composition, then we can set fitsSystemWindow to true without introducing unwanted behavior from activity customization. updated UI [tests PR](https://github.com/appcues/appcues-mobile-experience-spec/pull/114)

🐛 Fix bug with virtualkeyboard on scrollable content

---

appcues/src/main/AndroidManifest.xml
appcues/src/main/java/com/appcues/ui/AppcuesActivity.kt
appcues/src/main/java/com/appcues/ui/composables/AppcuesComposition.kt
appcues/src/main/java/com/appcues/ui/composables/CompositionLocals.kt
appcues/src/main/java/com/appcues/ui/primitive/EmbedHtmlPrimitive.kt
appcues/src/main/res/layout/appcues_activity_layout.xml

To support a fullscreen button on an embedded video inside of a WebView, we need to implement a custom `AccompanistWebChromeClient` and override the `onShowCustomView` and `onHideCustomView` functions. These calls get invoked to pass a `View` that should be shown/hidden respectively, when the user toggles that button. The general concept for hooking into the Accompanist WebView chrome client was modeled after ideas in https://github.com/google/accompanist/pull/1113. Some of the other implementation details were inspired by https://github.com/akhgupta/WebviewVideo/blob/master/src/com/example/webview/MyActivity.java#L99.
This implementation shows the new custom view by using an empty, hidden `FrameLayout` in the root activity layout, which is then used as a custom view container, …

Fix embed video expansion to full screen

---

appcues/src/main/java/com/appcues/trait/BackdropDecoratingTrait.kt
appcues/src/main/java/com/appcues/trait/TraitKoin.kt
appcues/src/main/java/com/appcues/trait/TraitRegistry.kt
appcues/src/main/java/com/appcues/trait/appcues/BackdropTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/KeyholeTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/SkippableTrait.kt
appcues/src/main/java/com/appcues/ui/composables/AppcuesComposition.kt

Before this change, backroptraits were rendering one on top of the other, as totally different compositions, now its all in the same end composition, in a way that you can (if desired) alter the composition coming from the ApplyBackdropTrait chain. an example of this is found on KeyholeTrait, which is not accepting any styling options for now but works as a proof of concept and will be updated later.

♻️  Update backdrop trait behavior inside composition to enable keyhoole trait

---

README.md
samples/kotlin-android-app/build.gradle

NOTE: targeting new `release/1.2 branch`
Now that we have a `1.2.0` release branch going, cherry picking a couple of minor updates from `main` that were after `1.1.1` but not related to any of the longer term trait 2.0 work. 
This is really just to keep things in clean state, branch hygiene - one readme doc update and one update to the sample app build minification.

A couple of cherry picks for release/1.2

---

appcues/src/main/java/com/appcues/analytics/ExperienceLifecycleEvent.kt
appcues/src/main/java/com/appcues/data/mapper/experience/ExperienceMapper.kt
appcues/src/main/java/com/appcues/data/model/Experiment.kt
appcues/src/main/java/com/appcues/data/remote/response/ExperimentResponse.kt
appcues/src/main/java/com/appcues/ui/ExperienceRenderer.kt
appcues/src/main/java/com/appcues/util/UuidExt.kt
appcues/src/test/java/com/appcues/ui/ExperienceRendererTest.kt

NOTE: targeting new `release/1.2` branch (branched off 1.1.1 tag)
* capture 2 new properties from the response for experiments
* update the experience_entered analytic to output 3 additional properties and rename another
Also added extension on UUID for analytics string formatting logic shared in a few places

Rework experiment analytics to support new requested properties

---

appcues/src/main/java/com/appcues/Appcues.kt
appcues/src/main/java/com/appcues/DeepLinkHandler.kt
appcues/src/main/java/com/appcues/action/ActionKoin.kt
appcues/src/main/java/com/appcues/action/appcues/LaunchExperienceAction.kt
appcues/src/main/java/com/appcues/data/AppcuesRepository.kt
appcues/src/main/java/com/appcues/data/mapper/experience/ExperienceMapper.kt
appcues/src/main/java/com/appcues/data/model/Experience.kt
appcues/src/main/java/com/appcues/data/model/ExperienceTrigger.kt
appcues/src/main/java/com/appcues/statemachine/Transitions.kt
appcues/src/main/java/com/appcues/ui/ExperienceRenderer.kt
appcues/src/test/java/com/appcues/AppcuesTest.kt
appcues/src/test/java/com/appcues/action/appcues/LaunchExperienceActionTest.kt
appcues/src/test/java/com/appcues/action/appcues/SubmitFormActionTest.kt
appcues/src/test/java/com/appcues/data/AppcuesRepositoryTest.kt
appcues/src/test/java/com/appcues/mocks/ExperienceMocks.kt
appcues/src/test/java/com/appcues/statemachine/StateMachineTest.kt

note: targeting `release/1.2`
This PR introduces the concept of `ExperienceTrigger`, which defines the currently six ways an Experience can be triggered: 
* builder preview
* qualification
* deep link
* show function call
* launch experience action
* post-flow completion action
This context is now stored on the `Experience` object via passing through at call sites as appropriate. This allows us to detect when an Experience is being launched from a method other than the standard qualification flow, and enable pre-step navigation actions to occur if so. Qualified flows are unchanged - as the location in the app they trigger upon is based entirely on the flow settings defined in Studio, and no redirection is done on launch in those cases.
This will enable use cases like redirecting to the …

Allow navigate actions on first step for non-qualifying experience triggers

---

appcues/src/main/java/com/appcues/ui/primitive/ExperiencePrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/OptionSelectPrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/TextPrimitive.kt

note: targeting `release/1.2`
Fixes the issue observed with our `optionSelect` implementation - where the option `content` was replaced with `selectedContent`, but did not actually apply the updated text style due to the `remember` in place on the style object. This `remember` is updated to be based on the style as the key, so it is updated when `style` updates.
The other change in `ExperiencePrimitive.Compose` is to allow us to more effectively apply the click handler _after_ the content styling is completed - so that the shape of the tap gesture feedback matches the selection element.

Fix text style updates not being applied on recomposition

---

appcues/src/main/java/com/appcues/data/mapper/step/primitives/OptionSelectPrimitiveMapper.kt
appcues/src/main/java/com/appcues/data/model/ExperiencePrimitive.kt
appcues/src/main/java/com/appcues/data/remote/response/step/primitive/PrimitiveResponse.kt
appcues/src/main/java/com/appcues/ui/primitive/OptionSelectPrimitive.kt
appcues/src/test/java/com/appcues/data/mapper/step/primitives/OptionSelectPrimitiveMapperTest.kt

note: targeting `release/1.2`
This is the Android implementation of the [proposed spec change](https://github.com/appcues/appcues-mobile-experience-spec/pull/121/files#diff-b4d74ced281deda59b98f155a0fd068ac0bcaa79d3c9fb67cf91023a80f664f4R457-R460) to add `leadingFill` on the `optionSelect` component.
It is only supported for single select components, with `hidden` controlPosition (ratings use cases)
This would apply in cases like the star rating block being built now.

Add leadingFill option for rating components

---

appcues/src/main/java/com/appcues/data/MoshiConfiguration.kt
appcues/src/main/java/com/appcues/data/remote/adapters/TraitResponseAdapterFactory.kt
appcues/src/test/java/com/appcues/data/remote/retrofit/AppcuesServiceTest.kt
appcues/src/test/resources/content/content_duplicate_traits_experience.json
appcues/src/test/resources/content/content_duplicate_traits_group.json
appcues/src/test/resources/content/content_duplicate_traits_step.json

A custom Moshi factory/adapter to allow use to detect malformed experiences and report errors, per 2.0 trait design discussions.
Analogous to the iOS changes in https://github.com/appcues/appcues-ios-sdk/pull/295

Prevent multiple traits of the same type at the same level of an Experience

---

appcues/build.gradle

note: targeting `release/1.1.2`
This change reverts the Koin version back to `3.1.6` instead of `3.2.2` that was used in the SDK 1.1 release. 
The prior change was [here](https://github.com/appcues/appcues-android-sdk/pull/262/files#diff-dc19bb0e566daa0f4286c73260cb0d2b2e3b5a303a2323ff0a01e0fdc17347b9L17), and done to keep current and adopt any internal fixes in Koin. However, we've since learned that this version of Koin conflicts with what is used in Expo development builds, specifically in [expo-dev-launcher](https://github.com/expo/expo/blob/main/packages/expo-dev-launcher/android/build.gradle#L154) where 3.1.2 is used. We cannot move to 3.1.2 due to other issues, but 3.1.6 seems to be compatible in testing.
The 3.2.x issue may be related to what others have reported …

⏪ Revert Koin back to 3.1.6 from 3.2.2 for Expo compatibility

---

appcues/src/main/java/com/appcues/ui/extensions/StyleComponentExt.kt
appcues/src/main/java/com/appcues/ui/primitive/OptionSelectPrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/TextInputPrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/VerticalStackPrimitive.kt

note: targeting `release/1.2`
similar to the update on iOS https://github.com/appcues/appcues-ios-sdk/pull/306
This updates the `textInput` and `optionSelect` components to allow their `label` and `errorLabel` primitives within to apply their own `style.horizontalAlignment` properties, and position the text as desired, relative to the survey options/controls.
This allows for the common case of having a `leading` aligned label/error, and `center` aligned ratings content

Update optionSelect and textInput components to handle label horizontalAlignment

---

appcues/src/main/java/com/appcues/ui/modal/DialogModal.kt

`targeting release/1.3.0`
Added verticalAlignment handling for dialogs

✨ Added verticalAlignment to modal dialog styles

---

appcues/src/main/java/com/appcues/data/mapper/step/primitives/TextPrimitiveMapper.kt
appcues/src/main/java/com/appcues/data/model/ExperiencePrimitive.kt
appcues/src/main/java/com/appcues/data/model/ExperienceStepFormState.kt
appcues/src/main/java/com/appcues/data/remote/response/step/primitive/PrimitiveResponse.kt
appcues/src/main/java/com/appcues/ui/extensions/TextStyleExt.kt
appcues/src/main/java/com/appcues/ui/primitive/BoxPrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/ButtonPrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/HorizontalStackPrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/TextInputPrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/TextPrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/VerticalStackPrimitive.kt
appcues/src/test/java/com/appcues/action/appcues/SubmitFormActionTest.kt
appcues/src/test/java/com/appcues/data/mapper/step/primitives/TextPrimitiveMapperTest.kt
appcues/src/test/java/com/appcues/data/model/ExperienceStepFormStateTest.kt
appcues/src/test/java/com/appcues/mocks/ExperienceMocks.kt

`targeting release/1.3.0`
adds spans as a TextPrimitive property and handles it so whenever we have spans we basically ignore the content sent in "text" and override it with the combined values of all spans.
also when we have only text we map to a single span item so its straight forward way to handle all texts (as span elements).

✨ Added spans property to TextPrimitive

---

appcues/src/main/java/com/appcues/debugger/DebuggerViewModel.kt
appcues/src/main/java/com/appcues/debugger/screencapture/Capture.kt
appcues/src/main/java/com/appcues/debugger/screencapture/ViewExt.kt
appcues/src/main/java/com/appcues/ui/ElementSelector.kt
appcues/src/main/java/com/appcues/util/ContextResources.kt

The only thing using this right now is the FAB tap action from the deep link to /sdk/capture_screen. This matches the model used on the iOS side and defined in the spec for platform. Initially just filling out the Android View hierarchy and device metadata and printing to the log for review.
Next steps will be to handle the screenshot portion, the confirmation dialog, and eventually the integration with the API.
Also want to take another pass and look into the Compose hierarchy capture capabilities, specifically researching how it is done in https://github.com/google/talkback.

Add initial layout capture model and populate from current Activity

---

appcues/src/main/java/com/appcues/trait/appcues/BackdropKeyholeTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/BackdropTrait.kt

Added support for blurRadius to keyhole trait.
Refactored some of backdrop trait too since both use similar code, wanted both traits to look as close as possible.
The current approach is move advanced now using BlenderModes instead of clipping the shape and adding the radius on top of it. 
https://user-images.githubusercontent.com/5244805/217609963-b33a39ab-2c05-499d-beda-7b2fc7704faf.mov

✨ Added property blurRadius for keyhole trait

---

appcues/src/main/java/com/appcues/data/mapper/step/StepMapper.kt
appcues/src/test/java/com/appcues/data/mapper/step/StepMapperTest.kt

targeting `release/1.3.0`
This is a minor update to match the iOS logic as discussed here https://github.com/appcues/appcues-ios-sdk/pull/334#discussion_r1100164652
If the sticky content is a single item (typically a single horizontal stack), then we do not need to wrap that in another vertical stack - just position that horizontal stack directly as the sticky content.  If there are more than one sticky items defined for an edge, then wrap them in the vertical stack as we had before.

Update handling of sticky content for single primitive case

---

appcues/artifacts-android.gradle
appcues/build.gradle
appcues/publish-maven.gradle

`targeting release 1.3.0`
With this change customers can access the source and javadoc through the Android Studio.

✨ Include Source and Javadoc with library .aar

---

appcues/src/main/java/com/appcues/analytics/SdkMetrics.kt
appcues/src/test/java/com/appcues/analytics/SdkMetricsTest.kt

This is the one-liner change discussed when an issue arose on the iOS side with SdkMetrics and concurrent access https://github.com/appcues/appcues-ios-sdk/pull/336, [discussed here](https://appcues.slack.com/archives/C031RLGS4F8/p1676042652884329?thread_ts=1675968353.962369&cid=C031RLGS4F8)
changes
```kotlin
private val metrics = hashMapOf<UUID, SdkMetrics>()
```
to
```kotlin
private val metrics = ConcurrentHashMap<UUID, SdkMetrics>()
```
However, I was never able to see any real issue here in testing. This includes a unit test to exercise concurrent access in the same fashion that made iOS crash in some cases. This seems like perhaps a safe change without a perceived downside, but unclear if it is really needed. Going ahead and posting the work here for review/discussion.

Use a ConcurrentHashMap for SdkMetrics

---

appcues/src/main/java/com/appcues/statemachine/State.kt
appcues/src/main/java/com/appcues/statemachine/StateMachine.kt
appcues/src/main/java/com/appcues/ui/ExperienceRenderer.kt
appcues/src/test/java/com/appcues/statemachine/StateMachineTest.kt
appcues/src/test/java/com/appcues/ui/ExperienceRendererTest.kt

target `release/1.3.1`
Requested change for parity with web, and to make our Studio analytics dashboards more comprehendible for customers. This is the same change as was applied on iOS here https://github.com/appcues/appcues-ios-sdk/pull/345.

Do not mark experience completed if dismissed on the final step

---

appcues/build.gradle
appcues/schemas/com.appcues.data.local.room.AppcuesDatabase/1.json
appcues/schemas/com.appcues.data.local.room.AppcuesDatabase/2.json
appcues/src/main/java/com/appcues/Appcues.kt
appcues/src/main/java/com/appcues/AppcuesKoin.kt
appcues/src/main/java/com/appcues/Storage.kt
appcues/src/main/java/com/appcues/analytics/ActivityRequestBuilder.kt
appcues/src/main/java/com/appcues/data/AppcuesRepository.kt
appcues/src/main/java/com/appcues/data/local/model/ActivityStorage.kt
appcues/src/main/java/com/appcues/data/local/room/AppcuesDatabase.kt
appcues/src/main/java/com/appcues/data/remote/AppcuesRemoteSource.kt
appcues/src/main/java/com/appcues/data/remote/request/ActivityRequest.kt
appcues/src/main/java/com/appcues/data/remote/retrofit/AppcuesService.kt
appcues/src/main/java/com/appcues/data/remote/retrofit/RetrofitAppcuesRemoteSource.kt
appcues/src/test/java/com/appcues/AppcuesTest.kt
appcues/src/test/java/com/appcues/analytics/ActivityRequestBuilderTest.kt
appcues/src/test/java/com/appcues/data/AppcuesRepositoryTest.kt
appcues/src/test/java/com/appcues/data/remote/retrofit/AppcuesServiceTest.kt
appcues/src/test/java/com/appcues/data/remote/retrofit/MockWebServerExt.kt
appcues/src/test/java/com/appcues/data/remote/retrofit/RetrofitAppcuesRemoteSourceTest.kt
appcues/src/test/java/com/appcues/mocks/StorageMock.kt
appcues/src/test/resources/content/empty_qualification.json

targeting `release/1.3.1` - unsure exact timing on when we need this, but sooner rather than later.
The code changes here are not actually that large, but a lot of test updates and new tests, as well as some Room DB schema files. I'll note the important parts inline.
In short, you can identify with this optional new property, supplying a token, which then gets added to the Authorization header on any requests from this user.
```
appcues.identify(userID, mapOf("appcues:user_id_signature" to base64token))
```

Add support for Authorization header on API requests

---

appcues/src/main/java/com/appcues/Appcues.kt
appcues/src/test/java/com/appcues/AppcuesTest.kt

targets `release/1.3.1`
Matching web SDK behavior by adding an `anon:` prefix on any anonymous user ID generated and used in the anonymous() function call. Backend services can use this convention to reliably differentiate anonymous user traffic.

Add anonymous user ID prefix

---

appcues/src/main/java/com/appcues/Appcues.kt
appcues/src/test/java/com/appcues/AppcuesTest.kt
docs/Debugging.md

This is a `main` / 2.0 change (breaking) - we'll no longer support `properties` passed in on `anonymous()` user calls. This is to match the web SDK and comply with data security expectations.

Remove the properties parameter from anonymous function

---

appcues/src/main/java/com/appcues/data/mapper/step/StepMapper.kt
appcues/src/main/java/com/appcues/monitor/AppcuesActivityMonitor.kt
appcues/src/main/java/com/appcues/trait/appcues/BackdropKeyholeTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/TooltipTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/TooltipsPaths.kt
appcues/src/main/java/com/appcues/ui/AppcuesOverlayViewManager.kt
appcues/src/main/java/com/appcues/ui/composables/AppcuesComposition.kt
appcues/src/main/java/com/appcues/ui/extensions/ModifierExt.kt

This pass on tooltip trait comes with some changes.
* AppcuesActivityMonitor and AppcuesOverlay changed to support "subscribing" to the existing activity, I changed to this approach as a way to  re-add our view in case the activity gets destroyed and restored for any reason (orientation changes, layout inspector, etc)
* BackdropKeyHoleTrait now applies, a graphicLayer with 0.99F Alpha to add a new layer that enables BlendMondes to work as [expected](https://stackoverflow.com/questions/73313025/jetpack-compose-canvas-blendmode-not-working-as-expected) 
* Various changes to TooltipTrait files to add support for better positioning the pointer (at the top or bottom of the content). Plus adding in all animation to the animation trait.
* Minor change to AppcuesComposition to add an Spacer …

♻️ Update Tooltip Trait 

---

appcues/src/main/java/com/appcues/ui/AppcuesOverlayViewManager.kt

very easy fix in the end but I took the time to explore different options, in the end enforcing an index was the way to go for our new tooltip view.
I also tried to reposition in other places our views but it doesnt work as well. and also its probably inconsistent between android versions/devices the structure of the decorView, the only thing we know for sure is that there is a decorView, somewhere in there we have android.R.id.content which contains the content (excluding old actionbar). so one of the takes I had was to get the its parent by calling
( findViewById(android.R.id.content).parent as ViewGroup)
and adding the view into this one. the problem is that here on my emulator this one is actually an ActionBarOverlayView which is internal to the android and position views similarly to …

♻️  Ensure Tooltip view is added just after content view

---

appcues/src/main/java/com/appcues/DeepLinkHandler.kt
appcues/src/main/java/com/appcues/debugger/DebugMode.kt
appcues/src/main/java/com/appcues/debugger/DebuggerViewModel.kt
appcues/src/main/java/com/appcues/debugger/screencapture/ScreenCaptureProcessor.kt

stacks on #340 
Small prep work for upcoming API integration - allowing a `token` query parameter on the deep link
```
appcues-{app_id}://sdk/capture_screen?token={jwt}
```
This will come from the builder QR code flow, and allow authentication for screen capture requests coming up. The updates here capture the token and pass it through to spots it will be needed.

Add support for token param on capture_screen deep link

---

appcues/src/main/java/com/appcues/data/remote/customerapi/CustomerApiRemoteSource.kt
appcues/src/main/java/com/appcues/data/remote/imageupload/ImageUploadRemoteSource.kt
appcues/src/main/java/com/appcues/debugger/DebuggerKoin.kt
appcues/src/main/java/com/appcues/debugger/DebuggerViewModel.kt
appcues/src/main/java/com/appcues/debugger/screencapture/Capture.kt
appcues/src/main/java/com/appcues/debugger/screencapture/ScreenCaptureProcessor.kt
appcues/src/main/java/com/appcues/debugger/ui/CaptureConfirmDialog.kt

This change implements the sequence of calls to upload a screenshot and save the screen into the customer account for builder usage. Some cleanup items found and worked along the way
* capture proper screen rect for elements
* capture system window insets (top/bottom bars) for builder usage in metadata
* size bitmap to screen capture size in DP (not a much larger 3x image for instance)

Implement network calls to save screenshot and screen

---

appcues/src/main/java/com/appcues/trait/BackdropDecoratingTrait.kt
appcues/src/main/java/com/appcues/trait/ContainerDecoratingTrait.kt
appcues/src/main/java/com/appcues/trait/ContentHolderTrait.kt
appcues/src/main/java/com/appcues/trait/ContentWrappingTrait.kt
appcues/src/main/java/com/appcues/trait/MetadataSettingTrait.kt
appcues/src/main/java/com/appcues/trait/PresentingTrait.kt
appcues/src/main/java/com/appcues/trait/StepDecoratingTrait.kt
appcues/src/main/java/com/appcues/trait/StickyContentPadding.kt
appcues/src/main/java/com/appcues/trait/TraitExtensions.kt
appcues/src/main/java/com/appcues/trait/appcues/BackgroundContentTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/ModalTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/PagingDotsTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/SkippableTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/TooltipTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/TooltipsPaths.kt
appcues/src/main/java/com/appcues/trait/extensions/TargetRectangleInfoExt.kt
appcues/src/main/java/com/appcues/ui/composables/AppcuesComposition.kt
appcues/src/main/java/com/appcues/ui/composables/StepComposition.kt
appcues/src/main/java/com/appcues/ui/extensions/StyleComponentExt.kt
appcues/src/main/java/com/appcues/ui/modal/BottomSheetModal.kt
appcues/src/main/java/com/appcues/ui/modal/DialogModal.kt
appcues/src/main/java/com/appcues/ui/modal/ExpandedBottomSheetModal.kt
appcues/src/main/java/com/appcues/ui/modal/FullScreenModal.kt
appcues/src/test/java/com/appcues/data/mapper/step/StepMapperTest.kt

Another pass on tooltips, this time focusing on missing properties from trait config.
will note on the code important pieces, but the main goal of this was to better organize the composition and allow for flexibility over wrapperInsets and stickyContentPadding.
this PR got little heavier than expected, this is supposed to tackle down https://app.shortcut.com/appcues/story/48658/tooltip-implement-missing-properties
and https://app.shortcut.com/appcues/story/48660/tooltips-adjust-safe-content-area-for-tooltips

✨ Added remaining props for Tooltips + fix insets padding

---

appcues/src/main/java/com/appcues/debugger/DebuggerViewModel.kt
appcues/src/main/java/com/appcues/debugger/model/DebuggerToast.kt
appcues/src/main/java/com/appcues/debugger/ui/DebuggerComposition.kt
appcues/src/main/java/com/appcues/debugger/ui/MutableDebuggerState.kt
appcues/src/main/java/com/appcues/debugger/ui/ToastView.kt
appcues/src/main/java/com/appcues/ui/theme/AppcuesColors.kt
appcues/src/main/res/values/strings.xml

stacks on #344 
This adds the blue success and pink failure toasts per design. Failure allows a retry.
A new `ToastState` is used in the DebuggerViewModel, in addition to the `UIState`, as toasts are really independent of other UI and can show up on top of whatever other UI state is rendering. They auto dismiss after 3 seconds, or if the background is tapped.
Failure:
https://user-images.githubusercontent.com/19266448/221929787-9b65e1e4-4a21-42d3-a278-a18b6a6738f2.mov
Success:
https://user-images.githubusercontent.com/19266448/221929846-f391e510-66d4-4c33-91bf-ba4ab1a3153d.mov

Add success and failure toast messages on screen capture

---

appcues/src/main/java/com/appcues/ui/composables/AppcuesComposition.kt
appcues/src/main/java/com/appcues/ui/composables/StepComposition.kt

This will do the trick on the `release/1.3.1` branch - the sticky content composition needs the `contentPadding` passed down, just like the main content.
The change will differ on the `main` branch, as now this padding is part of the `modifier` passed through from the content wrapper (modal) -- will PR that separately and we'll handle merge conflicts when the branches sync up.
For example, consider this scrolling full screen modal with a button at the bottom. It has 20px padding all around defined at the modal level - no sticky content. Note, no margin set between the bottom of the last text and the top of the button at bottom.
https://user-images.githubusercontent.com/19266448/222220954-db6845a9-2f02-4c4e-8bfb-e9bb76239469.mov
Now, make that bottom button row `sticky=top`
| Before | …

Apply content padding from modal to the sticky content within

---

appcues/consumer-rules.pro

In #343 some files were moved and others added for network response models that are used in Moshi generated adapters. It was an oversight on my part to not also update the Proguard rules that are needed to keep those adapters from getting optimized away. This was causing broken network behavior and flows not rendering in the sample app.

Fix Proguard consumer-rules for file location changes in network response models

---

appcues/src/main/java/com/appcues/trait/ContainerDecoratingTrait.kt
appcues/src/main/java/com/appcues/trait/ContentWrappingTrait.kt
appcues/src/main/java/com/appcues/trait/StepDecoratingTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/BackgroundContentTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/ModalTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/PagingDotsTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/SkippableTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/TooltipTrait.kt
appcues/src/main/java/com/appcues/ui/composables/AppcuesComposition.kt
appcues/src/main/java/com/appcues/ui/composables/StepComposition.kt
appcues/src/main/java/com/appcues/ui/modal/BottomSheetModal.kt
appcues/src/main/java/com/appcues/ui/modal/DialogModal.kt
appcues/src/main/java/com/appcues/ui/modal/ExpandedBottomSheetModal.kt
appcues/src/main/java/com/appcues/ui/modal/FullScreenModal.kt
appcues/src/test/java/com/appcues/data/mapper/step/StepMapperTest.kt

This is the translation to `main` branch structure for what was updated in #348 on the 1.3.x code branch.
| Before | After |
| --- | --- |
| ![Screenshot 2023-03-01 at 3 56 10 PM](https://user-images.githubusercontent.com/19266448/222263304-f370c865-a2fb-431a-96d3-09fb9e4e317a.png) | ![Screenshot 2023-03-01 at 3 56 47 PM](https://user-images.githubusercontent.com/19266448/222263328-90d5c5b0-eea9-49d8-89eb-5ab629b15ebe.png) |

Ensure sticky content respects the container padding defined in trait style

---

appcues/src/main/java/com/appcues/debugger/ui/ToastView.kt

Requested change from ticket review ([additional chat](https://appcues.slack.com/archives/C02EX9N4067/p1677856940578969?thread_ts=1677856265.136019&cid=C02EX9N4067))

Update screen capture failure toast timeout to 6 seconds

---

appcues/src/main/java/com/appcues/trait/appcues/TooltipTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/TooltipsPaths.kt
appcues/src/main/java/com/appcues/trait/extensions/TargetRectangleInfoExt.kt

Tried as much as possible to simplify how we were trying to handle some of pointer position in relation to the container.
with this change now when we position target-rect closer to the edge, we have special handling of its appearance.
https://user-images.githubusercontent.com/5244805/223538533-7ec0deab-a4c2-40f8-801d-52386f85ea0b.mov

♻️  Updated logic around positioning the edge and corner radius for tooltip container

---

appcues/src/main/java/com/appcues/data/model/ModelExtensions.kt
appcues/src/main/java/com/appcues/debugger/screencapture/ScreenCaptureProcessor.kt
appcues/src/main/java/com/appcues/statemachine/State.kt
appcues/src/main/java/com/appcues/statemachine/StateMachine.kt
appcues/src/main/java/com/appcues/statemachine/Transitions.kt
appcues/src/main/java/com/appcues/trait/appcues/BackdropKeyholeTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/TargetContent.kt
appcues/src/main/java/com/appcues/trait/appcues/TargetElementTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/TargetRectangleTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/TooltipTrait.kt
appcues/src/main/java/com/appcues/trait/extensions/TargetRectangleInfoExt.kt
appcues/src/main/java/com/appcues/ui/AppcuesActivity.kt
appcues/src/main/java/com/appcues/ui/AppcuesOverlayViewManager.kt
appcues/src/main/java/com/appcues/ui/AppcuesViewModel.kt
appcues/src/main/java/com/appcues/ui/AppcuesViewModelFactory.kt
appcues/src/main/java/com/appcues/ui/ElementSelector.kt
appcues/src/main/java/com/appcues/ui/composables/AppcuesComposition.kt
appcues/src/test/java/com/appcues/analytics/ExperienceLifecycleTrackerTest.kt
appcues/src/test/java/com/appcues/statemachine/StateMachineTest.kt

A big chunk of this work was to support propagation of trait errors during rendering, and appropriately ending an experience when that occurs. For example: a selector not found error when trying to render a tooltip step with a target element trait. This was generally handled by changing the completion callback on render from: 
```
val presentationComplete: (() -> Unit),
```
to
```
val presentationComplete: ((ResultOf<Unit, Error>) -> Unit),
```
This applies to the BeginningStep state property that is used in transition to RenderingStep. Now, the UI layer can signal that the presentation failed, via the Error result there, and allow the state machine to be aware of that and transition back out of the experience and trigger the proper analytics.
To actually handle the error, when a trait …

Implement target element trait

---

appcues/build.gradle
appcues/src/main/AndroidManifest.xml
appcues/src/main/java/com/appcues/action/ActionKoin.kt
appcues/src/main/java/com/appcues/action/ActionRegistry.kt
appcues/src/main/java/com/appcues/action/appcues/RequestReviewAction.kt
appcues/src/main/java/com/appcues/ui/InAppReviewActivity.kt

targeting `release/1.3.1` (which will actually be 1.4.0 now)
This is effectively reverting the removal in #205 , brining back the request-review action and the dependency on the Play library to handle it.

Add @appcues/request-review action

---

appcues/src/main/java/com/appcues/trait/appcues/TooltipTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/TooltipsPaths.kt
appcues/src/main/java/com/appcues/trait/extensions/TargetRectangleInfoExt.kt

Updated test run can be checked [here](https://github.com/appcues/appcues-mobile-experience-spec/pull/161)
Adjusted rules around positioning of the tooltip (paddingTop, paddingStart), also general rules about how the tooltip is sized and animated

♻️  Updated Logic around positioning tooltip with distante from target

---

release.sh

A hidden `<fe0f>` was filtering out some emoji we want to include.
If you want to fix the GitHub release notes for the previous releases, you can generate them with this (updating the version tags appropriately)
```sh
git log --pretty=format:"- [%as] %s (%h)"  1.3.0..1.4.0 | sed '/[🔧🎬⬆📸✅💡📝]/d'
```

🔧 Update release changelog emoji exclusion

---

appcues/src/main/java/com/appcues/trait/appcues/TargetContent.kt
appcues/src/main/java/com/appcues/trait/appcues/TooltipTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/TooltipsPaths.kt
appcues/src/main/java/com/appcues/trait/extensions/TargetRectangleInfoExt.kt

Added Left and Right as preferredContentPosition supported for tooltips,
then added piece of calculation rules to determine where we should position the tooltip, and this is mirroring behavior described for IOS and WEB tooltip.
* Another pass on tooltip sizing related to task [#48999](https://app.shortcut.com/appcues/story/48999/android-update-tooltip-to-fit-in-visible-area)
* [This is](https://github.com/appcues/appcues-android-sdk/blob/2de61c114632faec66f4e9fa0da8e33d0e59f102/appcues/src/main/java/com/appcues/trait/extensions/TargetRectangleInfoExt.kt#L55) the method that should mirror IOS/WEB rules for tooltip positioning
* UI tests running OK

✨ Enable horizontal positioning for tooltip container

---

appcues/src/main/java/com/appcues/ui/extensions/TextPrimitiveExt.kt

Simple oversight we had when we moved from `text` to `spans` for rendering text primitive content. When we apply the error tint color, we can no longer apply to the root `style`, but rather need to apply to each individual span within, to the span `style`. Prior to this fix, the label text was just remaining in the same style - unchanged by the error tint.
| validation error | normal state |
| ---- | ----|
| ![Screenshot 2023-03-29 at 12 57 53 PM](https://user-images.githubusercontent.com/19266448/228627807-45112119-b1a6-4c5d-9db5-40fb9b7595eb.png) | ![Screenshot 2023-03-29 at 12 57 46 PM](https://user-images.githubusercontent.com/19266448/228627815-75a99cec-7fe5-440c-b46f-67e28e11af7d.png) |

Apply error tint color to text spans when indicating required field validation errors

---

appcues/src/main/java/com/appcues/debugger/ui/CaptureConfirmDialog.kt
appcues/src/main/java/com/appcues/trait/appcues/SkippableTrait.kt
appcues/src/main/java/com/appcues/ui/extensions/DrawScopeEx.kt

This PR stacks on #367 and adds the new styling support in the `SkippableTrait`. 
I would suggest not really looking at the diff here and really just looking at `SkippableTrait` as a new "2.0" implementation of the close button, since it now has a much different capability set. Almost all the changes are in there, other than the one related change to `X` path drawing in `DrawScopeExt` (and updated usage in one other spot in `CaptureConfirmDialog`).
There were a lot of little details covered here, but in summary - it handles all of the spec updates defined in https://github.com/appcues/appcues-mobile-experience-spec/pull/165 for styling options in `buttonStyle` on the `@appcues/skippable` trait. 
I restructured the code a bit to pull out the distinct differences in how `default` and …

Add support for close button styling

---

appcues/src/debug/java/com/appcues/CompositionTestHelper.kt
appcues/src/main/java/com/appcues/ui/composables/AppcuesComposition.kt
appcues/src/main/java/com/appcues/ui/composables/CompositionLocals.kt

The `CompositionTestHelper.ComposeContainer` is a debug only public helper that allows our snapshot test tools (different project) to send in experience and trait JSON data and render a step for snapshot purposes. It is similar in concept to how the existing `ComposeContent` works for primitives, but supports a more advanced case with the full experience and trait decoding and mapping. The given trait is injected into the specified step, for testing. This allows our test cases to have some base experience JSON and then add variations of traits as needed. (test updates will be in another PR in that repo)
The change in `AppcuesComposition` is just a refactor to make the render of a step container a testable piece with limited  dependencies, and internal visibility, in support of this new …

Refactor step container render into a testable function for snapshot testing

---

appcues/src/main/java/com/appcues/trait/appcues/TooltipTrait.kt

I was hacking around on some testing items and came across what seems to be the relatively simple fix for the crash seen when applying a border to a tooltip trait style. It simply needs to guard against an empty path during some layout passes. 
I'm guessing there is a first pass composition running before the tooltip size is first set and the `containerDimens` are fully known. In the `tooltipPath` helper, if no `containerDimens` are set yet, it does not draw any path. Later, if using this empty path when drawing a border, a crash is observed:
```
java.lang.IllegalArgumentException: width and height must be > 0
at android.graphics.Bitmap.createBitmap(Bitmap.java:1095)
at androidx.compose.ui.graphics.Api26Bitmap.createBitmap-x__-hDU$ui_graphics_release(AndroidImageBitmap.android.kt:198)
at …
```

Fix crash when applying border to tooltip

---

appcues/src/main/java/com/appcues/trait/appcues/TooltipPath.kt
appcues/src/main/java/com/appcues/trait/appcues/TooltipPathExt.kt
appcues/src/main/java/com/appcues/trait/appcues/TooltipTrait.kt
appcues/src/main/java/com/appcues/util/FloatExt.kt

adding cornerRadius to the previous tooltip structure required some changes and a lot of testing. part of the effort here was to keep it organized so we can come back to it later if needed.
TooltipPath now contains all the Path related methods, auxiliary classes and methods were moved to TooltipPathExt for lack of a better name. with this change we are supporting cornerRadius on tooltips including some animations, but there are still some remaining work to safe guard odd scenarios (I will create a separate ticket for this one after)
https://user-images.githubusercontent.com/5244805/231225409-9165106c-a2d0-4343-87e7-2bccd21982f6.mov
tagging @mmaatttt here since he helped quite a lot with the trigonometry involved, + I know he wanted to know how this will be merged on android to compare …

✨ Added property pointerCornerRadius for tooltip trait

---

release.sh

Matching what was done on iOS here https://github.com/appcues/appcues-ios-sdk/pull/387/commits

Don’t deploy SDK docs for pre-release versions

---

appcues/src/main/java/com/appcues/data/MoshiConfiguration.kt

If something inside of a trait `config` block was malformed, things would silently fail due to a Moshi error which ends up causing the trait to fail to instantiate when Koin tried to inflate it. This would not render anything at all, nor give a step error.
Now, it will gracefully handle decoding errors and return null to the caller, which has the option of whether to continue with default config values or do any other sort of error handling desired.

Handle errors in decoding trait configs

---

appcues/src/main/java/com/appcues/trait/appcues/TooltipPathExt.kt
appcues/src/main/java/com/appcues/trait/appcues/TooltipTrait.kt
appcues/src/main/java/com/appcues/trait/extensions/TargetRectangleInfoExt.kt

the way the tooltip is built at the moment sometimes gives us unexpected results, where the pointer is in the wrong position and/or the content is not visible.
Some adjustments to align positioning logic between android and ios.
* TargetRectangleInfo?.getTooltipPointerPosition(..) we added distance as one parameter that can influence available space, and changed the containerDimens with contentDimens.
* Added contentDimens that is calculated based on existing containerDimens and known tooltip position.
* Fixed tooltipSize to mirror rules from IOS
* general improvement on how the composition is organized (fixing some of the detekt warnings)

♻️ Adjusting tooltip composition to fix pointer positioning

---

appcues/src/main/java/com/appcues/trait/appcues/TooltipTrait.kt

small improvement to include pointer length when defining the min height for the tooltip container

🐛 improving min height constraints to include pointer length

---

appcues/src/main/java/com/appcues/trait/appcues/TooltipPath.kt
appcues/src/main/java/com/appcues/trait/appcues/TooltipPathExt.kt
appcues/src/main/java/com/appcues/trait/appcues/TooltipTrait.kt

safeguarding pointer base values based on content available space to position the pointer.
also as part of this task, after calculating how much space the pointer base will take, we compare with the available space to figure out if we should round the base corners of the pointer. (matching IOS behavior)

♻️  limit pointer width based on tooltip contraints

---

appcues/src/main/java/com/appcues/trait/appcues/TooltipPathExt.kt
appcues/src/main/java/com/appcues/trait/appcues/TooltipTrait.kt
appcues/src/main/java/com/appcues/trait/extensions/TargetRectangleInfoExt.kt

These updates are to ensure that the desired target width gets satisfied and the start padding is not too large, in some horizontal tooltip cases. It was observed in tests that content positioned to left (pointing to right) could sometimes be compressed in width by the pointer length, leading to a narrow than expected tooltip.

Account for the pointer length in the horizontal tooltip padding start calculation

---

appcues/src/main/java/com/appcues/trait/appcues/TooltipTrait.kt

Tests revealed that previous version would result in too much top padding, pushing the tooltip lower on the screen than it should be.

Property account for the pointer height in the padding top calculation

---

appcues/src/main/java/com/appcues/trait/appcues/TooltipTrait.kt
gradle/tools/detekt/detekt-config.yml

did some small change related to the padding modifier, in order to keep the value of the animated padding values even when contentDimens is not available.

🐛 fixing animated values related to positioning the tooltip

---

appcues/src/main/java/com/appcues/trait/appcues/TooltipPathExt.kt

This fixes the issue where the pointerBase max was causing the pointer alignment to be incorrect in some cases. Validated with snapshot tests coming. Turned out to just be a simple off by one case in calculating the pointer x/y offsets.
| After | Before |
| --- | --- |
| ![com appcues host TooltipTraitTests_testPointerBaseGreaterThanContentTop](https://user-images.githubusercontent.com/19266448/233709244-067bfaee-a1e6-4233-8302-75cec3e07ac7.png) | ![com appcues host TooltipTraitTests_testPointerBaseGreaterThanContentTop](https://user-images.githubusercontent.com/19266448/233709181-4a88e536-9a3a-4a80-90a4-c5c6f3f83643.png) |

Fix handling of pointerBase larger than available space

---

appcues/src/main/java/com/appcues/trait/appcues/TooltipPath.kt

added an extra logic around rounding or not the corners of the pointer to factor in the pointer alignment and NOT round it in some special cases
| Before      | After |
| ----------- | ----------- |
| <img width="299" alt="image" src="https://user-images.githubusercontent.com/5244805/233728207-cea2b6b1-715a-40d7-a621-da2bf6476afc.png">      | <img width="357" alt="image" src="https://user-images.githubusercontent.com/5244805/233727988-f74c8052-6690-4046-9512-b84a011e9747.png"> |

🐛 fixing shadow for rounded corner on container edge

---

appcues/src/main/java/com/appcues/action/ActionKoin.kt
appcues/src/main/java/com/appcues/action/ActionProcessor.kt
appcues/src/main/java/com/appcues/action/ExperienceAction.kt
appcues/src/main/java/com/appcues/action/appcues/CloseAction.kt
appcues/src/main/java/com/appcues/action/appcues/ContinueAction.kt
appcues/src/main/java/com/appcues/action/appcues/LaunchExperienceAction.kt
appcues/src/main/java/com/appcues/action/appcues/LinkAction.kt
appcues/src/main/java/com/appcues/action/appcues/RequestReviewAction.kt
appcues/src/main/java/com/appcues/action/appcues/StepInteractionAction.kt
appcues/src/main/java/com/appcues/action/appcues/SubmitFormAction.kt
appcues/src/main/java/com/appcues/action/appcues/TrackEventAction.kt
appcues/src/main/java/com/appcues/action/appcues/UpdateProfileAction.kt
appcues/src/main/java/com/appcues/data/mapper/experience/ExperienceMapper.kt
appcues/src/test/java/com/appcues/action/ActionProcessorTest.kt
appcues/src/test/java/com/appcues/action/appcues/CloseActionTest.kt
appcues/src/test/java/com/appcues/action/appcues/ContinueActionTest.kt
appcues/src/test/java/com/appcues/action/appcues/LaunchExperienceActionTest.kt
appcues/src/test/java/com/appcues/action/appcues/LinkActionTest.kt
appcues/src/test/java/com/appcues/action/appcues/SubmitFormActionTest.kt
appcues/src/test/java/com/appcues/action/appcues/TrackEventActionTest.kt
appcues/src/test/java/com/appcues/action/appcues/UpdateProfileActionTest.kt
appcues/src/test/java/com/appcues/mocks/ExperienceMocks.kt
docs/VersionMigration.md

At the moment Appcues instance is not required on ExperienceAction.execute call, when necessary we can let it be declared as a constructor of the implementing class.
This changes removes appcues from the execute method

💥  Removed Appcues param from action.execute method

---

appcues/src/main/java/com/appcues/analytics/ExperienceLifecycleEvent.kt
appcues/src/main/java/com/appcues/data/mapper/action/ActionsMapper.kt
appcues/src/main/java/com/appcues/data/model/AppcuesConfigMapExt.kt
appcues/src/main/java/com/appcues/trait/TraitKoin.kt
appcues/src/main/java/com/appcues/trait/TraitRegistry.kt
appcues/src/main/java/com/appcues/trait/appcues/TargetInteractionTrait.kt
appcues/src/main/java/com/appcues/ui/extensions/ModifierExt.kt

This adds an implementation of @appcues/target-interaction (https://github.com/appcues/appcues-mobile-experience-spec/pull/175). This trait can be used to create a transparent View that lays over the target rectangle, from metadata, to captures taps and long presses. 
Additionally this trait can also provide with a list of actions that should be executed when those actions occur.
```json
{
"type": "@appcues/target-interaction",
"config": {
"actions": [
{
"on": "tap",
"type": "@appcues/continue",
"config": {
"offset": 1
}
}
]
}
}
```

✨ Added target-interaction trait

---

appcues/src/main/java/com/appcues/trait/appcues/BackdropKeyholeTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/TargetInteractionTrait.kt
appcues/src/main/java/com/appcues/trait/extensions/RectExt.kt

This changes introduces new metadataSettings property that holds all keyhole configs so it can be consulted by other traits like `@appcues/target-interaction`.
with this target-interaction will support RECT/CIRCLE, cornerRadius and spreadRadius

♻️  change target-interaction to use all of keyhole configs

---

docs/Identifying.md

Requested naming update to align with the feature name throughout Appcues documentation.

Use identity verification instead of sender validation for feature name in docs

---

appcues/src/main/java/com/appcues/ElementTargetingStrategy.kt

This function could be used in the future by custom element targeting strategies.

Revert public visibility on the View.isAppcuesView() extension

---

appcues/src/main/java/com/appcues/debugger/screencapture/AndroidTargetingStrategy.kt

A pretty simple update in our selector structure, this adds `resourceName`, using the resource ID string representation from how the view was defined in XML layouts, as a property you can use for target element selection.
This approach would only add that property if the `View.isClickable` was `true` - for commonly interactive elements like buttons, tabs, menus. It would avoid a lot of the extra noise in the screenshot for container elements or internal system views, but still make a lot of common tooltip targets selectable "for free".  I'm wondering if there is a better filter to use here than `isClickable` still?

Add support for XML resource ID based selectors

---

appcues/src/main/java/com/appcues/ElementTargetingStrategy.kt
appcues/src/main/java/com/appcues/debugger/screencapture/AndroidTargetingStrategy.kt

This approach uses a custom Modifier to set a SemanticsProperty. We can then traverse the [Semantics tree](https://developer.android.com/jetpack/compose/semantics), very similar to how Compose UI testing works, to gather up layout info an selectors for views defined in compose. This is a low-code solution approach for element targeting with Jetpack Compose views.
The one complexity this brings is the usage of Reflection to extract the `AndroidComposeView` (host view container) instance and the `semanticsOwner` field within. Compose makes `SemanticsOwner` and `SemanticsNode` classes public, but does not provide any way to get access to them or instantiate them (internal constructors). So this appears to be the only mechanism at this point. This code is wrapped in exception handling to …

Add an element targeting approach for Composables

---

appcues/src/main/java/com/appcues/ui/AppcuesOverlayViewManager.kt

Sets underlaying views to be ignored by talkback while experiences are showing.
by changing the importantForAccessibility flag on specific view, we ensure talkback will ignore it while we have our overlayed view on screen

🐛 removing customer view from talkback stack when experiences are showing

---

appcues/src/main/java/com/appcues/ui/theme/AppcuesTheme.kt

quick fix that resumes the function to preview content blocks inside Android Studio

🐛 Fix compose preview

---

appcues/src/main/java/com/appcues/debugger/DebuggerViewModel.kt
appcues/src/main/java/com/appcues/debugger/screencapture/ScreenCaptureProcessor.kt
appcues/src/main/java/com/appcues/debugger/ui/DebuggerComposition.kt

Looking for suggestion on how we could dismiss the current experience, at this moment we are hiding the appcues_overlay_view, which produces the same end result
this screenshot was taken after opening an experience and clicking on the capture FAB

♻️  update screen capture name

---

appcues/src/main/java/com/appcues/analytics/AutoPropertyDecorator.kt
appcues/src/test/java/com/appcues/analytics/AutoPropertyDecoratorTest.kt
docs/Identifying.md

matching the last change coming from a bug found when a customer wanted to export information in studio, IOS has this [PR](https://github.com/appcues/appcues-ios-sdk/pull/414). 
I think this is matching the new behavior, the unit test is also there showing its working.

🐛 Add all identify properties to all session events

---

appcues/src/main/java/com/appcues/debugger/screencapture/AndroidTargetingStrategy.kt

While testing the new sdk features with [this PR](https://github.com/appcues/mobile-experiments/pull/258) found that sometimes Role is not present, which is causing an exception and disabling basically compose element scans.
with this change if Role is not present, we use null, which is totally fine since role is just being used for displayName for now

🐛 key Role may not exist in some compositions

---

appcues/build.gradle
appcues/src/main/java/com/appcues/debugger/screencapture/AndroidTargetingStrategy.kt
appcues/src/main/java/com/appcues/debugger/screencapture/ScreenCaptureProcessor.kt
appcues/src/main/java/com/appcues/trait/appcues/TargetElementTrait.kt
appcues/src/main/java/com/appcues/ui/AppcuesOverlayViewManager.kt

This handles situations where simply taking the
```kotlin
activity.window.decorView.rootView
```
to be the root view for injecting overlay content  is not sufficient.
If a dialog view / modal is being shown in the customer application, this will cause another window and decorView to show up in the view hierarchy. We need to actually get all of the top level windows in the Activity and find the topmost item (last) and use this for screen capture, element targeting, and content overlay.
This [post](https://stackoverflow.com/a/19776489) had some helpful tips about how to get this info, which is not always straightforward. We use a multi-layer approach, where API 29+ can use a [handy WindowInspector function](https://developer.android.com/reference/android/view/inspector/WindowInspector#getGlo …

Add support for multi window scenarios in element targeting + overlay

---

README.md
docs/AnchoredTooltips.md

For [sc-53872]
Covering the general element targeting concept here, and how to instrument android views, but keeping it worded more specifically to apply to "Anchored Tooltips" to try to match the customer expectations around feature naming and what they'd be looking for information about. Open to any ideas on that though.
This general format will be applied to iOS and React Native once we're happy with it.
Thinking maybe this one should be linked to from the [Getting Started](https://github.com/appcues/appcues-android-sdk/blob/main/docs/GettingStarted.md) page.

Add doc on instrumenting views for element targeting

---

appcues/src/main/java/com/appcues/data/mapper/experience/ExperienceMapper.kt
appcues/src/main/java/com/appcues/data/model/Experience.kt
appcues/src/main/java/com/appcues/data/model/RenderContext.kt
appcues/src/test/java/com/appcues/action/appcues/SubmitFormActionTest.kt
appcues/src/test/java/com/appcues/mocks/ExperienceMocks.kt
appcues/src/test/java/com/appcues/statemachine/StateMachineTest.kt

added new property renderContext and logic around building this property.
looking for @appcues/embedded trait in experience.traits and in case one is found, get "frameID" from config map to set as the RenderContext.Embed frameId, else returning Modal as default type

✨ Added renderContext property to Experience model

---

appcues/src/main/java/com/appcues/action/ActionKoin.kt
appcues/src/main/java/com/appcues/action/appcues/CloseAction.kt
appcues/src/main/java/com/appcues/action/appcues/ContinueAction.kt
appcues/src/main/java/com/appcues/action/appcues/LaunchExperienceAction.kt
appcues/src/main/java/com/appcues/action/appcues/StepInteractionAction.kt
appcues/src/main/java/com/appcues/action/appcues/SubmitFormAction.kt
appcues/src/main/java/com/appcues/analytics/AnalyticsKoin.kt
appcues/src/main/java/com/appcues/analytics/AnalyticsPolicy.kt
appcues/src/main/java/com/appcues/data/mapper/experience/ExperienceMapper.kt
appcues/src/main/java/com/appcues/debugger/DebuggerViewModel.kt
appcues/src/main/java/com/appcues/trait/appcues/SkippableTrait.kt
appcues/src/main/java/com/appcues/ui/AppcuesViewModel.kt
appcues/src/main/java/com/appcues/ui/ExperienceRenderer.kt
appcues/src/test/java/com/appcues/action/ActionProcessorTest.kt
appcues/src/test/java/com/appcues/action/appcues/CloseActionTest.kt
appcues/src/test/java/com/appcues/action/appcues/ContinueActionTest.kt
appcues/src/test/java/com/appcues/action/appcues/LaunchExperienceActionTest.kt
appcues/src/test/java/com/appcues/action/appcues/SubmitFormActionTest.kt
appcues/src/test/java/com/appcues/ui/ExperienceRendererTest.kt

Changes included.
* Centralizing access to StateMachine by calling ExperienceRenderer
* Adding property RenderContext to ExperienceRenderer calls tied to StateMachine

♻️  ExperienceRenderer depending on RenderContext to access StateMachine

---

appcues/src/main/java/com/appcues/ElementTargetingStrategy.kt
appcues/src/main/java/com/appcues/debugger/screencapture/Capture.kt
appcues/src/main/java/com/appcues/debugger/screencapture/ScreenCaptureProcessor.kt
appcues/src/main/java/com/appcues/ui/AppcuesOverlayViewManager.kt

This is the extra extensibility point I think we'd need to support a Flutter plugin screen capture. The Flutter plugin could then provide the bitmap and sizing information needed that we cannot access directly from the normal screen capture method.

Support screenshot capture from plugins

---

appcues/src/main/java/com/appcues/AppcuesKoin.kt
appcues/src/main/java/com/appcues/SessionMonitor.kt
appcues/src/main/java/com/appcues/action/appcues/LaunchExperienceAction.kt
appcues/src/main/java/com/appcues/action/appcues/StepInteractionAction.kt
appcues/src/main/java/com/appcues/action/appcues/SubmitFormAction.kt
appcues/src/main/java/com/appcues/analytics/AnalyticsKoin.kt
appcues/src/main/java/com/appcues/analytics/AnalyticsPolicy.kt
appcues/src/main/java/com/appcues/analytics/AnalyticsTracker.kt
appcues/src/main/java/com/appcues/analytics/AnalyticsTrackerExt.kt
appcues/src/main/java/com/appcues/analytics/ExperienceLifecycleTracker.kt
appcues/src/main/java/com/appcues/statemachine/Error.kt
appcues/src/main/java/com/appcues/statemachine/StateMachine.kt
appcues/src/main/java/com/appcues/ui/AppcuesViewModel.kt
appcues/src/main/java/com/appcues/ui/ExperienceRenderer.kt
appcues/src/test/java/com/appcues/SessionMonitorTest.kt
appcues/src/test/java/com/appcues/action/ActionProcessorTest.kt
appcues/src/test/java/com/appcues/analytics/AnalyticsTrackerExtTest.kt
appcues/src/test/java/com/appcues/analytics/AnalyticsTrackerTest.kt
appcues/src/test/java/com/appcues/analytics/ExperienceLifecycleTrackerTest.kt
appcues/src/test/java/com/appcues/mocks/ExperienceMocks.kt
appcues/src/test/java/com/appcues/ui/ExperienceRendererTest.kt

A couple of changes here in order to support multiple state machines being created for each render context.
* Updated ExperienceRenderer: Added the dictionary with state machine slots, whenever a new RenderContext comes, if we dont have a state machine for it yet then we create, this will happen for any type of RenderContext, supposedly making it a generic logic that should work to any type of RenderContext now and in the future.
* Updated ExperienceLifecycleTracker: now during start it receives the state machine so it can observe states and errors. the start happens once for each state machine when its fabricated during ExperienceRenderer show method.
* Various changes to accommodate multiple state machines
Different from my last approach, we are not deleting any renderContext and its …

♻️  Support Multiple state machines tied to each RenderContext

---

appcues/src/main/java/com/appcues/trait/appcues/TargetInteractionTrait.kt

This is used in Koin here https://github.com/appcues/appcues-android-sdk/blob/main/appcues/src/main/java/com/appcues/trait/TraitKoin.kt#L33 and the `params.get()` for the second param is for the `renderContext`.
I'll work on getting a UI test for this trait as well to avoid future issues.

Fix the parameter order on TargetInteractionTrait init to match Koin expectation

---

.circleci/config.yml
appcues/build.gradle
appcues/codecov.gradle
appcues/publish-maven.gradle
appcues/src/main/AndroidManifest.xml
appcues/src/main/java/com/appcues/action/ActionKoin.kt
appcues/src/main/java/com/appcues/action/appcues/StepInteractionAction.kt
appcues/src/main/java/com/appcues/trait/TraitKoin.kt
appcues/src/main/java/com/appcues/trait/appcues/CarouselTrait.kt
appcues/src/main/java/com/appcues/ui/utils/ActivityExt.kt
appcues/src/test/java/com/appcues/action/ActionProcessorTest.kt
appcues/src/test/java/com/appcues/data/AppcuesRepositoryTest.kt
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
samples/kotlin-android-app/build.gradle
samples/kotlin-android-app/src/main/AndroidManifest.xml

Updates related to the latest Android Studio Flamingo default versions, getting into compatibility with other tools releasing similar updates. A lot of these are cascading updates from the Gradle 8 change really, for example the Kotlin version which then requires a Compose Compiler / Compose update.
* Android Gradle Plugin 7.2.2 -> 8.0.2
* JDK 11 -> 17
* Kotlin 1.7.20 - 1.8.21
* Compose 1.3.0 -> 1.4.3
* Compose Compiler 1.3.2 -> 1.4.7
* Accompanist 0.27.0 -> 0.30.1
As part of Compose 1.4.3 - now using the official Pager for our carousel and removed the usage of the Accompanist Pager.
Ended up also needing to explicitly declare OkHttp 4.11.0 as a dependency to[ resolve a minification issue with the 4.10.0 version](https://github.com/square/okhttp/issues/7777) that was previously being …

Update to Gradle 8 and other related updates

---

appcues/src/main/java/com/appcues/debugger/screencapture/AndroidTargetingStrategy.kt
appcues/src/test/java/com/appcues/debugger/screencapture/ElementSelectorTest.kt

Some customer data showed selectors with `""` values - we should ignore these and not create selectors that will not provide any unique value. Matching iOS change in https://github.com/appcues/appcues-ios-sdk/pull/431 and react native in https://github.com/appcues/appcues-react-native-module/pull/99

Ensure no empty strings are present in selector property values

---

appcues/src/main/java/com/appcues/Appcues.kt
appcues/src/main/java/com/appcues/AppcuesViews.kt
appcues/src/main/java/com/appcues/RenderContextManager.kt
appcues/src/main/java/com/appcues/ui/presentation/EmbedViewPresenter.kt
appcues/src/main/java/com/appcues/ui/presentation/OverlayViewPresenter.kt
appcues/src/main/java/com/appcues/ui/presentation/ViewPresenter.kt
samples/kotlin-android-app/src/main/res/layout/fragment_embed.xml

An additional PR to the original embed trait PR.
this one is aiming to replace the generic ViewGroup with a specific AppcuesFrameView, the reasoning behind it is to limit customer options here, not letting them adding ANY type of ViewGroup, in addition this is extending from AbstractComposeView, with similar implementation as ComposeView, which should be perfect for our use case.
deriving two classes, one internal and the other (AppcuesFrameView) public for use during appcues.registerEmbed("frame", appcuesFrameView)

✨ Added AppcuesFrameView to replace generic ViewGroup

---

appcues/src/main/java/com/appcues/Appcues.kt
appcues/src/main/java/com/appcues/AppcuesKoin.kt
appcues/src/main/java/com/appcues/RenderContextManager.kt
appcues/src/main/java/com/appcues/analytics/AnalyticsEvent.kt
appcues/src/main/java/com/appcues/analytics/AnalyticsTrackerExt.kt
appcues/src/main/java/com/appcues/analytics/ExperienceLifecycleTracker.kt
appcues/src/main/java/com/appcues/data/model/Experience.kt
appcues/src/main/java/com/appcues/ui/ExperienceRenderer.kt
appcues/src/test/java/com/appcues/action/ActionProcessorTest.kt
appcues/src/test/java/com/appcues/analytics/ExperienceLifecycleTrackerTest.kt
appcues/src/test/java/com/appcues/ui/ExperienceRendererTest.kt

the goal here is to cover some of the edge cases for embeds when its registered an re-registered.
the initial scenario I was going for is to have proxy experiences to show on Embeds tab, and then interacting with those and changing between tabs should be able to work well.
for next step I will be looking into RecyclerViews

♻️  ExperienceRenderer changes around how embeds are displayed

---

appcues/consumer-rules.pro

Workaround for issue with release minification https://github.com/square/retrofit/issues/3751#issuecomment-1192043644

Add Retrofit Proguard rules to avoid issue with AGP8 and R8 full mode

---

appcues/src/main/java/com/appcues/RenderContextManager.kt

adding clearComposition here ensures that whenever we register a new frame, that the new and the old frame are cleared of any Compositions

🐛 Fix a bug where recycled item would render experience without owning it

---

appcues/src/main/java/com/appcues/trait/AppcuesTraitException.kt
appcues/src/main/java/com/appcues/trait/appcues/TargetElementTrait.kt
appcues/src/main/java/com/appcues/ui/AppcuesOverlayViewManager.kt
appcues/src/main/java/com/appcues/ui/AppcuesViewModel.kt
appcues/src/main/java/com/appcues/ui/composables/AppcuesComposition.kt
appcues/src/main/java/com/appcues/ui/composables/CompositionLocals.kt

There were a few complex bits to this, which I'll do my best to explain. The overall idea is this:
1. If a target-element is not found, it should allow some retry - by default after 300, 900, 1800, and 3000ms. If it still is not found after 3s, it will report a StepError and abort the flow (as before)
2. If the element is found, it will continue on and trigger the ExperienceStarted and StepSeen as appropriate
3. If the Activity is removed out from under us (deep link or user navigation) - it will report a new type of StepError `"Activity changed during render of step $index" - and abort the flow (free up the state machine)
To support this, the `@appcues/target-element` trait has an optional array of Ints (milliseconds) for `retryIntervals` that define the retry timeline (defaults as noted …

Add retry capability for target element matching

---

appcues/src/main/java/com/appcues/Appcues.kt
appcues/src/main/java/com/appcues/AppcuesConfig.kt
appcues/src/main/java/com/appcues/SessionMonitor.kt
appcues/src/main/java/com/appcues/analytics/AnalyticsEvent.kt
appcues/src/main/java/com/appcues/analytics/AnalyticsTracker.kt
appcues/src/main/java/com/appcues/data/remote/DataRemoteKoin.kt
appcues/src/main/java/com/appcues/data/remote/appcues/AppcuesRemoteSource.kt
appcues/src/main/java/com/appcues/debugger/AppcuesDebuggerManager.kt
appcues/src/main/java/com/appcues/debugger/DebuggerRecentEventsManager.kt
appcues/src/main/java/com/appcues/debugger/DebuggerStatusManager.kt
appcues/src/main/java/com/appcues/debugger/DebuggerViewModel.kt
appcues/src/main/java/com/appcues/debugger/ui/DebuggerExt.kt
appcues/src/main/java/com/appcues/ui/ExperienceRenderer.kt
appcues/src/test/java/com/appcues/AppcuesTest.kt
appcues/src/test/java/com/appcues/SessionMonitorTest.kt
appcues/src/test/java/com/appcues/analytics/AnalyticsTrackerExtTest.kt
appcues/src/test/java/com/appcues/analytics/AnalyticsTrackerTest.kt
appcues/src/test/java/com/appcues/data/remote/retrofit/RetrofitAppcuesRemoteSourceTest.kt

At a high level: remove session events for suspend/resume/reset - only track `session_start`. Update the timeout default to 300 sec (was 1800), and check for timeout after any period of analytics inactivity, regardless of app background/foreground. No longer track background/foreground at all effectively.
`AnalyticsTracker` now completely owns the session management. On any attempt to track any analytics, it will (A) check if any session exists and (B) check if that session is expired. In either case, it will try to restart a new session. This can fail if there is no user identified. Session starts are thus completely based on some initial analytic being tracked (commonly the user identify at start), and the session duration depends on continued tracking with no period of inactivity …

Update session tracking

---

samples/kotlin-android-app/src/main/java/com/appcues/samples/kotlin/main/EmbedFragment.kt
samples/kotlin-android-app/src/main/java/com/appcues/samples/kotlin/main/MainActivity.kt

`Embed Harness` --> `Embed Container` 
Making this match with [iOS](https://github.com/appcues/appcues-ios-sdk/blob/main/Examples/DeveloperCocoapodsExample/CocoapodsExample/EmbedViewController.swift#L30) to avoid any test confusion
also using `/embed` instead of `/embeds` for the deep link route, for same reason

Update example app embed screen tracking name

---

samples/kotlin-android-app/src/main/java/com/appcues/samples/kotlin/main/EventsFragment.kt
samples/kotlin-android-app/src/main/res/layout/fragment_events.xml
samples/kotlin-android-app/src/main/res/values/strings.xml

Matching update to iOS proposal here https://github.com/appcues/appcues-ios-sdk/pull/444
Updates sample app to support testing delay loaded elements with element targeted patterns, using a third button on the events page that becomes visible 2 seconds after initial load.
https://github.com/appcues/appcues-android-sdk/assets/19266448/8ccdf3c1-758c-400a-aec5-13cb528cd210

Add delay loaded button to test element targeting retry

---

appcues/src/main/java/com/appcues/DeepLinkHandler.kt
appcues/src/main/java/com/appcues/data/AppcuesRepository.kt
appcues/src/main/java/com/appcues/data/model/RenderContext.kt
appcues/src/main/java/com/appcues/ui/ExperienceRenderer.kt
appcues/src/main/res/values/strings.xml
appcues/src/test/java/com/appcues/data/AppcuesRepositoryTest.kt
appcues/src/test/java/com/appcues/ui/ExperienceRendererTest.kt
samples/kotlin-android-app/build.gradle

Preview logic for embeds.
storing embeds preview in a different dictionary that is no cleared on new screen event calls. also ensuring it is always using a prestine state machine or else we could get into some scenarios where the state machine doesnt have a view and its not dismissing the existing experience before showing the new previewd one.

✨ Preview for embeds

---

samples/kotlin-android-app/src/main/java/com/appcues/samples/kotlin/main/EventsFragment.kt

This is a fix up related to the recent example app change in https://github.com/appcues/appcues-android-sdk/pull/462
I noticed that if you navigate away from the Events tab before the 2 second timer is up, the View may have been destroyed, and the view binding null - which could then lead to a null reference in the coroutine where it is trying to delay show the view.

Avoid crash in example app for delayed button visibility

---

appcues/src/main/java/com/appcues/AppcuesFrame.kt
appcues/src/main/java/com/appcues/ui/composables/AppcuesComposition.kt

Small fix around sizing of AppcuesComposition, specifically targeting embeds

🐛 Removing FillMaxSize from consumeAllTouch

---

.circleci/config.yml

Our [reporting](https://app.codecov.io/gh/appcues/appcues-android-sdk) hasn't updated in a month or so (nor has iOS). I'm not sure why, but trying the updated orb as a start.

Update to latest codecov orb for uploading test coverage

---

.circleci/config.yml

Using a project specific variable to not conflict with the one defined in the org context.

Update the Codecov token variable to match CircleCI

---

appcues/src/main/java/com/appcues/analytics/AnalyticsQueueProcessor.kt
appcues/src/main/java/com/appcues/data/AppcuesRepository.kt
appcues/src/main/java/com/appcues/data/model/QualificationResult.kt
appcues/src/main/java/com/appcues/ui/ExperienceRenderer.kt
appcues/src/test/java/com/appcues/analytics/AnalyticsQueueProcessorTest.kt
appcues/src/test/java/com/appcues/data/AppcuesRepositoryTest.kt
appcues/src/test/java/com/appcues/mocks/ExperienceMocks.kt
appcues/src/test/java/com/appcues/ui/ExperienceRendererTest.kt

...not just those with qualified experiences
The lower level code now returns a `QualificationResult`, instead of just `List<Experiences>`. This result can have an empty list of experiences, but will always communicate the qualification reason from the most recent response - so that the `ExperienceRenderer` can use that to determine cache behavior. This reason is passed in on all responses now, not just those with non-zero qualified experiences. The passed in value is used rather than relying on the value from the first qualified experience (which may not always exist).
This is adding the same handling as noted in the iOS [todo](https://github.com/appcues/appcues-ios-sdk/pull/416#discussion_r1232330446) here, and then in the update …

Ensure that all screen view responses clear the embed cache

---

appcues/src/debug/java/com/appcues/CompositionTestHelper.kt
appcues/src/main/java/com/appcues/ui/presentation/EmbedViewPresenter.kt
appcues/src/main/java/com/appcues/ui/presentation/OverlayViewPresenter.kt
appcues/src/main/java/com/appcues/ui/presentation/ViewPresenter.kt

small change to pass in the correct Context so that Shot tests can capture screen properly

🐛 Passing activity context instead of Generic context

---

appcues/src/main/java/com/appcues/ui/composables/AppcuesComposition.kt
appcues/src/main/java/com/appcues/ui/composables/CompositionLocals.kt
appcues/src/main/java/com/appcues/ui/presentation/AppcuesViewModel.kt
appcues/src/main/java/com/appcues/ui/presentation/ViewPresenter.kt
appcues/src/main/java/com/appcues/ui/theme/AppcuesTheme.kt

This change moves the handling of shake/refresh to the `ViewPresenter` - removing/simplifying the previous usage in the `AppcuesViewModel` and `AppcuesComposition`. This also fixes the shake to refresh issue seen previously.

Handle preview refresh in the view presenter

---

appcues/src/debug/java/com/appcues/CompositionTestHelper.kt
appcues/src/main/java/com/appcues/Appcues.kt
appcues/src/main/java/com/appcues/statemachine/BeginningStepExt.kt
appcues/src/main/java/com/appcues/statemachine/SideEffect.kt
appcues/src/main/java/com/appcues/statemachine/State.kt
appcues/src/main/java/com/appcues/statemachine/StateMachine.kt
appcues/src/main/java/com/appcues/statemachine/Transitions.kt
appcues/src/main/java/com/appcues/trait/PresentingTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/EmbedTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/ModalTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/TooltipTrait.kt
appcues/src/main/java/com/appcues/ui/ExperienceRenderer.kt
appcues/src/main/java/com/appcues/ui/StateMachineDirectory.kt
appcues/src/main/java/com/appcues/ui/composables/AppcuesComposition.kt
appcues/src/main/java/com/appcues/ui/composables/CompositionLocals.kt
appcues/src/main/java/com/appcues/ui/presentation/AppcuesViewModel.kt
appcues/src/main/java/com/appcues/ui/presentation/EmbedViewPresenter.kt
appcues/src/main/java/com/appcues/ui/presentation/OverlayViewPresenter.kt
appcues/src/main/java/com/appcues/ui/presentation/ViewPresenter.kt
appcues/src/test/java/com/appcues/analytics/ExperienceLifecycleTrackerTest.kt
appcues/src/test/java/com/appcues/statemachine/StateMachineTest.kt
appcues/src/test/java/com/appcues/ui/ExperienceRendererTest.kt

These are the changes from a deeper review of state machine handling, in particular related to recent embeds work.
* Remove await on presentation callbacks to avoid issues with hung state machine, no longer needed
* Process trait metadata before presenting new container or moving to new steps in container, and handle errors prior to render
* Add remove() to PresentingTraits to ensure that UI can be dismissed in trait metadata error cases
* Simplify StateMachineOwning implementation (for embeds) to remove optionals and handle edge cases

State machine updates/simplifications to handle rendering issues

---

appcues/src/main/java/com/appcues/ui/primitive/EmbedHtmlPrimitive.kt

Pulling [this one detail](https://github.com/appcues/appcues-android-sdk/pull/477/files#r1316171902) out of the larger set of changes in the dependency update PR, as this is a simple fix to the currently broken behavior in the 3.x release packages.

Fix expand and collapse video embed behavior

---

appcues/src/main/java/com/appcues/trait/appcues/TooltipPathExt.kt
appcues/src/main/java/com/appcues/trait/appcues/TooltipTrait.kt

comparing width and height (as Int) to make sure we are not updating size on every decimal size update.
unsure the root cause of the issue, its probably because we may have an unintentional loop in this composition, where we need the containerSize and contentSize to build the tooltipSettings, and tooltipSettings needs to know the content size too.
maybe worth revisiting this later to see if we can simplify how we build tooltips, but for now I think we can limit the update on containerSize to only update when its a relevant value

🐛 guarding onSizeChange to only apply when size is not the same as old size

---

appcues/src/main/java/com/appcues/trait/AppcuesContentAnimatedVisibility.kt
appcues/src/main/java/com/appcues/trait/appcues/ModalTrait.kt
appcues/src/main/java/com/appcues/ui/modal/DialogModal.kt
appcues/src/main/java/com/appcues/ui/modal/SharedModal.kt

This PR adds support for the slideout display style in our dialog modal. The key aspects of this are
* Can have a specific width specified, not always full width
* Can be positioned in any horizontal or vertical alignment combination
* Can include a slide in from edge transition animation (and matching exit)
There were some structural changes in `DialogModal` to support this, and I'll try to call those out specifically. But there should not be any visual difference in a standard dialog modal using the existing "dialog" style and the default fade transition. Will confirm this with UI tests as well.
https://github.com/appcues/appcues-android-sdk/assets/19266448/12af2426-f45c-44bf-90a2-c8c8b102eb71

Add slideout transition handling to dialog modal

---

.circleci/config.yml
codecov.yml
fastlane/Fastfile

This is on top of #486 and pairs with the snapshot test project update in https://github.com/appcues/appcues-mobile-experience-spec/pull/218
This changes our CI configuration for the Android SDK to closely mirror how iOS is working now. PR validation runs (and merges to main) will now
1. trigger a test run on the same branch (or main if no matching branch) in the spec repo - running unit tests from this SDK project along with snapshot tests against the updated SDK branch
2. generate coverage report along with pass/fail and report back to the triggering pipeline here
3. continue this pipeline and get the result as well as upload the combined codecov report from unit tests + snapshot tests
The majority of this was copy/pasted from iOS exactly, which made it quite easy to get working and …

Integrate snapshot tests into CI and coverage

---

appcues/src/test/java/com/appcues/AppcuesTest.kt
appcues/src/test/java/com/appcues/data/mapper/step/StepMapperTest.kt

Recent test CI worked revealed a few small warnings in the unit test build. These updates will resolve those.
```
> Task :*******:*******:compileDebugUnitTestKotlin
w: file:///home/circleci/project/*******-android-sdk/*******/src/test/java/com/*******/AppcuesTest.kt:52:13 Variable 'sessionMonitor' is never used
w: file:///home/circleci/project/*******-android-sdk/*******/src/test/java/com/*******/AppcuesTest.kt:67:13 Variable 'sessionMonitor' is never used
w: file:///home/circleci/project/*******-android-sdk/*******/src/test/java/com/*******/AppcuesTest.kt:208:13 Variable 'sessionMonitor' is never used
w: file:///home/circleci/project/*******-android-sdk/*******/src/test/java/com/*******/data/mapper/step/StepMapperTest.kt:137:37 There is more than one label with such a name in this scope …
```

Fix unit test warnings

---

appcues/src/main/java/com/appcues/analytics/AnalyticsTrackerExt.kt
appcues/src/main/java/com/appcues/statemachine/Error.kt
appcues/src/main/java/com/appcues/ui/ExperienceRenderer.kt

Discovered this bug while testing some other analytics changes in 3.1. We had an issue with how we were reporting experience errors for the "no render context found" case, related to embeds.
1. (less severe) It was not including any of the experience properties like normal lifecycle events
2. (primary issue) it can potentially end up reporting the same error over and over each 10 sec interval as it is flushed and a new (empty) qualify response comes back
The key thing was that we were missing this guard that iOS has: https://github.com/appcues/appcues-ios-sdk/blob/e8308edbf160cd7b3b6bd2e70982a8e08f110f26/Sources/AppcuesKit/Presentation/ExperienceRendering/ExperienceStateObserver.swift#L118 -- this ensures that a recoverable error is only tracked once - when it initially gets processed and …

Fix reporting of missing render context errors

---

appcues/src/main/java/com/appcues/util/ContextResources.kt

This update will capture the primary language with the region subtag, like "en-US" rather than just "en".

Use language tag for _lastBrowserLanguage auto property

---

appcues/src/main/java/com/appcues/data/AppcuesRepository.kt
appcues/src/main/java/com/appcues/data/mapper/experience/ExperienceMapper.kt
appcues/src/main/java/com/appcues/data/mapper/trait/TraitsMapper.kt
appcues/src/main/java/com/appcues/statemachine/StateMachine.kt
appcues/src/main/java/com/appcues/trait/appcues/ModalTrait.kt

This update is meant to address two scenarios:
1. A modal trait has a presentationStyle that is unknown
2. There is no valid presenting trait in the experience
Both of these scenarios currently result in sub-optimal behavior:
1. leaves the backdrop overlay on the screen with no content, in a potentially "hung" state
2. throws an exception that is not handled until it hits the root coroutine handler, aborting the entire response processing flow
In both cases, no trackable errors are reported to the backend, and if there are other valid experiences in the response, lower in the priority list, they get skipped instead of attempted.
This change addresses these by (1) supporting traits throwing AppcuesTraitException instances during init, if config is invalid and (2) handling these exceptions …

Improved trait error handling

---

appcues/src/main/java/com/appcues/analytics/ExperienceLifecycleEvent.kt
appcues/src/main/java/com/appcues/data/mapper/experience/ExperienceMapper.kt
appcues/src/main/java/com/appcues/data/model/Experience.kt
appcues/src/main/java/com/appcues/data/remote/appcues/response/experience/ExperienceResponse.kt
appcues/src/test/java/com/appcues/action/appcues/SubmitFormActionTest.kt
appcues/src/test/java/com/appcues/analytics/ExperienceLifecycleTrackerTest.kt
appcues/src/test/java/com/appcues/data/mapper/experience/ExperienceMapperTest.kt
appcues/src/test/java/com/appcues/data/remote/retrofit/stubs/ContentModalOneStubs.kt
appcues/src/test/java/com/appcues/mocks/ExperienceMocks.kt
appcues/src/test/java/com/appcues/statemachine/StateMachineTest.kt

Quick update here to capture a `context` object in the experience response that will contain the locale id and name, in the case of localized content, when this is returned from the server in the future. This info is then returned verbatim in the experience analytics to denote which version of an experience the user saw.
Per Andy, the response property at the root of the experience will look like 
```js
"context": {
"locale_id": "the-id",
"locale_name": "the-name"
}
```
and the name and id value is "default" when no localization matched

Add locale name and id in analytics

---

appcues/src/main/java/com/appcues/debugger/AppcuesDebuggerManager.kt

Detail from testing RTL languages like Arabic - our debugger is fixed to English language and should fix itself to LTR layout regardless of the system/app settings.

Fix Debugger UI to LTR layout direction

---

appcues/src/debug/java/com/appcues/CompositionTestHelper.kt
appcues/src/main/java/com/appcues/ui/composables/CompositionRemembers.kt

Small change corresponding to the test updates in https://github.com/appcues/appcues-mobile-experience-spec/pull/221
This allows us to start the visibility flags `true` rather than starting `false` and transitioning to `true`.

Update animation handling for UI tests

---

appcues/build.gradle
appcues/src/main/java/com/appcues/debugger/ui/DebuggerPanel.kt
appcues/src/main/java/com/appcues/trait/appcues/CarouselTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/EmbedTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/TooltipTrait.kt
appcues/src/main/java/com/appcues/ui/InAppReviewActivity.kt
appcues/src/main/java/com/appcues/ui/composables/AppcuesComposition.kt
appcues/src/main/java/com/appcues/ui/composables/CompositionLocals.kt
appcues/src/main/java/com/appcues/ui/modal/BottomSheetModal.kt
appcues/src/main/java/com/appcues/ui/modal/DialogModal.kt
appcues/src/main/java/com/appcues/ui/modal/ExpandedBottomSheetModal.kt
appcues/src/main/java/com/appcues/ui/modal/FullScreenModal.kt
appcues/src/main/java/com/appcues/ui/primitive/EmbedHtmlPrimitive.kt
build.gradle
samples/kotlin-android-app/build.gradle

Taking a pass through, post 3.0 release, to update various dependencies and settings. Will need to consider the best time to push these updates out, and test with cross platform toolkits still.
* AGP 8.0.2 -> 8.1.1
* Kotlin 1.8.21 -> 1.9.10
* compileSdk and targetSdk 33 -> 34
* migrate [from kapt to ksp](https://developer.android.com/build/migrate-to-ksp)
* Room 2.4.3 -> 2.5.2 (required for Kotlin 1.9)
* Compose 1.4.3 -> 1.5.0 (compiler 1.4.7 -> 1.5.3)
* Koin 3.4.2 -> 3.5.0
* Coil 2.2.2 -> 2.4.0
* Moshi 1.14.0 -> 1.15.0
* few other misc androidx lib patch updates
removed usage of Accompanist entirely
* the Navigation lib is now rolled into compose navigation in the core
* the WebView lib is [deprecated](https://google.github.io/accompanist/web/), and replaced with a simple port into our …

Dependency updates

---

appcues/src/debug/java/com/appcues/CompositionTestHelper.kt
appcues/src/main/java/com/appcues/ui/primitive/EmbedHtmlPrimitive.kt

These are the changes in debug only test helper to support experience snapshot tests in https://github.com/appcues/appcues-mobile-experience-spec/pull/223
plus one error handling case with WebViews, since accessing WebView.settings [is not supported in Paparazzi tests](https://github.com/cashapp/paparazzi/issues/1058)

Add support for experience test snapshots

---

appcues/src/main/java/com/appcues/trait/ContentWrappingTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/EmbedTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/ModalTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/TooltipTrait.kt
appcues/src/main/java/com/appcues/ui/composables/AppcuesComposition.kt
appcues/src/main/java/com/appcues/ui/composables/StepComposition.kt
appcues/src/main/java/com/appcues/ui/modal/BottomSheetModal.kt
appcues/src/main/java/com/appcues/ui/modal/DialogModal.kt
appcues/src/main/java/com/appcues/ui/modal/ExpandedBottomSheetModal.kt
appcues/src/main/java/com/appcues/ui/modal/FullScreenModal.kt
appcues/src/main/java/com/appcues/ui/primitive/TextPrimitive.kt

three commits here for three specific fixes that came up recently
1. using `key(id) { ... }` around each step composition, to prevent node re-use causing an issue with our usage of IntrinsicSize.Min on row heights - the original issue in the linked ticket
2. fix the resizing logic on our `text` primitives to resize the span font sizes, not just the root style font size, since now all text content is actually within the spans
3. fix the vertical scroll handling for each individual step - moving the `rememberScrollState()` into the step composition, rather than the outer container composition, to restore expected behavior

three layout fixes

---

appcues/src/debug/java/com/appcues/CompositionTestHelper.kt
appcues/src/main/java/com/appcues/AppcuesConfig.kt
appcues/src/main/java/com/appcues/debugger/DebuggerFontManager.kt
appcues/src/main/java/com/appcues/debugger/DebuggerKoin.kt
appcues/src/main/java/com/appcues/ui/composables/AppcuesComposition.kt
appcues/src/main/java/com/appcues/ui/composables/CompositionLocals.kt
appcues/src/main/java/com/appcues/ui/extensions/StyleComponentExt.kt
appcues/src/main/java/com/appcues/ui/extensions/TextStyleExt.kt
appcues/src/main/java/com/appcues/ui/presentation/ViewPresenter.kt
appcues/src/main/java/com/appcues/ui/primitive/BoxPrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/ButtonPrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/HorizontalStackPrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/TextInputPrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/TextPrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/VerticalStackPrimitive.kt

This is to support custom font loading in React Native Expo projects, on Android. The new config option for `fontAssetPath` will allow specifying something other than the default (`/assets/fonts`), since Expo apps put custom fonts in the `/assets` root.
* update the Debugger list of fonts to look in both the default `/assets/fonts` and any custom path provided
* update the runtime styling for text to look for custom fonts in both the default and any custom path
The majority of the changes here are propagating a new CompositionLocal for AppcuesConfig down through the spots that eventually need it for text styling.

Add support for custom font asset path in config

---

appcues/src/main/java/com/appcues/statemachine/SideEffect.kt
appcues/src/main/java/com/appcues/statemachine/State.kt
appcues/src/main/java/com/appcues/statemachine/StateMachine.kt
appcues/src/main/java/com/appcues/statemachine/Transitions.kt
appcues/src/main/java/com/appcues/ui/composables/AppcuesComposition.kt
appcues/src/main/java/com/appcues/ui/composables/CompositionRemembers.kt
appcues/src/main/java/com/appcues/ui/presentation/AppcuesViewModel.kt
appcues/src/main/java/com/appcues/ui/presentation/ViewPresenter.kt
appcues/src/test/java/com/appcues/analytics/ExperienceLifecycleTrackerTest.kt
appcues/src/test/java/com/appcues/statemachine/StateMachineTest.kt
appcues/src/test/java/com/appcues/ui/presentation/AppcuesViewModelTest.kt

This is a followup PR to ViewModel improvements.
1. AppcuesViewModel will call Dismiss if getStateFlow is null
2. When we receive EndingStep + UiDismissed we cancel the collect job instead of running a if (uiState == Dismissing) during collect
3. calling onUiDismissed from composition (viewModel.onDismissed(onUiDismissed) to avoid checking for dismissing state, since it was already being checked by the composition.
4. ViewPresenter has viewModel as nullable var, so we can unset it whenever onCompositionDismiss
5. Removed unused `LaunchOnShowAnimationCompleted`
6. Turns out we can simplify how AwaitEffect is currently, given that we dont need to pass in AppcuesCoroutineScope (any suspend thread can call complete()) and also we can have it all inside AwaitEffect class, since we dont …

♻️  StateMachine transition improvements

---

appcues/src/debug/java/com/appcues/CompositionTestHelper.kt
appcues/src/main/java/com/appcues/AppcuesConfig.kt
appcues/src/main/java/com/appcues/debugger/DebuggerFontManager.kt
appcues/src/main/java/com/appcues/debugger/DebuggerModule.kt
appcues/src/main/java/com/appcues/ui/composables/AppcuesComposition.kt
appcues/src/main/java/com/appcues/ui/composables/CompositionLocals.kt
appcues/src/main/java/com/appcues/ui/extensions/StyleComponentExt.kt
appcues/src/main/java/com/appcues/ui/extensions/TextStyleExt.kt
appcues/src/main/java/com/appcues/ui/presentation/ViewPresenter.kt
appcues/src/main/java/com/appcues/ui/primitive/BoxPrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/ButtonPrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/HorizontalStackPrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/TextInputPrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/TextPrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/VerticalStackPrimitive.kt

This reverts the changes in https://github.com/appcues/appcues-android-sdk/pull/505 as another approach is being taken for React Native Expo now.

Revert: add support for custom font asset path in config

---

appcues/src/test/java/com/appcues/di/BootstrapTest.kt

very minor, but noticed a warning on unused item while working on test updates in https://github.com/appcues/appcues-mobile-experience-spec/pull/234

Remove unused test line

---

appcues/src/main/java/com/appcues/analytics/AutoPropertyDecorator.kt
appcues/src/main/java/com/appcues/util/ContextWrapper.kt
appcues/src/test/java/com/appcues/analytics/AutoPropertyDecoratorTest.kt

Per discussions, removing this auto property on both iOS (for performance reasons) and Android here (for consistency). It is not believed to be a useful property in mobile for most scenarios, and it can be sent as a custom property if still desired for targeting content.

Remove user agent auto-property

---

appcues/src/debug/java/com/appcues/ExperienceTestHelper.kt
appcues/src/main/java/com/appcues/AppcuesConfig.kt
appcues/src/main/java/com/appcues/data/remote/DataRemoteModule.kt
appcues/src/main/java/com/appcues/data/remote/customerapi/CustomerApiRemoteSource.kt
appcues/src/main/java/com/appcues/debugger/ui/CaptureConfirmDialog.kt
appcues/src/main/java/com/appcues/debugger/ui/DebuggerComposition.kt
appcues/src/main/java/com/appcues/debugger/ui/ToastView.kt

Some proposed updates in the SDK to support automated testing of the screen capture flow
1. a debug-only config value to supply an override to the api path used to look up the sdk config (normally fast.appcues.com path), so we can handle the screen capture flow with a MockWebServer
2. slightly change how the bitmap is shown on the confirm dialog, to work with Robolectric
3. a few `.testTag` modifiers to identify elements more easily in the debugger code

Add test support for screen capture flow

---

appcues/src/main/java/com/appcues/debugger/screencapture/Capture.kt
appcues/src/main/java/com/appcues/debugger/ui/CaptureConfirmDialog.kt
appcues/src/main/res/values/strings.xml

Completing the task to match iOS when capturing screen
when we get to the confirmation dialog we show extra information and give a link to docs where users can troubleshoot in case they are not finding what they are trying to target.
|Some selectors|No selectors|
|-|-|
|![](https://github.com/appcues/appcues-android-sdk/assets/5244805/caf69ebc-880e-402d-a22f-cd2d09691377)|![](https://github.com/appcues/appcues-android-sdk/assets/5244805/2b34f520-c3f6-4e3b-8f43-d581c47ab641)|

✨ Add Extra texts regarding captured screen and link to docs

---

appcues/src/main/java/com/appcues/ui/utils/ActivityExt.kt

This came from a customer that reported small percentage of crashes coming from appcues. 
```
java.lang.IllegalStateException: Horizontally scrollable component was measured with 
an infinity maximum width constraints, which is disallowed. One of the common reasons 
is nesting layouts like LazyRow and Row(Modifier.horizontalScroll()). If you want to add a 
header before the list of items please add a header as a separate item() before the main items() 
inside the LazyRow scope. There are could be other reasons for this to happen: your 
ComposeView was added into a LinearLayout with some weight, you applied 
Modifier.wrapContentSize(unbounded = true) or wrote a custom layout.
Please try to remove the source of infinite constraints in the hierarchy above the scrolling container.
.
.
at …
```

🐛 Fixed bug where in split-screen android build may have different decorViews not used for content rendering

---

appcues/src/main/java/com/appcues/ui/ExperienceRenderer.kt

Reviewing the iOS cleanup in https://github.com/appcues/appcues-ios-sdk/commit/92e0d64c807bc3a30e21c2c238de5b4618ff25f1 revealed that the Android side was missing cache handling for embeds the in the case of a `show(experienceId)` call (manually show, deep link, or launch from another flow)

Ensure manually shown embeds are cached properly

---

appcues/src/main/java/com/appcues/debugger/screencapture/AndroidTargetingStrategy.kt

This is a defect discovered while doing other tooltip testing. We were previously not checking the return value of [getGlobalVisibleRect](https://developer.android.com/reference/android/view/View#getGlobalVisibleRect(android.graphics.Rect)). However, a false value returned means none of the view is visible, and "If the method returns false, the contents of r are undefined." This means we were previously allowing some undefined rect values to flow through as target element rects, incorrectly.
This could lead to undesired behavior like this:
| incorrect target | target button is actually behind bottom nav |
| --- | --- |
|  ![Screenshot 2023-10-30 at 4 40 51 PM](https://github.com/appcues/appcues-android-sdk/assets/19266448/558c3f54-de44-4fb8-ba68-318488f26c2e) | ![Screenshot 2023-10-30 at …

Fix element target visibility check

---

appcues/src/main/java/com/appcues/statemachine/StateMachine.kt
appcues/src/main/java/com/appcues/ui/ExperienceRenderer.kt

Item found while testing updates in #528 
[distinctUntilChanged](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/distinct-until-changed.html) is enabled by default on StateFlow, but not on the SharedFlow used here - but we want that behavior here as well, since the state could be emitted multiple times with the same value, during error transitions (i.e. ExperienceAlreadyActive)

Fix issue with duplicate state updates in shared flow

---

appcues/src/main/java/com/appcues/data/model/Experience.kt
appcues/src/main/java/com/appcues/ui/presentation/AppcuesViewModel.kt
appcues/src/main/java/com/appcues/ui/presentation/EmbedViewPresenter.kt
appcues/src/main/java/com/appcues/ui/presentation/OverlayViewPresenter.kt
appcues/src/main/java/com/appcues/ui/presentation/ViewPresenter.kt
appcues/src/test/java/com/appcues/data/model/ExperienceTest.kt
appcues/src/test/java/com/appcues/ui/presentation/AppcuesViewModelTest.kt
appcues/src/test/java/com/appcues/ui/presentation/EmbedViewPresenterTest.kt
appcues/src/test/java/com/appcues/ui/presentation/OverlayViewPresenterTest.kt

related to https://app.shortcut.com/appcues/story/42518/non-skippable-experience-can-be-skipped-by-device-back-button-or-gesture noticed that since we moved away from the Activity approach, experiences are not handling the back press properly, this change takes into consideration a possible feature "Block" users from dismissing experience by not including skippable traits into the step, but also includes a fix to make so experiences showing can properly handle the native back press

🐛 Back press not being handled on Experiences

---

appcues/src/main/java/com/appcues/analytics/ActivityRequestBuilder.kt
appcues/src/main/java/com/appcues/analytics/AutoPropertyDecorator.kt
appcues/src/main/java/com/appcues/data/remote/appcues/request/ActivityRequest.kt
appcues/src/test/java/com/appcues/analytics/ActivityRequestBuilderTest.kt
appcues/src/test/java/com/appcues/analytics/AutoPropertyDecoratorTest.kt

[sc-58911] and [sc-58912]
A group update API request will now look like
```diff
{
"request_id": "710a3f33-261b-4a56-ac06-aab4519c1f2b",
"user_id": "default-0000",
"account_id": "PLACEHOLDER_ACCOUNT_ID",
"session_id": "4eb0d930-6125-48d0-af09-3e9838764416",
"group_id": "group-name",
"group_update": {
+		"_lastSeenAt": 1699300394324
},
+	"source": "mobile"
}
```

Add request properties - root level source, and group property lastSeenAt

---

appcues/consumer-rules.pro

The update I made in #532 was incorrect for the Moshi response model classes, this should fix that back up - restoring the old rule and adding a new one for ViewElement, which seems like it was working already, but just in case.

Fix proguard rules for Moshi response models

---

appcues/src/main/java/com/appcues/MainModule.kt
appcues/src/main/java/com/appcues/debugger/AppcuesDebuggerManager.kt
appcues/src/main/java/com/appcues/monitor/AppcuesActivityMonitor.kt
appcues/src/main/java/com/appcues/ui/presentation/ViewPresenter.kt
appcues/src/main/java/com/appcues/ui/utils/ActivityExt.kt
appcues/src/main/java/com/appcues/util/AppcuesViewTreeOwner.kt
appcues/src/test/java/com/appcues/ModulesTests.kt
samples/kotlin-android-app/src/main/java/com/appcues/samples/kotlin/signin/SignInActivity.kt

Initially this was focusing more on the debugger behavior, but I guess we can now more generally handle views that are not "ViewTreeOwners" for both the debugger and PresenterViews, its basically an extra safety that can enable the debugger and experiences to show for customers on old Activity apis.

♻️  Debugger adding view tree owners on demand

---

appcues/src/main/java/com/appcues/analytics/AnalyticsModule.kt
appcues/src/main/java/com/appcues/analytics/AnalyticsQueueProcessor.kt
appcues/src/main/java/com/appcues/analytics/AnalyticsTracker.kt
appcues/src/test/java/com/appcues/analytics/AnalyticsQueueProcessorTest.kt
appcues/src/test/java/com/appcues/analytics/AnalyticsTrackerTest.kt
appcues/src/test/java/com/appcues/analytics/StubQueueScheduler.kt

This is a similar update to what was recently done in the web sdk in https://github.com/appcues/javascript-sdk/pull/613
* on `identify(id, props)` or the `appcues:session_started` event - a 50ms timer is started to allow analytics that occur immediately after, to be batched together into the same activity payload to the API.
* the expected use case would be a `group(id, props)` called immediately after `identify(id, props)` resulting in a combined payload with the new user and the current group - this prevents any chance of state group information being used during the resulting qualification on the server for the new user update or session start qualification
* all other analytics are unaffected, unless they also happen within that 50ms window (in which case they would go in this …

Batch group updates with user identification when called right after identify

---

appcues/src/main/java/com/appcues/action/ActionProcessor.kt
appcues/src/main/java/com/appcues/statemachine/effects/ExperienceActionEffect.kt
appcues/src/test/java/com/appcues/statemachine/StateMachineTest.kt
appcues/src/test/java/com/appcues/statemachine/effects/ExperienceActionEffectTest.kt

During regression testing I found an issue where a post complete action to LaunchExperience would lead to StateMachine getting into a deadlock situation, this happens because LaunchExperience is running on the same suspend function as the handleInternalAction and it gets to a point where both are waiting on each other to move on.
this can be tested by tapping on event2 and invoking [this](https://studio.appcues.com/mobile/flows/bf387041-bf99-43b7-b21f-da76bb56340c/settings) experience
now LaunchExperience launches a new coroutine which unlocks the ActionProcessor.process call, and unlocks the whole transition

🐛 LaunchExperience should launch different coroutine and unlock processing actions

---

appcues/src/main/java/com/appcues/trait/appcues/TooltipTrait.kt

I believe this should fix the issue with tooltips getting into a layout loop causing the width to narrow and the leading padding to grow, observed in certain tooltip layouts on specific devices.
before
https://github.com/appcues/appcues-android-sdk/assets/19266448/a17a9fc2-942d-4837-8400-b18467fe9527
after
https://github.com/appcues/appcues-android-sdk/assets/19266448/7bc8f06a-71ea-4b0d-987d-0490831bb129

Enforce tooltip width remains fixed at calculated value

---

appcues/src/main/java/com/appcues/action/ActionRegistry.kt
appcues/src/main/java/com/appcues/action/appcues/LinkAction.kt
appcues/src/main/java/com/appcues/data/mapper/experience/ExperienceMapper.kt
appcues/src/test/java/com/appcues/action/appcues/LinkActionTest.kt

bug found during exploration test for the 3.1.5 release, its very low severity since its an edge case, but for future versions we can handle invalid deeplinks, we can also display a log error in the debugger so customers can figure out why they are not navigating properly

🐛 Properly handle link actions for invalid deep links

---

appcues/src/main/java/com/appcues/debugger/DebuggerViewModel.kt
appcues/src/main/java/com/appcues/debugger/screencapture/ScreenCaptureProcessor.kt
appcues/src/main/java/com/appcues/debugger/ui/DebuggerComposition.kt

Customer was unable to take screenshot on a full compose app. I was able to reproduce by installing Appcues into [NowInAndroid](https://github.com/android/nowinandroid). the error message suggest that the method we were using for taking screenshots is probably not the most recommended, so for API 26+ I switched to an approach that uses PixelCopy.
+ When I changed to PixelCopy I noticed that the screenshot was being taken on the mainThread (probably) causing the visibility animation of the FAB to lag for some frames, so I changed our internal logic, we now wait for the fab to dismiss before taking the screen shot, this also means that we don't need to "prepare" and "restore" anymore as the FAB is no longer there.
Tested on API 22, 25, 26, 32

🐛 Fix screenshot for API 26+ when target view that  doesn’t support hardware bitmaps.

---

appcues/src/main/java/com/appcues/monitor/AppcuesActivityMonitor.kt
appcues/src/main/java/com/appcues/statemachine/states/RenderingStepState.kt
appcues/src/main/java/com/appcues/ui/ExperienceRenderer.kt
appcues/src/main/java/com/appcues/ui/StateMachineDirectory.kt
appcues/src/main/java/com/appcues/ui/presentation/AppcuesViewModel.kt
appcues/src/main/java/com/appcues/ui/presentation/ViewPresenter.kt
appcues/src/test/java/com/appcues/monitor/AppcuesActivityMonitorTest.kt
appcues/src/test/java/com/appcues/statemachine/states/RenderingStepStateTest.kt

https://app.shortcut.com/appcues/story/59914/anchored-tooltip-positioning-issue-on-rotation-to-landscape
During investigation it was discovered that sometimes we are also dismissing the current Experience, if for some reason when configuration changes we hit the onActivityChanged callback from ActivityMonitor (1), and then when the experience is able to persist through the configuration changing the current state of the state machine was the same was before (2) this is why we see this anchored tooltip issue in the first place.
So:
1 - ActivityMonitor now better differentiate between activity changes and configuration changes (new callback method too)
2 - Introduced new action `RestartStep` (open to name suggestions) that we can send to RenderingStepState to move to BeginningStepState and …

🐛 Invalidate current step and re-present onConfigurationChanged

---

appcues/src/main/java/com/appcues/debugger/screencapture/AndroidTargetingStrategy.kt
appcues/src/main/java/com/appcues/statemachine/Error.kt
appcues/src/main/java/com/appcues/statemachine/effects/PresentationEffect.kt
appcues/src/main/java/com/appcues/trait/AppcuesTraitException.kt
appcues/src/main/java/com/appcues/trait/appcues/TargetElementTrait.kt
appcues/src/main/java/com/appcues/ui/ExperienceRenderer.kt
appcues/src/main/java/com/appcues/ui/ModalStateMachineOwner.kt
appcues/src/main/java/com/appcues/ui/StateMachineDirectory.kt
appcues/src/test/java/com/appcues/statemachine/StateMachineTest.kt
appcues/src/test/java/com/appcues/ui/ExperienceRendererTest.kt

Stacks on error/retry handling in #528 
Creating a draft here for feedback on approach.
The bulk of the work is being done in the `ModalStateMachineOwner` now - split out from the main ExperienceRenderer, as this is Modal render context specific logic. There are a variety of options available to observe changes in the view tree, using a ViewTreeObserver. This starts out by watching scroll, global layout changes, and draw updates - detecting when the UI is idling by waiting for a 1 sec period after all updates have concluded, before attempting a retry.
The retry is controlled by listening for StepErrors that are marked recoverable. Only selected errors are such type, like "no target element found" and "multiple matching targets" - things that _could_ be resolved by UI updates. Each time a …

Add retry handling on tooltip render when ui layout updates are detected

---

appcues/src/main/java/com/appcues/analytics/AnalyticsTrackerExt.kt
appcues/src/main/java/com/appcues/analytics/ExperienceLifecycleTracker.kt
appcues/src/main/java/com/appcues/debugger/screencapture/AndroidTargetingStrategy.kt
appcues/src/main/java/com/appcues/statemachine/Action.kt
appcues/src/main/java/com/appcues/statemachine/Error.kt
appcues/src/main/java/com/appcues/statemachine/State.kt
appcues/src/main/java/com/appcues/statemachine/StateMachine.kt
appcues/src/main/java/com/appcues/statemachine/Transition.kt
appcues/src/main/java/com/appcues/statemachine/effects/PresentationEffect.kt
appcues/src/main/java/com/appcues/statemachine/states/FailingState.kt
appcues/src/main/java/com/appcues/trait/AppcuesTraitException.kt
appcues/src/main/java/com/appcues/trait/appcues/TargetElementTrait.kt
appcues/src/main/java/com/appcues/ui/ExperienceRenderer.kt
appcues/src/main/java/com/appcues/ui/ModalStateMachineOwner.kt
appcues/src/main/java/com/appcues/ui/StateMachineDirectory.kt
appcues/src/test/java/com/appcues/analytics/ExperienceLifecycleTrackerTest.kt
appcues/src/test/java/com/appcues/statemachine/StateMachineTest.kt
appcues/src/test/java/com/appcues/statemachine/effects/PresentationEffectTest.kt
appcues/src/test/java/com/appcues/statemachine/states/BeginningExperienceStateTest.kt
appcues/src/test/java/com/appcues/statemachine/states/BeginningStepStateTest.kt
appcues/src/test/java/com/appcues/statemachine/states/EndingExperienceStateTest.kt
appcues/src/test/java/com/appcues/statemachine/states/EndingStepStateTest.kt
appcues/src/test/java/com/appcues/statemachine/states/FailingStateTest.kt
appcues/src/test/java/com/appcues/statemachine/states/IdlingStateTest.kt
appcues/src/test/java/com/appcues/statemachine/states/RenderingStepStateTest.kt
appcues/src/test/java/com/appcues/statemachine/states/StatesTestingHelper.kt
appcues/src/test/java/com/appcues/ui/ExperienceRendererTest.kt
appcues/src/test/java/com/appcues/ui/sm/owner/ModalStateMachineOwnerTest.kt
appcues/src/test/java/com/appcues/ui/sm/owner/StateMachineDirectoryTest.kt

This is some foundational work that will support future research on tooltip error/retry handling. I wanted to put up a preliminary PR checkpoint for feedback.
When an error occurs in the PresentationEffect now, it will use ReportError (as before) but also provide a retry SideEffect object as part of the ReportError Action. This SideEffect is whatever should be retried, if a recover attempt is to be made - in this case, the PresentationEffect again.
The StateMachine then has the ability to handle ReportError by transitioning to a FailingState, which captures the current state (to return to) and the SideEffect to retry, to try again later. FailingState can respond to 
* Retry - try the effect again
* StartExperience - which means something new has come into the machine and it should give up …

Add state machine capabilities for FailingState and Retry action

---

appcues/src/main/java/com/appcues/debugger/screencapture/GetCaptureUseCase.kt
appcues/src/main/java/com/appcues/debugger/ui/CaptureConfirmDialog.kt
appcues/src/main/java/com/appcues/monitor/AppcuesActivityMonitor.kt

It was observed that screen capture could fail sometimes, seemingly randomly, and the log message seen was
```
java.lang.IllegalArgumentException: Window doesn't have a backing surface!
```
The error was seen on a tablet device, using rotation to landscape as well during capture (important later). This message is coming from a call to PixelCopy, which was [introduced recently](https://github.com/appcues/appcues-android-sdk/pull/544) in the 3.1.7 version. 
However, further research seems to show that the root cause was actually a bad current `Activity` reference, from the `AppcuesActivityMonitor`, due to some other recent 3.1.7 changes in https://github.com/appcues/appcues-android-sdk/pull/543. Specifically, on a rotation change, the `onActivityCreated` handler would not set the current …

Fix issue with screen capture not working in some scenarios

---

docs/Identifying.md

Per recent customer feedback and [discussion](https://appcues.slack.com/archives/C031RLGS4F8/p1704495749255789) - moving to an approach where we do not provide a code snippet including `"appcues:user_id_signature"` that could mistakenly be copy/pasted, and rather a less explicit pointer to the main help doc for identity verification - for the less common use case where those details are needed.

Update identity verification note to point to central help doc

---

appcues/src/main/java/com/appcues/action/appcues/TrackEventAction.kt
appcues/src/test/java/com/appcues/action/appcues/TrackEventActionTest.kt

This is part of a larger initiative for integrations related to button clicks, on our end for now we need to add an attribute property that can receive generic information from builder, and pass it as properties when calling appcues.track internally.

✨ Adding attributes to action @appcues/track

---

appcues/src/main/java/com/appcues/Appcues.kt
appcues/src/main/java/com/appcues/DeepLinkHandler.kt
appcues/src/main/java/com/appcues/action/appcues/LaunchExperienceAction.kt
appcues/src/main/java/com/appcues/data/AppcuesRepository.kt
appcues/src/main/java/com/appcues/data/model/Experience.kt
appcues/src/main/java/com/appcues/data/remote/appcues/AppcuesRemoteSource.kt
appcues/src/main/java/com/appcues/data/remote/appcues/AppcuesService.kt
appcues/src/main/java/com/appcues/ui/ExperienceRenderer.kt
appcues/src/main/java/com/appcues/ui/presentation/ViewPresenter.kt
appcues/src/test/java/com/appcues/AppcuesTest.kt
appcues/src/test/java/com/appcues/DeeplinkHandlerTest.kt
appcues/src/test/java/com/appcues/action/appcues/LaunchExperienceActionTest.kt
appcues/src/test/java/com/appcues/data/AppcuesRepositoryTest.kt
appcues/src/test/java/com/appcues/data/remote/retrofit/AppcuesServiceTest.kt
appcues/src/test/java/com/appcues/data/remote/retrofit/RetrofitAppcuesRemoteSourceTest.kt

matching iOS https://github.com/appcues/appcues-ios-sdk/pull/489.
Enabling query params from builder deeplinks (preview and show) to be used by de SDK when calling the end points for preview and show.
this use case is currently aiming to solve the localeId properly related to localization feature.

♻️  Adding Query params for deeplink preview and show

---

appcues/src/main/java/com/appcues/debugger/screencapture/GetCaptureUseCase.kt

I believe this will fix the issue seen recently with apps using HW accelerated views trying to take screen captures. The error observed was:
```
java.lang.Exception: java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps
```
This error was coming from the lines removed in this PR.
What I believe happened was
* A fix was made in https://github.com/appcues/appcues-android-sdk/pull/544 that corrected the behavior, and worked, in version 3.1.7
* Some refactoring was then done in https://github.com/appcues/appcues-android-sdk/pull/546 and when the `GetCaptureUseCase` was created, a couple of lines were accidentally copied over into this spot where they should not be. These lines are from the `captureLegacyBitmap` implementation - which should only be used on …

Fix screen capture bitmap handling with hardware accelerated views

---

appcues/src/main/java/com/appcues/analytics/AutoPropertyDecorator.kt
appcues/src/main/java/com/appcues/debugger/DebuggerRecentEventsManager.kt
appcues/src/test/java/com/appcues/analytics/AutoPropertyDecoratorTest.kt

Keeping in sync with Web Frontend change to include _lastSeenAt as _updatedAt is deprecated but is still used for targeting.
included:
* changes to autoPropertyDecorator.
* change to Debugger for recent events to use new property
* changes to unit tests

✨ Adding _lastSeenAt autoProp to identify and event analytics

---

appcues/src/main/java/com/appcues/ui/presentation/ViewPresenter.kt

Experience was not showing because the composition was losing state, I still did not figure out what exactly made so the experience was stuck, but it was related to how React Native keeps "refreshing" the layout direction, so by adding LayoutDirection.current to the main key clause we ensure to re-compose from scratch when a new value is passed in.

🐛 Fix to React Native RTL

---

appcues/src/main/java/com/appcues/analytics/ActivityRequestBuilder.kt
appcues/src/main/java/com/appcues/data/remote/appcues/request/ActivityRequest.kt
appcues/src/test/java/com/appcues/AnalyticsPublisherTest.kt
appcues/src/test/java/com/appcues/analytics/AnalyticsQueueProcessorTest.kt
appcues/src/test/java/com/appcues/analytics/AutoPropertyDecoratorTest.kt
appcues/src/test/java/com/appcues/data/AppcuesRepositoryTest.kt

adding app_id as a root property of the ActivityRequest, this is how the new request looks like:
```json
{
"request_id": "a6e00d46-2343-4bf3-a131-396da3560fd4",
"events": [ ... ],
"profile_update": { ... },
"user_id": "default-0000",
"account_id": "103523",
"app_id": "4b6b796f-1313-440a-b356-ee4b7abe931c",
"session_id": "8f368e26-d3da-4b30-83c6-08df9d66d48a",
"group_id": null,
"source": "mobile"
}
```

✨ Adding app_id to ActivityRequest

---

appcues/build.gradle
appcues/src/main/java/com/appcues/debugger/screencapture/AndroidTargetingStrategy.kt
appcues/src/main/java/com/appcues/ui/extensions/StyleComponentExt.kt
appcues/src/main/java/com/appcues/ui/modal/BottomSheetModal.kt
appcues/src/main/java/com/appcues/ui/modal/DialogModal.kt
appcues/src/main/java/com/appcues/ui/modal/ExpandedBottomSheetModal.kt
appcues/src/main/java/com/appcues/ui/primitive/OptionSelectPrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/TextInputPrimitive.kt
appcues/src/main/java/com/appcues/ui/theme/AppcuesExperienceTheme.kt

Migrating from compose 1.5 to 1.6
it was necessary to remove the MaterialTheme since they constraint the line height to a proper font style, since we dynamically decide on the font size and possibly custom font height, using MaterialTheme as our overall theme is no longer an option.
* Pending to figure out if there is a way to minimize the differences in text display from the material theme and the standard theme.

⬆️  Update compose from 1.5 to 1.6

---

appcues/src/main/java/com/appcues/debugger/DebuggerViewModel.kt
appcues/src/main/java/com/appcues/debugger/model/DebuggerToast.kt
appcues/src/main/java/com/appcues/debugger/screencapture/SaveCaptureUseCase.kt
appcues/src/main/java/com/appcues/debugger/screencapture/ScreenCaptureSaveException.kt
appcues/src/main/java/com/appcues/debugger/ui/ToastView.kt
appcues/src/main/res/values/strings.xml

Adding more descriptive error message when the session token is invalid.

✨ Adding error description for InvalidToken 400 during screen capture

---

appcues/src/main/java/com/appcues/AppcuesConfig.kt
appcues/src/main/java/com/appcues/debugger/DebuggerFontManager.kt
appcues/src/main/java/com/appcues/debugger/DebuggerModule.kt
appcues/src/main/java/com/appcues/debugger/ui/ds/BoxComponents.kt
appcues/src/main/java/com/appcues/debugger/ui/fonts/DebuggerFontList.kt
appcues/src/main/java/com/appcues/debugger/ui/logs/DebuggerLogDetails.kt
appcues/src/main/java/com/appcues/debugger/ui/logs/DebuggerLogList.kt
appcues/src/main/java/com/appcues/logging/LogType.kt
appcues/src/main/java/com/appcues/logging/LogcatDestination.kt
appcues/src/main/java/com/appcues/logging/Logcues.kt
appcues/src/main/java/com/appcues/ui/composables/AppcuesComposition.kt
appcues/src/main/java/com/appcues/ui/composables/CompositionLocals.kt
appcues/src/main/java/com/appcues/ui/extensions/StyleComponentExt.kt
appcues/src/main/java/com/appcues/ui/extensions/TextStyleExt.kt
appcues/src/main/java/com/appcues/ui/presentation/ViewPresenter.kt
appcues/src/main/java/com/appcues/ui/primitive/BoxPrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/ButtonPrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/HorizontalStackPrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/TextInputPrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/TextPrimitive.kt
appcues/src/main/java/com/appcues/ui/primitive/VerticalStackPrimitive.kt
appcues/src/main/res/values/strings.xml
appcues/src/test/java/com/appcues/logging/LogcuesTest.kt
docs/Fonts.md
samples/kotlin-android-app/src/main/java/com/appcues/samples/kotlin/ExampleApplication.kt

Adding the property packageNames that allows customers to set different paths when we look for fonts in res/fonts
* Adding to the debugger scan was easy and straight forward
* Adding to the composition (Text and Syles) on the other hand required a lot of change 
-> Created `LocalPackageNames` 
Improving logging when font coming from builder is not found:
also Adding informative block about missing fonts

✨ Adding option for packageNames in AppcuesConfig

---

appcues/src/main/AndroidManifest.xml
appcues/src/main/java/com/appcues/action/ActionRegistry.kt
appcues/src/main/java/com/appcues/action/appcues/RequestPushAction.kt
appcues/src/main/java/com/appcues/ui/RequestPermissionActivity.kt

Adding appcues/request-push action 
Creates a new transparent activity just so we can call permission request and listen to the return of the REQUEST_CODE, which is internally implemented by this new API `ActivityResultLauncher `

✨ Adding request-push action

---

samples/kotlin-android-app/src/main/java/com/appcues/samples/kotlin/main/MainActivity.kt

simple addition of query param on sample app deeplink to support showing content after moving to a particular screen. like so:
```kotlin
deeplink-android "appcues-example://profile?experience=dc3c3e23-cc34-4720-94b8-6a1db104dc7d"
```

♻️  Updating sample app to support show experience

---

appcues/src/main/java/com/appcues/debugger/DebuggerStatusManager.kt
appcues/src/main/java/com/appcues/debugger/model/DebuggerStatusItem.kt

When verifying the push setup, if permission is not granted customer can tap on the same line and open settings page to give permission manually (this is done this one to avoid having to deal with different scenarios like permission denied forever, api level differences, etc)

✨ Adding shortcut for settings when Push notification permission is not granted

---

appcues/src/main/java/com/appcues/AppcuesFirebaseMessagingService.kt
appcues/src/main/java/com/appcues/DeepLinkHandler.kt
appcues/src/main/java/com/appcues/util/NotificationBuilderExt.kt

including properties: `notification_version` and `workflow_version` as part of notification data model.
also whenever they are present we want to include both in the push_opened track.
+ Renaming `id` to `notificationId` and  old `notificationId` to `androidNotificationId` for clarification

♻️  Adding properties to push data & improve naming

---

appcues/src/main/java/com/appcues/DeepLinkHandler.kt
appcues/src/main/java/com/appcues/SessionMonitor.kt
appcues/src/main/java/com/appcues/analytics/AnalyticsTracker.kt
appcues/src/main/java/com/appcues/push/PushDeeplinkHandler.kt
appcues/src/main/java/com/appcues/push/PushOpenedAction.kt
appcues/src/main/java/com/appcues/push/PushOpenedProcessor.kt
appcues/src/main/java/com/appcues/util/NotificationBuilderExt.kt

First pass of this task. here we are storing in Room table the deferred actions (currently Track, Deeplink and ShowContent) when we see that sessionMonitor has no active session, else we run those normally.
+ Separated some piece of DeeplinkHandler for clarity and to solve some detekt warnings (Complex methods)
This is the big chunk, want to make sure this makes sense before moving forward, the idea here is that we will be storing deferred actions based on appId and userId (to account for different sessions and multi-instances of appcues),
and then later we are going to implement the other piece which after the identify we will see if there is any elements in that list and run those, also clear those elements from the list afterwards.

♻️  Storing deferred actions when processing notification deeplink in no-session run

---

appcues/src/main/java/com/appcues/Appcues.kt
appcues/src/main/java/com/appcues/MainModule.kt
appcues/src/main/java/com/appcues/SessionMonitor.kt
appcues/src/test/java/com/appcues/analytics/AnalyticsTrackerExtTest.kt
appcues/src/test/java/com/appcues/analytics/AnalyticsTrackerTest.kt
appcues/src/test/java/com/appcues/rules/TestScopeRule.kt

Last piece for this task, consuming deferred action for given userId during the identify call, similarly to whats done on iOS [here](https://github.com/appcues/appcues-ios-sdk/blob/sdk4/Sources/AppcuesKit/Appcues.swift#L404)
* Minor changes to adjust unit tests.

♻️  Processing deferred notification actions during identify call

---

codecov.yml

targeting `main` (we can then rebase `sdk4`). Noticed a failure on a `-0.02%` drop recently.
same update made on iOS side a while back in https://github.com/appcues/appcues-ios-sdk/commit/b9a342e5dfc3235ac1f8fe0061bd14f3b67a6bcb

Make Codecov more lenient about small drops in coverage

---

appcues/src/main/java/com/appcues/analytics/AutoPropertyDecorator.kt
appcues/src/main/java/com/appcues/data/remote/customerapi/CustomerApiRemoteSource.kt
appcues/src/main/java/com/appcues/debugger/DebuggerStatusManager.kt
appcues/src/main/java/com/appcues/util/ContextWrapper.kt
appcues/src/main/res/values/strings.xml

Adding extra check that verifies that there is a Service filtered by the firebase messaging Action.
if there is another one not the default FirebaseMessagingService it means they are either using Appcues's or a custom one (which is what we want)
+ Re-ordered existing error messages to match the sequence they are being checked.

♻️  Adding new push verification check for the manifest.xml

---

.circleci/config.yml
fastlane/Fastfile
fastlane/replace-placeholders.sh
samples/kotlin-android-app/.gitignore
samples/kotlin-android-app/google-services.json

syncing up the approach used for the RN project, we include the google-services.json while hiding the key as GOOGLE_SERVICES_KEY placeholder
* Found an issue with the latest android image, changing from default to a static reference for now until we take a proper look at whats happening there.

✨ Adding google services key (protected key)

---

appcues/src/main/java/com/appcues/Appcues.kt
appcues/src/main/java/com/appcues/SessionMonitor.kt
appcues/src/main/java/com/appcues/action/appcues/RequestPushAction.kt
appcues/src/main/java/com/appcues/analytics/AutoPropertyDecorator.kt

I put this in `SessionMonitor`, piggybacking on some lifecycle observation already there, as a simple add-on. This could also be moved into its own class if you feel like it shouldn't mix in with the SessionMonitor like this. I thought it was simple enough to put here, but also take no issue if preference is to not do that.

Check for push enabled status changes while app is not active

---

appcues/src/main/java/com/appcues/action/ActionRegistry.kt
appcues/src/main/java/com/appcues/action/appcues/DelayAction.kt
appcues/src/test/java/com/appcues/action/appcues/DelayActionTest.kt

Adding support for the new @appcues/delay action:
```json
{
"on": "navigate",
"type": "@appcues/delay",
"config": {
"duration": 3000
}
}
```

✨ Adding delay action

---

appcues/src/main/java/com/appcues/Appcues.kt

Removing deprecated anonymous call as part of sdk4 breaking changes

💥 Removing deprecated Anonymous call

---

appcues/src/main/java/com/appcues/statemachine/states/EndingStepState.kt
appcues/src/main/java/com/appcues/statemachine/states/RenderingStepState.kt
appcues/src/main/java/com/appcues/ui/presentation/ViewPresenter.kt
appcues/src/test/java/com/appcues/statemachine/states/RenderingStepStateTest.kt

Reported by a customer in [#mobile-support ](https://appcues.slack.com/archives/C03JYPH1NJZ/p1724931068889339) it looks like an oversight on our part for some of the possible outcomes from creating an overlay activity on top of an existing activity that was presenting an experience.
changes: 
* When transitioning from [RenderingStep to EndingExperience](https://github.com/appcues/appcues-android-sdk/compare/fix/overlay_view_experience?expand=1#diff-9a2951280d6c94900b1fb1c73e24089e62d7f593ef819d695183f858be5a74cdR92) we will always pass in the AwaitDismissEffect to ensure that it will always fire up a new ui state in AppcuesViewModel.
*  Since the reported issue was this error message `java.lang.IllegalStateException: Method removeObserver must be called on the main thread` when …

🐛 fix state machine when another activity is started on top

---

appcues/build.gradle
appcues/src/main/java/com/appcues/debugger/ui/CaptureConfirmDialog.kt
appcues/src/main/java/com/appcues/debugger/ui/DebuggerComposition.kt
appcues/src/main/java/com/appcues/debugger/ui/DebuggerFloatingActionButton.kt
appcues/src/main/java/com/appcues/debugger/ui/DebuggerFloatingActionEvents.kt
appcues/src/main/java/com/appcues/trait/appcues/CarouselTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/SkippableTrait.kt
appcues/src/main/java/com/appcues/ui/extensions/StyleComponentExt.kt
appcues/src/main/java/com/appcues/ui/primitive/ExperiencePrimitive.kt
appcues/src/main/java/com/appcues/ui/utils/AppcuesMargins.kt
appcues/src/test/java/com/appcues/data/model/ExperienceTest.kt
appcues/src/test/java/com/appcues/statemachine/effects/PresentationEffectTest.kt
samples/kotlin-android-app/build.gradle
samples/kotlin-android-app/src/main/java/com/appcues/samples/kotlin/main/MainActivity.kt

These are the updates I think are needed for Compose 1.7+ to work, plus misc other version updates to bring up to latest. This appears to have no cascading effects on the Kotlin version (due to staying on same Compose Compiler version 1.4.8) or on anything like Android targetSdk - so, I think rather safe for rolling out across our platforms, but that is what I'll be testing next.
Without this update, any app that begins using Compose 1.7 will hit a crash at runtime with an error like:
```
java.lang.NoSuchMethodError: No static method HorizontalPager-xYaah8o(Landroidx/compose/foundation/pager/PagerState;Landroidx/compose/ui/Modifier;Landroidx/compose/foundation/layout/PaddingValues;Landroidx/compose/foundation/pager/PageSize;IFLandroidx/compose/ui/Alignment$Vertical;Landroidx/compose/founda …
```

Update Compose and some other dependencies

---

appcues/src/main/java/com/appcues/trait/appcues/EmbedTrait.kt

Discovered that we were not handling background color on embeds correctly.
It looks like the Compose 1.5 -> 1.6 update a while back required a change in the code for this, and most of those were handled in this PR like https://github.com/appcues/appcues-android-sdk/pull/562/files#diff-afc24a72ab4ac5516ef5e46774a4ca3ea80
Full screen modal got missed, and fixed in https://github.com/appcues/appcues-android-sdk/pull/591
This should be the final related fix.

Fix embed background color not applying

---

appcues/src/main/java/com/appcues/debugger/ui/DebuggerPanel.kt

There is a crash when tapping a row in the debugger event history, to view event details - or to navigate to any sub page of the debugger, for that matter.
The issue is that the recent update to navigation-compose 2.8.1 introduced a conflict with our own implementation of `NavController.navigate(DebuggerPage)` and the [newly added](https://developer.android.com/reference/androidx/navigation/NavController#navigate(kotlin.Any,kotlin.Function1)) `NavController.navigate(any)` from version 2.8.1. This is part of a [type safe navigation project in Compose](https://medium.com/androiddevelopers/navigation-compose-meet-type-safety-e081fb3cf2f8), but not actually something we are using yet, or intend to at this point due to the implication of using newer versions of Kotlin that it requires.
Simply …

Disambiguate function for navigating debugger pages

---

README.md
appcues/build.gradle

After analyzing our dependency usage a bit more, I discovered that reverting coil (image loading), moshi (json) and navigation-compose (debugger nav) components back to previous versions before #635  allows us to update to Compose 1.7.2 without imposing a new requirement of Kotlin 1.9. I don't see any compelling reason to force this upgrade, so I propose we keep those as-is. This lessens the burden of integration on some cross platform frameworks as well. Our minimum Kotlin version is 1.8.22 [as determined by the Compose compiler](https://developer.android.com/jetpack/androidx/releases/compose-kotlin) currently.
There does not appear to be any way to avoid the AGP 8+ requirement at this point, as it seems Compose 1.7 requires that. Hopefully this is acceptable, as that version has been …

Revert dependency versions to avoid kotlin version requirement change

---

appcues/src/main/java/com/appcues/analytics/AutoPropertyDecorator.kt
appcues/src/test/java/com/appcues/analytics/AutoPropertyDecoratorTest.kt

Will help support options in the future to only send push notifications within certain time windows in the device's timezone. This property is set at the user level (last known value) and each device level.

Add _timezoneOffset auto property

---

.gitignore
appcues/src/debug/java/com/appcues/CompositionTestHelper.kt
appcues/src/main/java/com/appcues/data/model/Experience.kt
appcues/src/main/java/com/appcues/data/model/Step.kt
appcues/src/main/java/com/appcues/trait/appcues/SkippableTrait.kt
appcues/src/main/java/com/appcues/ui/composables/AppcuesComposition.kt
appcues/src/main/java/com/appcues/ui/composables/CompositionLocals.kt
appcues/src/main/java/com/appcues/ui/composables/StepComposition.kt
appcues/src/main/java/com/appcues/ui/modal/DialogModal.kt
appcues/src/main/java/com/appcues/ui/presentation/AppcuesViewModel.kt
appcues/src/main/java/com/appcues/ui/presentation/ViewPresenter.kt
appcues/src/test/java/com/appcues/data/model/ExperienceTest.kt
appcues/src/test/java/com/appcues/ui/presentation/AppcuesViewModelTest.kt

This adds swipe to dismiss behavior similar to what was done for iOS in https://github.com/appcues/appcues-ios-sdk/pull/564
The core functionality builds upon the `.anchoredDraggable` Modifier that was added in Compose a few versions back https://fvilarino.medium.com/exploring-jetpack-compose-anchored-draggable-modifier-5fdb21a0c64c
We conditionally add this modifier if (A) the transition on the modal trait is `slide` (a slideout) and (B) the transition is from an edge (not center). The modifier defines an initial anchor point where the content is presenting, and then a dismissal anchor that represents the content being fully off screen. In the case that the content is not dismissible (the `ignoreBackdropTap: true` case on the `@appcues/skippable` trait) - the dismissal anchor moves to …

Add support for swipe to dismiss on slideouts from edge

---

appcues/src/main/java/com/appcues/data/mapper/step/StepMapper.kt
appcues/src/main/java/com/appcues/trait/BackdropDecoratingTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/BackdropKeyholeTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/BackdropTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/EffectsTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/SkippableTrait.kt
appcues/src/main/java/com/appcues/trait/appcues/TargetInteractionTrait.kt
appcues/src/main/java/com/appcues/ui/composables/AppcuesComposition.kt

stacks on #642 
Similar change to iOS update in https://github.com/appcues/appcues-ios-sdk/pull/567 - if there is no `@appcues/backdrop` trait, then interactions with the app beneath our content are not blocked.
implications:
* Skippable trait will no longer cover the screen with a tap to dismiss handler, if no backdrop exists
* Target interaction will no longer capture input, if no backdrop exists
* Backdrop keyhole will not attempt to render, if no backdrop exists
* Effects trait will continue to operate as-is, so you could have confetti showing while also allowing interaction with the app behind that confetti
The above updates are accomplished by adding a new `isBlocking` property on any `BackdropDecoratingTrait`, to allow it to declare that it blocks input -- currently only true for …

Allow interaction with underlying app when backdrop is disabled

---

appcues/build.gradle

+ a couple of other minor version updates
Confirmed these don't impact our core dependency versions for gradle, kotlin, etc that would impact a customer. They do add support for this [fix](https://issuetracker.google.com/issues/341880461#comment19), which will allow us to restore some of our automated tests that did not work on the previous version.

Update Jetpack Compose 1.7.2 -> 1.7.3

---

appcues/src/main/java/com/appcues/trait/appcues/CarouselTrait.kt

If a carousel trait is applied but only a single page, we should ignore it - otherwise, it will capture any horizontal scroll gestures and prevent our swipe to dismiss capability.

Don't apply carousel gesture handling if only a single page

---

appcues/src/debug/java/com/appcues/CompositionTestHelper.kt
appcues/src/main/java/com/appcues/trait/appcues/TargetInteractionTrait.kt
appcues/src/main/java/com/appcues/ui/composables/AppcuesComposition.kt
appcues/src/main/java/com/appcues/ui/composables/CompositionLocals.kt
appcues/src/main/java/com/appcues/ui/presentation/AppcuesViewModel.kt
appcues/src/main/java/com/appcues/ui/presentation/ViewPresenter.kt
appcues/src/test/java/com/appcues/ui/presentation/AppcuesViewModelTest.kt

The changes here in the `TargetInteractionTrait` are the key updates. We'll now detect tap gestures, and conditionally forward them back to the underlying Android View that is hosting our experience, if the trait `enablePassThrough` is `true`. This is done by creating synthetic `MotionEvent`s for down + up and sending them to the View. The trait also continues to run any actions declared for tap (or longPress), so these can be combined.
The abstraction to a `LocalAppcuesTapForwardingDelegate` that gets passed through the composition is simply to avoid referencing `LocalViewModel` directly, for snapshot test purposes -- similar to what is done in a couple other spots now.
This example shows a tooltip highlight that allows pass though - note the `event2` that gets fired on the tap, but also …

Allow tap interactions in tooltip highlight area to optionally pass through to underlying views

---

appcues/build.gradle
appcues/src/main/java/com/appcues/debugger/ui/AppcuesSearchView.kt
appcues/src/main/java/com/appcues/debugger/ui/ds/BoxComponents.kt
appcues/src/main/java/com/appcues/debugger/ui/icons/CloseIcon.kt
appcues/src/main/java/com/appcues/debugger/ui/icons/DebuggerIcons.kt
appcues/src/main/java/com/appcues/debugger/ui/icons/InfoIcon.kt

Reported by customer, there was an increase of SDK size because during our Material Compose update we included icons-extension which is heavy.
```
implementation "androidx.compose.material:material-icons-extended:$compose_version"
```
It is possible to keep the library and exclude all icons but the ones we are using, for a simple solution we decided to have our own local icons and avoid including an extra dependency instead.

🐛 Cleanup icons-extension and use local references

---

appcues/src/main/java/com/appcues/util/StringExt.kt
appcues/src/test/java/com/appcues/data/model/ExperienceStepFormStateTest.kt

The hyphen in the scenario described in the ticket was due to replacing of special char `*` with empty space ` `, then splitting on empty space, but not filtering out empty strings, then joining with a `-`. In this case, joining an empty string to the front with a hypen.
Fix here is to (A) filter out empty strings in the join, and (B) trim any leading hyphen for good measure.
| before | after | 
| --- | --- |
|  ![before](https://github.com/user-attachments/assets/74248537-09df-4c0a-841d-60b1ebd1c610) |  ![after](https://github.com/user-attachments/assets/226edf0c-f87e-491a-8385-9cb8c5418ffd) |

Trim any leading hyphen on form response generated property names

---

appcues/src/main/java/com/appcues/data/MoshiConfiguration.kt
appcues/src/main/java/com/appcues/data/remote/appcues/response/step/primitive/PrimitiveResponse.kt

This change resolves an issue that a customer observed where minified builds (Proguard) would fail to render an experience. The issue resulted in a JSON deserialization error, from Moshi, the JSON library we use.
```
com.squareup.moshi.JsonDataException: Expected one of [STACK, BOX, CUSTOM_COMPONENT, BUTTON, TEXT, IMAGE, EMBED, SPACER, TEXT_INPUT, OPTION_SELECT, BLOCK] but was text at path $.steps[0].children[0].content.items[0].items[0].content.errorLabel.type
```
Tracing through the problem and the customer provided build configuration. I was able to reproduce by using the `-dontshrink` option in a sample app proguard-rules.pro file, and building against a matching Kotlin version `2.1.0` (our core sdk still builds against the older `1.8.22`) - using a release config build with …

simplify primitive deserialization

---

appcues/src/main/java/com/appcues/ui/utils/ActivityExt.kt

Discovered during investigation of a customer issue. When one Activity is navigating back to another Activity, there is a brief moment in time where `WindowInspector.getGlobalWindowViews()` will return multiple global views - one for both the exiting and entering Activities. We were not properly filtering to find our target view to inject content. We should always find the view that is within the target Activity we are rendering content within (already known from our `AppcuesActivityMonitor`).
To reproduce, I qualified for content in a Fragment onResume, right as one Activity was exiting to return to the previous Activity and returning back to the screen to qualify. This correctly results in the "current" Activity we track updating …

Ensure content is rendered in the correct Activity view hierarchy

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

Staying current here on build tooling, also for my local builds the current codebase is very slow to build in recent releases of Android Studio - this update seems to help that.

Update to AGP 8.9.1

---

appcues/src/main/java/com/appcues/DeepLinkHandler.kt
appcues/src/main/java/com/appcues/debugger/DebuggerViewModel.kt
appcues/src/main/java/com/appcues/debugger/model/DebuggerConstants.kt
appcues/src/main/java/com/appcues/debugger/ui/DebuggerExt.kt
appcues/src/main/java/com/appcues/debugger/ui/DebuggerFloatingActionEvents.kt
appcues/src/main/java/com/appcues/push/PushDeeplinkHandler.kt
appcues/src/main/res/values/strings.xml

It was discovered that on cross platform frameworks, the push open tracking was not working as expected. The reason for this is the usage of Intent `extras` to pass the push details. 
The simplest approach I could think of to improve this was to just move to a URL query parameter approach to pass the extras, which accomplishes the same result but is cross-platform friendly with things like React Native linking - where the URL is already passed back to the JS side of the app and processed through normal deep link handling (passing into our SDK). This seems to work fine and allow us to avoid any other changes on the x-plat sides.
Here is the end result in React Native using an updated local library for the native dependency - Push opens, tracks analytics, and launches a linked flow: …

Improve push open handling

---

appcues/src/main/java/com/appcues/AppcuesFrameView.kt
appcues/src/main/java/com/appcues/analytics/ExperienceLifecycleTracker.kt
appcues/src/main/java/com/appcues/statemachine/Action.kt
appcues/src/main/java/com/appcues/statemachine/StateMachine.kt
appcues/src/main/java/com/appcues/statemachine/states/EndingExperienceState.kt
appcues/src/main/java/com/appcues/statemachine/states/EndingStepState.kt
appcues/src/main/java/com/appcues/ui/ExperienceRenderer.kt
appcues/src/main/java/com/appcues/ui/StateMachineDirectory.kt
appcues/src/test/java/com/appcues/statemachine/StateMachineTest.kt
appcues/src/test/java/com/appcues/statemachine/states/EndingExperienceStateTest.kt
appcues/src/test/java/com/appcues/statemachine/states/EndingStepStateTest.kt
appcues/src/test/java/com/appcues/ui/ExperienceRendererTest.kt
docs/AppcuesFrameViewConfiguring.md

The idea here is to add a `retainContent` (default true) option on `AppcuesFrameView`, to give control over how the embed cache operates. 
By default, a frame with embed content can render over and over as the same frameId is re-registered in a situation like a recycler view. However, in some use cases this is undesired, and a subsequent render of the embed on a new view load would actually show content that was not supposed to be qualified. If a fragment is launching, for instance, and sometimes should qualify, but sometimes not - each new render of the view should only show current qualified experiences - nothing from cache. This can now be accomplished by setting `retainContent = false` on that particular frame view.
Note: we also had a bug here where the desired recyclerView behavior …

Add an option to control embed cache behavior and retained content

---

appcues/build.gradle

minor update, but wanted to include [this improvement](https://github.com/vanniktech/gradle-maven-publish-plugin/pull/935) for package names during publish to Maven Central that was released
https://github.com/vanniktech/gradle-maven-publish-plugin/releases/tag/0.32.0
it will give a more readable name for each artifact to distinguish this SDK from the Segment plugin, rather than just a UUID value.

Update maven publish plugin to 0.32

---

README.md
appcues/build.gradle
samples/kotlin-android-app/build.gradle

Address #676 
* Updates Jetpack Compose `1.7.3` -> `1.8.2`
* Updates required `compileSdk: 34` -> `compileSdk: 35`
There were changes in Compose 1.8.0-alpha06 to how AnchoredDraggableState confirmValueChange` works [ref](https://developer.android.com/jetpack/androidx/releases/compose-foundation#1.8.0-alpha06) ([code](https://android-review.googlesource.com/c/platform/frameworks/support/+/3260759/5/compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/AnchoredDraggable.kt))
> instead of vetoing state changes, disallowed anchors should not be in the active anchor set, and an OverscrollEffect should be used to indicate the unavailability of the requested action.
We use the veto state changes behavior …

Update to Compose 1.8.2

---

appcues/src/main/java/com/appcues/ui/InAppReviewActivity.kt
appcues/src/main/java/com/appcues/ui/RequestPermissionActivity.kt

I believe this should improve the issue noted in #664 -  by removing the `!!` not-null assertion and safely checking the extra values.
These values could be null in some edge cases when a device has killed a process and then an Activity tries to re-create, potentially. I think this could lead to the observed intermittent crash issue related to these Activities for requesting a permission or app review. Now they will gracefully close in this scenario and can be retried at a later time.

Protect against missing intent extras
