appcues/appcues-android-sdk

- appcues/build.gradle
- appcues/src/main/java/com/appcues/SessionMonitor.kt
- appcues/src/main/java/com/appcues/analytics/AnalyticsPolicy.kt
- appcues/src/main/java/com/appcues/debugger/ui/DebuggerFloatingActionButton.kt
We had a few simple warnings after recent dependency updates - resolving those.
> Fix build warnings

- appcues/build.gradle
- appcues/codecov.gradle
I _think_ this will fix the jacoco report generation and upload in CI build
> Fix code coverage generation

- appcues/src/main/java/com/appcues/debugger/DebuggerStatusManager.kt
very simple bug, debugger needs a special case to handle SessionReset.
> 🐛 Fix bug to properly track session reset on the debugger

- appcues/src/main/java/com/appcues/statemachine/StateMachine.kt
- appcues/src/test/java/com/appcues/statemachine/StateMachineTest.kt
only if it is offset: 1 (or default)
> Add support for closing experience when continue action is used on last step

- appcues/build.gradle
- appcues/src/main/java/com/appcues/data/mapper/DataMapperKoin.kt
- appcues/src/main/java/com/appcues/data/mapper/step/StepContentMapper.kt
- appcues/src/main/java/com/appcues/data/mapper/step/primitives/BoxPrimitiveMapper.kt
- appcues/src/main/java/com/appcues/data/model/ExperiencePrimitive.kt
- appcues/src/main/java/com/appcues/ui/component/AppcuesBoxComponent.kt
- appcues/src/main/java/com/appcues/ui/extensions/ExperiencePrimitiveExt.kt
* Added Box primitive to match IOS behavior
* Fixed Compose Previews
> ✨ Added Box primitive

- appcues/src/main/java/com/appcues/AppcuesKoin.kt
- appcues/src/main/java/com/appcues/action/ActionKoin.kt
- appcues/src/main/java/com/appcues/action/ActionProcessor.kt
- appcues/src/main/java/com/appcues/action/ActionRegistry.kt
- appcues/src/main/java/com/appcues/action/appcues/LaunchExperienceAction.kt
- appcues/src/main/java/com/appcues/action/appcues/LinkAction.kt
- appcues/src/main/java/com/appcues/analytics/ExperienceLifecycleTracker.kt
- appcues/src/main/java/com/appcues/data/mapper/experience/ExperienceMapper.kt
- appcues/src/main/java/com/appcues/data/model/Experience.kt
- appcues/src/main/java/com/appcues/data/remote/response/experience/ExperienceResponse.kt
- appcues/src/main/java/com/appcues/statemachine/SideEffect.kt
- appcues/src/main/java/com/appcues/statemachine/State.kt
- appcues/src/main/java/com/appcues/statemachine/StateMachine.kt
- appcues/src/main/java/com/appcues/statemachine/Transitions.kt
- appcues/src/test/java/com/appcues/action/ActionRegistryTest.kt
- appcues/src/test/java/com/appcues/data/remote/retrofit/stubs/ContentModalOneStubs.kt
- appcues/src/test/java/com/appcues/mocks/ExperienceMocks.kt
- appcues/src/test/java/com/appcues/rules/KoinScopeRule.kt
- appcues/src/test/java/com/appcues/statemachine/StateMachineTest.kt
* I added actionProcessor as the StateMachine dependency.
* Added Tests to cover this new use case of the statemachine
> ✨ Added Support for actions after flow is completed

- appcues/src/main/java/com/appcues/trait/appcues/CarouselTrait.kt
This additional safeguard appears to fix the issue noted in the ticket, for me.  The root cause was that a programmatic transition from page 3 back to page 1 in a modal was causing a page change event on page 2 along the way - this would then get processed like user interaction, sent to the state machine, and update the view to page 2 erroneously.
> Prevent extra page change notifications during programmatic scroll in Pager

- appcues/src/main/res/values/themes.xml
- samples/kotlin-android-app/src/main/res/values/themes.xml
Tested out some other options but it seems like this is the way to go for now.
basically we are applying a translucent mask on status bar, so it will get whatever color it comes from the overlayed activity (customer activity).
I'm not sure how we can properly handle fullscreen activities yet.
> 🐛 Added properties on manifest to ajust how statusbar appear on flows

- appcues/src/main/java/com/appcues/Storage.kt
- samples/kotlin-android-app/src/main/java/com/appcues/samples/kotlin/ExampleApplication.kt
arranged the gettter/setters to be main thread compliancy.
> 🐛 Moved all read/put from main to io thread on Storage

- appcues/src/main/java/com/appcues/ui/ShakeGestureListener.kt
did a call with ben and we went over the expectations for the shake motion, I did some more work based on that.
> 👌 fine tuning shake motion to make it easier to reproduce

- appcues/src/main/java/com/appcues/debugger/DebuggerStatusManager.kt
- appcues/src/main/java/com/appcues/debugger/DebuggerViewModel.kt
- appcues/src/main/java/com/appcues/debugger/ui/main/DebuggerStatusItems.kt
- appcues/src/main/res/values/strings.xml
also fix padding on end of row
> Update wording in Debugger UI for deep link check

- appcues/build.gradle
- build.gradle
* Compose 1.2.0 -> 1.2.1
* Accompanist 0.25.0 -> 0.25.1
* Coil 2.1.0 -> 2.2.0
* Kotlin 1.7.0 -> 1.7.10
> Update dependencies for Compose, Accompanist, Coil, Kotlin

- .idea/detekt.xml
- build.gradle
- gradle/tools/detekt/detekt-build.gradle
This should also resolve the security check noted here https://github.com/appcues/appcues-android-sdk/runs/8096333392
updating org.yaml:snakeyaml:1.31 (from 1.29)
> Update Detekt 1.19.0 -> 1.21.0

- docs/Debugging.md
- docs/URLSchemeConfiguring.md
updating docs to match a better way of checking deep link setup
> 📝 Updating docs related to deep link setup verification

- appcues/src/debug/java/com/appcues/CompositionTestHelper.kt
- appcues/src/main/java/com/appcues/data/MoshiConfiguration.kt
- appcues/src/main/java/com/appcues/data/mapper/step/StepMapper.kt
- appcues/src/main/java/com/appcues/data/mapper/step/primitives/BoxPrimitiveMapper.kt
- appcues/src/main/java/com/appcues/data/mapper/step/primitives/ButtonPrimitiveMapper.kt
- appcues/src/main/java/com/appcues/data/mapper/step/primitives/OptionSelectPrimitiveMapper.kt
- appcues/src/main/java/com/appcues/data/mapper/step/primitives/PrimitiveMapper.kt
- appcues/src/main/java/com/appcues/data/mapper/step/primitives/SpacerPrimitiveMapper.kt
- appcues/src/main/java/com/appcues/data/mapper/step/primitives/StackPrimitiveMapper.kt
- appcues/src/main/java/com/appcues/data/model/ExperiencePrimitive.kt
- appcues/src/main/java/com/appcues/data/model/ModelExtensions.kt
- appcues/src/main/java/com/appcues/data/remote/response/step/primitive/PrimitiveResponse.kt
- appcues/src/main/java/com/appcues/ui/primitive/ExperiencePrimitive.kt
- appcues/src/main/java/com/appcues/ui/primitive/HorizontalStackPrimitive.kt
- appcues/src/main/java/com/appcues/ui/primitive/SpacerPrimitive.kt
Took me longer than expected to pull this one. the main problem I faced here was testing, because a spacer doesnt actually take space on screen unless we modify it to do so.
some important notes I will note to help understand what I had to do to make Spacer work like IOS works
> ✨ Added Spacer primitive block

- appcues/src/main/java/com/appcues/data/mapper/step/primitives/SpacerPrimitiveMapper.kt
- appcues/src/main/java/com/appcues/data/model/ExperiencePrimitive.kt
- appcues/src/main/java/com/appcues/data/remote/response/step/primitive/PrimitiveResponse.kt
- appcues/src/main/java/com/appcues/ui/composables/CompositionLocals.kt
- appcues/src/main/java/com/appcues/ui/primitive/HorizontalStackPrimitive.kt
- appcues/src/main/java/com/appcues/ui/primitive/SpacerPrimitive.kt
- appcues/src/main/java/com/appcues/ui/primitive/VerticalStackPrimitive.kt
first time around I thought spacer would take width/height, but instead it seems like it uses "spacing" as a way for determining space it takes depending on which scope its in (row or column) this PR changes so it reflects IOS behavior
> ♻️  Reworked spacer to match IOS behavior

- appcues/src/main/java/com/appcues/data/AppcuesRepository.kt
- appcues/src/main/java/com/appcues/data/remote/response/QualifyResponse.kt
Quick fix here - should not have made this a required field in the JSON in my previous PR.
> Make the experiments property optional on the QualifyResponse

- appcues/src/main/java/com/appcues/data/mapper/step/primitives/TextInputPrimitiveMapper.kt
- appcues/src/main/java/com/appcues/data/model/styling/ComponentDataType.kt
- appcues/src/main/java/com/appcues/ui/primitive/TextInputPrimitive.kt
Supporting the spec update here https://github.com/appcues/appcues-mobile-experience-spec/pull/110
Ends up adjusting the on screen keyboard like this
> Add support for the url dataType on textInput

- appcues/consumer-rules.pro
- appcues/publish-maven.gradle
when minifying the library we need proguard rules to keep files in the data remote package so it can be used to generate the deserializers
> ✨ Added proguard rules on for consumers of the library

- README.md
doc update for clarity to customers, matching iOS update https://github.com/appcues/appcues-ios-sdk/pull/282
> Provide more direct instruction for setting up the URL scheme during install

- samples/kotlin-android-app/build.gradle
change to build.gradle to make so release to enable minify
> 🔧 update gradle to enable minify on release

- appcues/src/main/java/com/appcues/trait/AppcuesTraitException.kt
- appcues/src/test/java/com/appcues/statemachine/StateMachineTest.kt
forgot to push these changes on previous PR
> 👌 code review updates

- appcues/build.gradle
- appcues/src/main/AndroidManifest.xml
- appcues/src/main/java/com/appcues/monitor/AppcuesActivityMonitor.kt
- appcues/src/main/java/com/appcues/monitor/AppcuesInitializer.kt
- appcues/src/main/java/com/appcues/trait/TraitKoin.kt
- appcues/src/main/java/com/appcues/trait/TraitRegistry.kt
- appcues/src/main/java/com/appcues/trait/appcues/BackdropKeyholeTrait.kt
- appcues/src/main/java/com/appcues/trait/appcues/BackdropTrait.kt
- appcues/src/main/java/com/appcues/trait/appcues/StepAnimationTrait.kt
- appcues/src/main/java/com/appcues/trait/appcues/TooltipTrait.kt
- appcues/src/main/java/com/appcues/ui/AppcuesOverlayViewManager.kt
- appcues/src/main/java/com/appcues/ui/extensions/ModifierExt.kt
- appcues/src/main/res/layout/appcues_overlay_layout.xml
- gradle/tools/detekt/detekt-config.yml
Added @appcues/tooltip. trait to the list. there is a lot of things to define, like what will be the styling options (so far we are only applying the background related styles). also the tooltip pointer is a triangle manually drawn, I tried spending some time trying to make that better with no success for now. 
I think next steps is to work on other styling properties for the tooltip while we wait for more definitions on behavior.
https://user-images.githubusercontent.com/5244805/210830091-e89dedd5-3b84-41c5-be4d-452b6bbdaeb3.mov
> ✨ Added TooltipTrait - first pass

- appcues/src/main/java/com/appcues/data/mapper/step/primitives/TextPrimitiveMapper.kt
- appcues/src/main/java/com/appcues/data/remote/response/step/primitive/PrimitiveResponse.kt
- appcues/src/test/java/com/appcues/data/mapper/step/primitives/TextPrimitiveMapperTest.kt
`targeting release 1.3.0`
PR to sync up behavior for text and spans with IOS and Android data model
> ♻️  Sync data model of TextPrimitive with IOS

- appcues/src/main/java/com/appcues/trait/appcues/BackdropKeyholeTrait.kt
- appcues/src/main/java/com/appcues/trait/appcues/BackdropTrait.kt
- appcues/src/main/java/com/appcues/trait/appcues/StepAnimationTrait.kt
- appcues/src/main/java/com/appcues/trait/appcues/TargetRectangleTrait.kt
- appcues/src/main/java/com/appcues/trait/appcues/TooltipTrait.kt
- appcues/src/main/java/com/appcues/trait/appcues/TooltipsPaths.kt
- appcues/src/main/java/com/appcues/trait/extensions/StepAnimationInfoExt.kt
- appcues/src/main/java/com/appcues/trait/extensions/TargetRectangleInfoExt.kt
properly applying contentDistanceFromTarget (from TargetRectangleTrait) on TooltipTraits
* moving some related code around for better reusability 
Most of the changes are basically moving and deleting duplicated code, but will note in comments important parts
> ✨ Add support for property contentDistanceFromTarget

- appcues/src/main/java/com/appcues/trait/appcues/SkippableTrait.kt
- appcues/src/main/java/com/appcues/trait/appcues/TooltipTrait.kt
- appcues/src/main/java/com/appcues/ui/extensions/DrawScopeEx.kt
minor changes to skippable and tooltip traits for consistency matching ui updates.
> ♻️  update for ui tooltip tests

- appcues/src/main/java/com/appcues/Appcues.kt
- appcues/src/main/java/com/appcues/analytics/ActivityScreenTracking.kt
- appcues/src/main/java/com/appcues/debugger/DebuggerStatusManager.kt
- appcues/src/main/java/com/appcues/ui/AppcuesActivity.kt
- appcues/src/main/java/com/appcues/util/ContextResources.kt
- appcues/src/main/java/com/appcues/util/PackageManagerExt.kt
Some general clean up I thought we could include in next major update.
> Fix compiler warnings for deprecated functions

- appcues/src/main/java/com/appcues/trait/appcues/TargetElementTrait.kt
This is a small, but useful improvement to how the target element trait reads its selector from the config JSON, during the mapping of an experience. This improves on the initial work in #363 .
I was really scratching my head and confusing myself earlier when working on React Native, as an experience I was using to test with was silently failing. No error for invalid selector, not even an error for JSON decoding issues. What was actually happening was that it was failing during the experience mapping, when the trait was trying to decode the config, and the exception thrown was silent since our `CoroutineExceptionHandler` catches (and optionally logs to logcat).
This change will make it so that the config props are read as a simple Map<String, String> rather than using the moshi adapter to …
> Improve error handling when reading target element trait from config

- appcues/src/main/java/com/appcues/ui/extensions/StyleComponentExt.kt
See linked [sc-50938] for details. This adds a layer of protection to avoid any crashes when rendering an Experience using custom fonts on a user device with an OS version that does not support that custom font resource.
> Guard against missing Font resources for custom font names

- appcues/src/debug/java/com/appcues/CompositionTestHelper.kt
This adjustment will allow our UI test library to snapshot test combinations of traits, for example: tooltip + target-rectangle. It will also allow optionally overriding the step content with another predefined block of content json.
The test updates will be coming in the spec repo, but these allow for a test that would use a combination like this example
```kotlin
snapshotTraits(
composeTestRule,
listOf(
"appcues-backdrop",
"appcues-target-rectangle-relative",
"appcues-tooltip",
"appcues-backdrop-keyhole-rectangle",
),
"text-default",
)
```
To produce an image like
> Add support for snapshot testing multiple traits with optional variable step content

- appcues/src/main/java/com/appcues/trait/appcues/TooltipTrait.kt
This update will handle the layout of any tooltip without a target rect - setting width to 400dp (or max for screen), and removing any pointer parameters in the draw. It also improves a little around the logic when transitioning from one step to the next, ensuring the proper `contentDimens` are used when running the next calculation on where to position the pointer.
End result should be a pretty robust handling of un-targeted tips anywhere in the sequence of tooltip steps, showing Android (left) and iOS (right) side-by-side here.
https://user-images.githubusercontent.com/19266448/232903037-8177d99d-d9a1-47e4-a006-f5efd6d0638e.mov
> Handle un-targeted tooltip layout and transitions to and from

- appcues/src/main/java/com/appcues/trait/appcues/TooltipPathExt.kt
This adds some logic to decide when to persist the container cornerRadius value, while still allowing edge positioned content to use a left or right (or top/bottom in horizontal tip) aligned pointer - per discussion on related ticket.
If the desired pointer position (midpoint of target rect) is closer to the rounded edge than the absolute edge, it will use a edge aligned pointer, but still maintain the rounded container edge.
So an example of a tooltip where the desired target is just close enough to maintain the container rounded edges will look like this:
And when the target is determined to be closer to the absolute edge, the container rounded corner is removed (as before) and it will look like this:
This is now in very close parity with the iOS handling of edge positioned tooltip …
> Fix handling of edge positioned tooltips with corner radius on container

- appcues/src/main/java/com/appcues/ElementTargetingStrategy.kt
- appcues/src/main/java/com/appcues/data/remote/appcues/adapters/LossyExperienceResponseAdapterFactory.kt
- appcues/src/main/java/com/appcues/data/remote/appcues/adapters/TraitResponseAdapterFactory.kt
- appcues/src/main/java/com/appcues/trait/TraitExtensions.kt
- appcues/src/main/java/com/appcues/trait/appcues/BackdropTrait.kt
- appcues/src/main/java/com/appcues/trait/extensions/StepAnimationInfoExt.kt
- appcues/src/main/java/com/appcues/trait/extensions/TargetRectangleInfoExt.kt
- appcues/src/main/java/com/appcues/ui/AppcuesOverlayViewManager.kt
- appcues/src/main/java/com/appcues/ui/composables/AppcuesComposition.kt
- appcues/src/main/java/com/appcues/ui/composables/CompositionLocals.kt
- appcues/src/main/java/com/appcues/util/StringExt.kt
- appcues/src/main/java/com/appcues/util/UuidExt.kt
- docs/Traits.md
- docs/VersionMigration.md
Updating docs and revising method/class visibility (from public to internal)
> 📝 Updating docs for 2.0 release

- appcues/src/debug/java/com/appcues/CompositionTestHelper.kt
Minor update in utility function for snapshot trait testing: now supports passing in multiple components in a list. All items are then put into a vertical stack in the experience used for snapshot.
per discussion https://github.com/appcues/appcues-mobile-experience-spec/pull/176#discussion_r1180797742
> Support snapshot testing of multiple components in a vertical stack

- README.md
- release.sh
matching changes from iOS side in https://github.com/appcues/appcues-ios-sdk/pull/400
> Fix release script and CircleCI badge

- docs/VersionMigration.md
This is a requested change from Chris, to lead with the positive/common case first.
> Update the introduction for 2.0 migration doc

- appcues/src/main/java/com/appcues/trait/AppcuesTraitException.kt
- appcues/src/main/java/com/appcues/trait/BackdropDecoratingTrait.kt
- appcues/src/main/java/com/appcues/trait/ContainerDecoratingTrait.kt
- appcues/src/main/java/com/appcues/trait/ContentHolderTrait.kt
- appcues/src/main/java/com/appcues/trait/ContentWrappingTrait.kt
- appcues/src/main/java/com/appcues/trait/ExperienceTrait.kt
- appcues/src/main/java/com/appcues/trait/ExperienceTraitLevel.kt
- appcues/src/main/java/com/appcues/trait/MetadataSettingTrait.kt
- appcues/src/main/java/com/appcues/trait/PresentingTrait.kt
- appcues/src/main/java/com/appcues/trait/StepDecoratingTrait.kt
- appcues/src/main/java/com/appcues/trait/StickyContentPadding.kt
- appcues/src/main/java/com/appcues/ui/composables/CompositionLocals.kt
- appcues/src/main/java/com/appcues/ui/composables/CompositionRemembers.kt
- appcues/src/main/java/com/appcues/ui/utils/BlurHashDecoder.kt
- gradle/tools/detekt/detekt-config.yml
stacks on #401 
enable Detekt [comments rules](https://detekt.dev/docs/rules/comments)
* OutdatedDocumentation
* UndocumentedPublicClass
* UndocumentedPublicFunction
* UndocumentedPublicProperty
+ fix up a few spots it found
(excludes the rule on the sample app)
> Update Detekt config to require comments on public API

- appcues/src/main/java/com/appcues/analytics/AnalyticsKoin.kt
- appcues/src/main/java/com/appcues/analytics/AutoPropertyDecorator.kt
- appcues/src/main/java/com/appcues/util/ContextResources.kt
- appcues/src/test/java/com/appcues/analytics/AutoPropertyDecoratorTest.kt
- appcues/src/test/java/com/appcues/rules/MainDispatcherRule.kt
This is one of the StrictModes we are hitting, because we were trying to use WebView with a non-ui context, we can easily fix this one by getting userAgent from the java framework instead of the WebView class
> 🐛 Fix StrictMode when using non-ui context to get userAgent

- appcues/src/main/java/com/appcues/debugger/screencapture/AndroidTargetingStrategy.kt
changing the logic around displayName, and also including another change to support appcuesId as Compose appcues tag property coming from the JSON selector
> ♻️  update capture screen displayName logic

- appcues/src/main/java/com/appcues/debugger/screencapture/AndroidTargetingStrategy.kt
This is the same correction that was made in React Native over in https://github.com/appcues/appcues-react-native-module/pull/89
I confirmed with logging that the DisplayMetrics used in the implementation here could also give container bounds that did not match the expected visible area when calculating visibility of child views, in the native sample app - which could lead to some views getting excluded unexpectedly from the capture.
> Use the root view bounds when determining if subviews are on screen

- appcues/src/main/java/com/appcues/AppcuesFrame.kt
Adding the interlop for compose!
> ✨ Added AppcuesFrame (compose)

- README.md
- docs/AppcuesFrameViewConfiguring.md
- docs/VersionMigration.md
> Add developer integration doc for embeds

- appcues/src/main/java/com/appcues/data/mapper/experience/ExperienceMapper.kt
quick fix needed to support builder testing
> Check for embed trait at both experience and first step group level

- appcues/src/main/java/com/appcues/DeepLinkHandler.kt
- appcues/src/main/java/com/appcues/analytics/ExperienceLifecycleEvent.kt
- appcues/src/main/java/com/appcues/data/model/RenderContext.kt
- appcues/src/main/java/com/appcues/debugger/DebuggerStatusManager.kt
- appcues/src/main/java/com/appcues/ui/ExperienceRenderer.kt
- appcues/src/main/res/values/strings.xml
adding debugger ability to read multiple experiences.
suggestion to add the frame id when it exists.
> ✨ Debugger displaying multiple experiences

- appcues/src/main/java/com/appcues/statemachine/StateMachine.kt
The scenario:
- an embed is targeted to any screen, but the frame exists on a certain tab (i.e. our embed tab)
- the first time you visit that tab, the frame is registered, qualification runs and everything shows up fine
- dismiss the embed
- go to another tab - another qualification runs, and since the **frame is now in the registry and the view technically still alive, on another tab** - it attempts to start rendering the embed again
- the state machine transitions to BeginningStep, and then pauses waiting on the UI callback to transition to RenderingStep
- revisit the embed tab - this will trigger a reset() (which does a stop() on the state machine) as the view has re-registered the frame - this should stop the current state machine and move it back to Idling and then it will restart …
> Ensure a state machine stop transitions to Idle when waiting on step presentation

- appcues/src/debug/java/com/appcues/ExperienceTestHelper.kt
- appcues/src/main/java/com/appcues/AppcuesConfig.kt
- appcues/src/main/java/com/appcues/AppcuesKoin.kt
- appcues/src/main/java/com/appcues/ui/composables/AppcuesComposition.kt
- appcues/src/main/java/com/appcues/ui/composables/CompositionLocals.kt
- appcues/src/main/java/com/appcues/ui/extensions/ImageLoaderExt.kt
- appcues/src/main/java/com/appcues/ui/presentation/ViewPresenter.kt
- appcues/src/main/java/com/appcues/ui/primitive/ExperiencePrimitive.kt
- appcues/src/main/java/com/appcues/ui/primitive/ImagePrimitive.kt
Idea here is that on Debug variant we can call a different Appcues(...) method that includes an extra property (ImageLoader)
this is helpful for Shot experience testing.
> ♻️  Enable custom ImageLoader on debug variant

- appcues/src/main/java/com/appcues/data/AppcuesRepository.kt
Recent set of PRs had conflicting changes that led to a compile error - patching up.
> Fix the build after conflicting merges

- appcues/src/main/java/com/appcues/action/appcues/LinkAction.kt
- appcues/src/test/java/com/appcues/DeeplinkHandlerTest.kt
- appcues/src/test/java/com/appcues/action/ActionProcessorTest.kt
- appcues/src/test/java/com/appcues/action/appcues/CloseActionTest.kt
- appcues/src/test/java/com/appcues/action/appcues/ContinueActionTest.kt
- appcues/src/test/java/com/appcues/action/appcues/LaunchExperienceActionTest.kt
- appcues/src/test/java/com/appcues/action/appcues/LinkActionTest.kt
- appcues/src/test/java/com/appcues/action/appcues/RequestReviewActionTest.kt
- appcues/src/test/java/com/appcues/action/appcues/TrackEventActionTest.kt
- appcues/src/test/java/com/appcues/data/mapper/step/StepMapperTest.kt
- appcues/src/test/java/com/appcues/data/remote/NetworkRequestTest.kt
- appcues/src/test/java/com/appcues/data/remote/customerapi/CustomerApiRemoteSourceTest.kt
- appcues/src/test/java/com/appcues/data/remote/imageupload/ImageUploadRemoteSourceTest.kt
- appcues/src/test/java/com/appcues/data/remote/sdksettings/SdkSettingsRemoteSourceTest.kt
- appcues/src/test/java/com/appcues/logging/LogcuesTest.kt
- appcues/src/test/java/com/appcues/monitor/AppcuesActivityMonitorTest.kt
- appcues/src/test/java/com/appcues/util/DoubleExtTest.kt
- appcues/src/test/java/com/appcues/util/FloatExtTest.kt
Adding some relevant unit test coverage all around
> ✅ updating custom action unit tests

- appcues/build.gradle
- appcues/src/main/java/com/appcues/ui/presentation/AppcuesViewModel.kt
- appcues/src/main/java/com/appcues/ui/presentation/ViewPresenter.kt
- appcues/src/test/java/com/appcues/ui/presentation/AppcuesViewModelTest.kt
Was able to put together some valid tests for AppcuesViewModel
when testing state the idea here is that during setup() we observe and put all states in a list.
then when testing we can check the list size and type check elements
> ✅ AppcuesViewModel Tests

- appcues/src/main/java/com/appcues/debugger/ui/DebuggerPanel.kt
For the fixed up usage in https://github.com/appcues/appcues-mobile-experience-spec/pull/224
> Add a test tag for debugger UI tests

- appcues/src/main/java/com/appcues/analytics/ExperienceLifecycleTracker.kt
small inconsistency found where the onEndedExperience callback is only being called for published experiences, where it should be called for any experience
> 🐛 onEndedExperience should be called for every experience

- appcues/src/main/java/com/appcues/MainModule.kt
- appcues/src/main/java/com/appcues/di/Bootstrap.kt
- appcues/src/main/java/com/appcues/ui/utils/ImageLoaderWrapper.kt
- appcues/src/test/java/com/appcues/ModulesTests.kt
- appcues/src/test/java/com/appcues/action/ActionProcessorTest.kt
- appcues/src/test/java/com/appcues/analytics/ExperienceLifecycleTrackerTest.kt
- appcues/src/test/java/com/appcues/di/BootstrapTest.kt
- appcues/src/test/java/com/appcues/rules/TestScopeRule.kt
- appcues/src/test/java/com/appcues/ui/ExperienceRendererTest.kt
Changed around how we create ImageLoader to enable for injection testing.
we can now verify that we are using the proper imageLoader based on AppcuesConfig
> ✅ Added Image Loader injection Test

- appcues/src/main/java/com/appcues/ui/modal/DialogModal.kt
[sc-57867]
one-liner to fix the application of margin on slideouts - the width needs to be set _after_ the margin
snapshot test update coming that validates
> Fix margin handling with slideout modal

- appcues/src/debug/java/com/appcues/ActivityMonitorTestHelper.kt
This is to support new Roborazzi tests in the spec repo at https://github.com/appcues/appcues-mobile-experience-spec/compare/feature/roborazzi
> Add function for test automation with activity monitor

- appcues/src/main/java/com/appcues/debugger/ui/CaptureConfirmDialog.kt
As part of this [ticket](https://app.shortcut.com/appcues/story/58343/add-target-overlay-and-help-text-to-the-screen-capture-confirm-screen). we need to include a highlighting overlay for selectable elements during screen capture.
this is how it looks after this change:
> ✨ Add Overlay to highlight selectable elements

- appcues/src/main/java/com/appcues/debugger/screencapture/AndroidTargetingStrategy.kt
Previously, we were not confirming that Compose view rects intersected the bounds of the visible screen, which is corrected here. Also, we did not have any policy around how much of a target element (Android View or Composable) needed to be visible, to render targeted content (i.e. have a selector). Now, we have a policy in place that at least the center point of the view must be visible.
This example illustrates the handling before and after. This is a view with a horizontal scrolling composable section at the bottom, as well as a horizontal pager. Prior to this change, as elements are laid out off-screen in preparation for a UI gesture to bring them into view, we were recognizing them in the view hierarchy and generating selectors. This led to snapshots where tooltips could be targeted …
> Ensure that compose elements are within screen bounds

- appcues/src/main/java/com/appcues/debugger/DebuggerStatusManager.kt
- appcues/src/main/res/values/strings.xml
adding extra row in the debugger to identify Group same way we identify userId
> ✨ Added group identification row in debugger

- samples/kotlin-android-app/src/main/java/com/appcues/samples/kotlin/main/EventsFragment.kt
- samples/kotlin-android-app/src/main/java/com/appcues/samples/kotlin/main/MainActivity.kt
- samples/kotlin-android-app/src/main/java/com/appcues/samples/kotlin/main/RecyclerViewFragment.kt
- samples/kotlin-android-app/src/main/res/layout/fragment_events.xml
- samples/kotlin-android-app/src/main/res/layout/fragment_recyclerview.xml
- samples/kotlin-android-app/src/main/res/layout/view_adapter_item.xml
- samples/kotlin-android-app/src/main/res/navigation/example_navigation.xml
- samples/kotlin-android-app/src/main/res/values/strings.xml
Adding RecyclerView list, had a tough time setting up navigation but I think its at a good point now
> ♻️  Adding RecyclerView list

- appcues/src/main/java/com/appcues/Appcues.kt
- appcues/src/main/java/com/appcues/Storage.kt
Adding new API call to register push token and set it in Storage (shared preferences)
> ✨ Adding Appcues.setPushToken method

- appcues/src/main/java/com/appcues/analytics/AutoPropertyDecorator.kt
- appcues/src/main/java/com/appcues/data/remote/appcues/request/EventRequest.kt
- appcues/src/main/java/com/appcues/debugger/DebuggerRecentEventsManager.kt
- appcues/src/main/java/com/appcues/debugger/ui/events/DebuggerEventDetails.kt
- appcues/src/main/res/values/strings.xml
- appcues/src/test/java/com/appcues/analytics/AutoPropertyDecoratorTest.kt
* Adding "_pushToken" to device properties
* Improving visual representation of the "_device" property set for debugger.
> ✨ Adding _pushToken property

- appcues/src/main/java/com/appcues/Appcues.kt
- appcues/src/main/java/com/appcues/analytics/AnalyticsEvent.kt
- appcues/src/main/java/com/appcues/debugger/ui/DebuggerExt.kt
- appcues/src/main/res/values/strings.xml
- appcues/src/test/java/com/appcues/analytics/AutoPropertyDecoratorTest.kt
* Adding device_unregistered event
* Updating debugger
> ✨ Adding device unregistered event

- appcues/src/main/java/com/appcues/analytics/AutoPropertyDecorator.kt
- appcues/src/main/java/com/appcues/util/ContextWrapper.kt
- appcues/src/test/java/com/appcues/analytics/AutoPropertyDecoratorTest.kt
- samples/kotlin-android-app/src/main/AndroidManifest.xml
* Including _pushEnabled property
* Adding permission to sample app so we can toggle on/off the permission
> ✨ Adding _pushEnabled property

- appcues/src/debug/java/com/appcues/ExperienceTestHelper.kt
- appcues/src/main/java/com/appcues/AppcuesConfig.kt
- appcues/src/main/java/com/appcues/data/remote/DataRemoteModule.kt
separate (cherry-pick) from sdk4 branch to fix automated tests
related PR https://github.com/appcues/appcues-mobile-experience-spec/pull/252
> 👌 Enabling custom path for api settings path

- appcues/src/main/java/com/appcues/ui/modal/FullScreenModal.kt
Reported on 3.1.13 from a customer, the background is not properly being applied on full modal style.
> 🐛 Fix Bug where background color was not properly being applied

- appcues/src/main/java/com/appcues/DeepLinkHandler.kt
- appcues/src/main/java/com/appcues/MainModule.kt
- appcues/src/main/java/com/appcues/data/PushRepository.kt
- appcues/src/main/java/com/appcues/data/remote/appcues/AppcuesRemoteSource.kt
- appcues/src/main/java/com/appcues/data/remote/appcues/AppcuesService.kt
- appcues/src/main/java/com/appcues/data/remote/appcues/request/PushRequest.kt
- appcues/src/test/java/com/appcues/data/AppcuesRepositoryTest.kt
- appcues/src/test/java/com/appcues/data/PushRepositoryTest.kt
Adding deeplinks will be used by builder for push preview, and push content, both can be called directly in order to trigger push to pop-up
> ✨ Adding push_preview and push_content deeplinks

- appcues/src/main/java/com/appcues/push/PushDeeplinkHandler.kt
- appcues/src/main/java/com/appcues/push/PushOpenedAction.kt
- appcues/src/main/java/com/appcues/push/PushOpenedProcessor.kt
* Fix that allows redirect and show content on preview push
> 🐛 Fix Push Opened Action for preview

- release.sh
temporary change to release script so we can work release from sdk4 branch
> ♻️  Update release script for sdk4 branch

- appcues/src/main/java/com/appcues/Appcues.kt
small improvement I would like to try, so on new installations of firebase it seems like the "onNewToken" is called, but then after that its never called again (unless the token changes), so this means customers would need to always get the current token and set in order to ensure we have that information set in the SDK, or else they could update Appcues on an already existing FirebaseMessagingService installation and never get setPushToken called.
> ♻️  Auto collecting push token whenever appcues is instanciated

- appcues/src/main/java/com/appcues/Appcues.kt
Posting my idea here to slightly revise the auto token collection from #605 . I believe the benefits may be
1. The debugger will see the token (from storage) even if a user has not been identified yet, to avoid any confusion like we had today on whether the token was actually being captured for push
2. Avoid any potential race condition where a session start would occur before the Firebase callback that sets the global token variable (temp storage)
> Revise automatic push token collection

- appcues/src/main/java/com/appcues/ui/ModalStateMachineOwner.kt
Reported in issue #616 
Replacing timer with debounce logic using coroutines since Timer appears to cause memory leak. [REF1](https://androidtrainningcenter.blogspot.com/2013/12/handler-vs-timer-fixed-period-execution.html)
> 🐛 Fix Timer memory leak on anchored tooltip retry

- README.md
including pre-requisites section like we have for x-platform repos and adding specific section regarding compose 1.6
> 📝 updating readme to include prerequisites

- .idea/deploymentTargetSelector.xml
- .idea/other.xml
- README.md
- appcues/src/main/java/com/appcues/util/ContextDensity.kt
- docs/PushNotification.md
- samples/kotlin-android-app/src/main/java/com/appcues/samples/kotlin/ExampleApplication.kt
* Adding push notification docs and linking on the main page
* Removing duplicate block of code to keep push token updated (happens internally on every appcues init)
> 📝 push notification docs and update example app

- appcues/src/main/java/com/appcues/AnalyticsPublisher.kt
from support [thread](https://appcues.slack.com/archives/C03JYPH1NJZ/p1725461076933259) we need to sanatize all events
+ sanatize UUID to string value
> 🐛 Add required sanatize for all events + UUID sanatize

- appcues/src/main/java/com/appcues/analytics/AutoPropertyDecorator.kt
- appcues/src/test/java/com/appcues/analytics/AutoPropertyDecoratorTest.kt
Adding new property to autoprops and device pro (_timezoneCode)
> ✨ Adding _timezoneCode

- appcues/src/debug/java/com/appcues/ExperienceTestHelper.kt
- appcues/src/main/java/com/appcues/AppcuesConfig.kt
- appcues/src/main/java/com/appcues/MainModule.kt
- appcues/src/main/java/com/appcues/debugger/AppcuesDebuggerManager.kt
- appcues/src/main/java/com/appcues/debugger/DebuggerLogMessageManager.kt
- appcues/src/main/java/com/appcues/debugger/DebuggerModule.kt
- appcues/src/main/java/com/appcues/debugger/DebuggerRecentEventsManager.kt
- appcues/src/main/java/com/appcues/debugger/DebuggerStatusManager.kt
- appcues/src/main/java/com/appcues/debugger/model/DebuggerConstants.kt
- appcues/src/main/java/com/appcues/debugger/ui/main/DebuggerStatusItems.kt
- appcues/src/main/java/com/appcues/debugger/ui/theme/AppcuesDarkColors.kt
- appcues/src/main/java/com/appcues/debugger/ui/theme/AppcuesLightColors.kt
- appcues/src/main/java/com/appcues/debugger/ui/theme/AppcuesTheme.kt
- appcues/src/main/java/com/appcues/debugger/ui/theme/AppcuesThemeColors.kt
- appcues/src/main/res/values/strings.xml
Small increment on Screenshot tests, debugger screens now have fixed version number and dates, so they can be screenshot tested.
> ✅ Enable screen shots tests for debugger

- .gitignore
- appcues/src/main/java/com/appcues/analytics/ExperienceLifecycleEvent.kt
- appcues/src/main/java/com/appcues/data/mapper/experience/ExperienceMapper.kt
- appcues/src/main/java/com/appcues/data/model/Experience.kt
- appcues/src/main/java/com/appcues/data/remote/appcues/response/experience/ExperienceResponse.kt
- appcues/src/test/java/com/appcues/action/appcues/SubmitFormActionTest.kt
- appcues/src/test/java/com/appcues/analytics/ExperienceLifecycleEventTest.kt
- appcues/src/test/java/com/appcues/analytics/ExperienceLifecycleTrackerTest.kt
- appcues/src/test/java/com/appcues/data/mapper/experience/ExperienceMapperTest.kt
- appcues/src/test/java/com/appcues/data/model/ExperienceTest.kt
- appcues/src/test/java/com/appcues/mocks/ExperienceMocks.kt
- appcues/src/test/java/com/appcues/statemachine/StateMachineTest.kt
Android version of https://github.com/appcues/appcues-ios-sdk/pull/589
> Add workflow details to experience analytics

- appcues/src/main/java/com/appcues/debugger/screencapture/AndroidTargetingStrategy.kt
Fix found while implementing https://github.com/appcues/appcues-react-native-module/pull/194
1. Ensure web view elements outside the webview frame are ignored
> Ensure web view elements are visible
